"""Accompaniments, drinks and the nationally known sweets the collection had
strong regional versions of but no plain, searchable recipe for."""
from add_recipes import R

E, M, A = "easy", "moderate", "advanced"
STOVE, PC, STEAM, BLEND, OVEN, KADHAI, TAWA = (
    "stovetop", "pressure-cooker", "steamer", "blender", "oven", "kadhai", "tawa")
VEG, VGN, GF, DF, NF, NOG = (
    "vegetarian", "vegan", "gluten-free", "dairy-free", "nut-free", "no-onion-garlic")

BATCH = [

R("paneer-do-pyaza", "Paneer Do Pyaza", "Awadhi/Lucknowi",
  "paneer with onion twice over, once melted into the gravy and once in soft petals",
  4, 15, 30, E, [STOVE, KADHAI], [VEG, GF, NF], ["dairy"],
  [("paneer", "400g, in thick fingers", None, True),
   ("onion", "5, two chopped fine and three in petals", "the name means two onions, and it is literal", True),
   ("tomato", "300g, chopped", None, True),
   ("yogurt", "100g, whisked", None, True),
   ("ginger", "1 tbsp paste", None, True),
   ("garlic", "1 tbsp paste", None, True),
   ("coriander-powder", "2 tsp", None, True),
   ("chilli-powder", "1.5 tsp", None, True),
   ("turmeric", "1/2 tsp", None, True),
   ("garam-masala", "1 tsp", None, True),
   ("kasuri-methi", "1 tbsp", None, True),
   ("neutral-oil", "4 tbsp", None, True),
   ("coriander-leaves", "a handful", None, False),
   ("salt", "to taste", None, True)],
  ["The two onions do different jobs. The chopped one dissolves into the gravy; the petals go in at the end and must stay separate and sweet.",
   "Take the yogurt off the heat before it goes in, or it splits."],
  [("Fry the chopped onion in oil for 12 minutes until deep brown, then add ginger and garlic.",),
   ("Add the ground spices with a splash of water, then the tomato, and cook until the oil separates.",),
   ("Take the pan off the heat, whisk in the yogurt, and only then return it to a low flame.",
    "Off the heat, always. Yogurt added to a hot pan curdles instantly."),
   ("Simmer 5 minutes with a little water to a thick gravy.",),
   ("In a separate pan sear the onion petals hard for 2 minutes so they colour but keep their bite, and add the paneer for a minute.",),
   ("Fold the petals and paneer through the gravy, add kasuri methi and garam masala, and rest 5 minutes off the heat.",)],
  "Keeps 2 days refrigerated. The onion petals soften overnight, which loses the contrast the dish is named for.",
  ["bhuna"]),

R("vegetable-korma", "Vegetable Korma", "Kerala",
  "mixed vegetables in a mild coconut and cashew gravy, southern style",
  4, 20, 30, E, [STOVE, BLEND], [VEG, GF], ["nuts"],
  [("carrot", "150g, diced", None, True),
   ("french-beans", "100g", None, True),
   ("potato", "200g, diced", None, True),
   ("peas", "100g", None, True),
   ("cauliflower", "150g", None, False),
   ("coconut", "100g, fresh grated", None, True),
   ("cashew", "40g", None, True),
   ("coconut-milk", "200ml", None, True),
   ("onion", "2, sliced", None, True),
   ("green-chilli", "3, slit", None, True),
   ("ginger", "1 tbsp", None, True),
   ("garlic", "4 cloves", None, True),
   ("fennel-seeds", "1 tsp", None, True),
   ("cardamom", "3", None, True),
   ("cinnamon", "1 piece", None, True),
   ("cloves", "3", None, True),
   ("curry-leaves", "2 sprigs", None, True),
   ("coconut-oil", "3 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["The southern korma leans on coconut rather than cream, and on fennel rather than garam masala. It should taste sweet and aromatic, not rich.",
   "Add the thick coconut milk off the heat. Boiled coconut milk separates into oil and grit."],
  [("Blend the grated coconut, cashews, fennel and a little water to a fine paste.",
    "Fine. Any grit here stays gritty in the finished dish."),
   ("Fry the whole spices and curry leaves in coconut oil, then the onion until soft but not brown.",
    "Not brown. This gravy should stay pale."),
   ("Add ginger, garlic and green chilli, then the vegetables and enough hot water to barely cover.",),
   ("Simmer covered until the vegetables are just tender, about 12 minutes.",),
   ("Stir in the coconut-cashew paste and cook 5 minutes until it thickens.",),
   ("Take off the heat, stir in the thick coconut milk, and check the salt.",
    "Off the heat. This is the step people get wrong.")],
  "Keeps 2 days refrigerated. Reheat very gently; coconut milk splits on a hard boil. Not suitable for freezing.",
  ["curry-leaves"]),

R("malabar-parotta", "Malabar Parotta", "Kerala",
  "layered, flaky flatbread slapped and coiled so it pulls apart in sheets",
  6, 30, 30, A, [TAWA, STOVE], [VEG, NF], ["gluten"],
  [("maida", "500g", None, True),
   ("eggs", "1", "optional, for softness", False),
   ("sugar", "1 tsp", None, True),
   ("milk", "100ml", "or water; omit for a dairy-free parotta", False),
   ("neutral-oil", "100ml", None, True),
   ("salt", "1 tsp", None, True)],
  ["The layers come from oil, stretching and coiling, not from folding like a paratha. The dough must be rested long enough to stretch paper thin without tearing.",
   "Rest twice: once after kneading, once after shaping into balls. Two hours total is the minimum."],
  [("Knead the maida with salt, sugar, egg and milk into a very soft dough, adding water as needed. Work it 10 minutes.",),
   ("Coat with oil, cover, and rest 1 hour.",),
   ("Divide into 8, roll each into an oiled ball, and rest another hour.",
    "The second rest is what lets the dough stretch without tearing."),
   ("Flatten a ball on an oiled surface and stretch it outward with your palms until nearly transparent.",
    "Stretch, do not roll. A rolling pin cannot make it thin enough."),
   ("Pleat the sheet like a fan along its length, then coil the strip into a spiral and tuck the end under. Rest 15 minutes.",),
   ("Flatten the coil gently to a 15cm round and cook on a hot tawa with oil, 2 minutes a side, until golden and blistered.",),
   ("While hot, clap the parotta between your palms to loosen the layers.",
    "The clap is not showmanship. It is what separates the sheets.")],
  "Best hot. They keep a day wrapped and reheat on a dry tawa. Coiled uncooked dough keeps 24 hours refrigerated and cooks straight from cold.",
  ["resting-dough"]),

R("fish-tikka", "Fish Tikka", "Punjabi",
  "firm fish in a carom and ajwain marinade, grilled hard and hit with lemon",
  4, 25, 15, E, [OVEN, TAWA], [GF, NF, "pescatarian"], ["fish", "dairy"],
  [("fish", "700g firm fillets, in 4cm chunks", "firm fish only: soft fillets fall through the grill", True),
   ("yogurt", "150g, hung", None, True),
   ("besan", "2 tbsp, roasted", "stops the marinade sliding off", True),
   ("ajwain", "1 tsp", "the classic pairing with fish", True),
   ("ginger", "1 tbsp paste", None, True),
   ("garlic", "1 tbsp paste", None, True),
   ("kashmiri-chilli", "2 tsp", None, True),
   ("turmeric", "1/2 tsp", None, True),
   ("chaat-masala", "1 tsp", None, True),
   ("lemon", "2", None, True),
   ("mustard-oil", "2 tbsp, smoked and cooled", None, True),
   ("salt", "to taste", None, True)],
  ["Marinate fish for 30 minutes, not hours. Lemon and yogurt begin to cure it, and cured fish goes chalky on the grill.",
   "Roast the besan first. Raw gram flour tastes of raw gram flour."],
  [("Pat the fish dry and rub with lemon juice, salt and turmeric. Rest 10 minutes, then pat dry again.",
    "Drying twice is what lets the marinade grip."),
   ("Whisk the hung yogurt with roasted besan, ajwain, ginger, garlic, kashmiri chilli and the cooled mustard oil.",),
   ("Coat the fish and refrigerate 30 minutes only.",),
   ("Thread onto skewers or lay on an oiled rack and cook at 230C for 10 minutes.",),
   ("Finish under a hot grill for 3 minutes until the edges char.",),
   ("Dust with chaat masala and squeeze lemon over just before serving.",)],
  "Eat within the hour; reheated fish tikka is dry. The marinated raw fish should be cooked the same day.",
  []),

R("seekh-kebab", "Seekh Kebab", "Punjabi",
  "spiced minced meat moulded onto skewers and grilled until charred",
  4, 25, 20, M, [OVEN, TAWA], [GF, DF, NF], [],
  [("mutton", "600g, minced twice, with some fat", "lean mince gives a dry, crumbling kebab", True),
   ("onion", "1, grated and squeezed bone dry", None, True),
   ("ginger", "1 tbsp paste", None, True),
   ("garlic", "1 tbsp paste", None, True),
   ("green-chilli", "3, very finely chopped", None, True),
   ("coriander-leaves", "a large handful, chopped", None, True),
   ("mint", "a handful, chopped", None, False),
   ("besan", "2 tbsp, roasted", None, True),
   ("garam-masala", "1.5 tsp", None, True),
   ("coriander-powder", "1 tsp", None, True),
   ("cumin-powder", "1 tsp", None, True),
   ("chaat-masala", "1 tsp, to finish", None, False),
   ("neutral-oil", "3 tbsp, for basting", None, True),
   ("salt", "to taste", None, True)],
  ["Water is the enemy. Squeeze the grated onion until it is genuinely dry, or the mince slides off the skewer.",
   "Chill the mix hard before shaping. Cold mince grips; warm mince sags."],
  [("Squeeze every drop from the grated onion, using a cloth if necessary.",
    "Genuinely dry. This is the step that decides whether the kebabs survive the grill."),
   ("Knead the mince with the onion, ginger, garlic, chilli, herbs, roasted besan, ground spices and salt for 5 minutes until it turns sticky.",
    "Kneading develops the protein that binds it. Gentle mixing is not enough."),
   ("Chill at least 1 hour.",),
   ("Take a handful, press it around a flat skewer, and work it along into a sausage about 2cm thick, pinching ridges as you go.",),
   ("Grill at high heat, 230C, turning every few minutes and basting with oil, for 12 minutes.",),
   ("Char the outside under the grill for 2 minutes, rest briefly, then dust with chaat masala and serve with onion and lemon.",)],
  "Best straight off the skewer. The raw mix keeps 24 hours refrigerated and freezes a month; cooked kebabs dry out on reheating.",
  []),

R("boondi-raita", "Boondi Raita", "Punjabi",
  "gram flour pearls soaked soft in spiced yogurt",
  4, 15, 15, E, [STOVE, KADHAI], [VEG, GF, NF], ["dairy"],
  [("besan", "120g", None, True),
   ("yogurt", "500g, whisked smooth", None, True),
   ("cumin-powder", "1.5 tsp, roasted", None, True),
   ("black-salt", "1 tsp", None, True),
   ("chilli-powder", "1/2 tsp", None, False),
   ("coriander-leaves", "a handful", None, False),
   ("mint", "a few leaves", None, False),
   ("neutral-oil", "400ml", "for frying the boondi", True),
   ("salt", "to taste", None, True)],
  ["Boondi must be soaked in warm water and squeezed before it goes into the yogurt. Dropped in dry, it stays hard and the raita turns to paste around it.",
   "The batter should pour off a spoon in a thin stream. Thick batter gives tails instead of round pearls."],
  [("Whisk the besan with water and a pinch of salt into a smooth, thin, pouring batter.",),
   ("Hold a perforated spoon above hot oil at 180C and pour the batter through it so droplets fall in.",
    "Hold the spoon high enough that the drops round off on the way down."),
   ("Fry 1 minute until pale and crisp, drain, and cool.",),
   ("Soak the boondi in warm water for 5 minutes, then squeeze gently between your palms.",
    "This is the step almost everyone skips, and it is the difference between good raita and gritty yogurt."),
   ("Whisk the yogurt with salt, black salt and roasted cumin until pourable.",),
   ("Fold in the squeezed boondi, chill 20 minutes, and finish with chilli powder and herbs.",)],
  "Best within a few hours; the boondi keeps softening. Plain fried boondi keeps two weeks airtight.",
  []),

R("cucumber-raita", "Cucumber Raita", "Punjabi",
  "grated cucumber in cumin-spiked yogurt, the standard cooling side",
  4, 10, 0, E, [], [VEG, GF, NF, NOG], ["dairy"],
  [("cucumber", "2, grated", None, True),
   ("yogurt", "500g, whisked", None, True),
   ("cumin-powder", "1.5 tsp, roasted", None, True),
   ("black-salt", "1/2 tsp", None, True),
   ("chilli-powder", "1/2 tsp", None, False),
   ("mint", "a few leaves, chopped", None, False),
   ("coriander-leaves", "a handful", None, False),
   ("salt", "to taste", None, True)],
  ["Salt the grated cucumber and squeeze it. Cucumber is mostly water and unsqueezed it turns the raita into a drink within twenty minutes.",
   "Roast and grind the cumin yourself if you can. Pre-ground roasted cumin loses its point quickly."],
  [("Grate the cucumber coarsely, salt it lightly, and leave 10 minutes.",),
   ("Squeeze out the water firmly with your hands.",
    "Firmly. You should be left with about half the volume you started with."),
   ("Whisk the yogurt until completely smooth, adding a spoon of water if it is very thick.",),
   ("Fold in the cucumber with roasted cumin, black salt and salt.",),
   ("Chill 20 minutes and finish with chilli powder, mint and coriander.",
    "Season again after chilling. Cold dulls salt.")],
  "Keeps a day refrigerated, though it loosens. Do not freeze.",
  []),

R("mint-coriander-chutney", "Mint-Coriander Chutney", "Punjabi",
  "the sharp green chutney that goes with everything fried",
  8, 10, 0, E, [BLEND], [VEG, VGN, GF, DF, NF], [],
  [("mint", "a large bunch, leaves only", "leaves only: the stalks are bitter", True),
   ("coriander-leaves", "a large bunch, stalks included", None, True),
   ("green-chilli", "3", None, True),
   ("ginger", "2cm piece", None, False),
   ("garlic", "2 cloves", None, False),
   ("lemon", "1", None, True),
   ("cumin-powder", "1 tsp, roasted", None, True),
   ("black-salt", "1/2 tsp", None, True),
   ("sugar", "1/2 tsp", "steadies the colour", False),
   ("salt", "to taste", None, True)],
  ["Use mint leaves only but coriander stalks and all. Mint stalks are bitter; coriander stalks carry most of the flavour.",
   "Blend with ice-cold water. Heat from the blade is what turns the chutney brown."],
  [("Pick the mint leaves off the stalks. Wash both herbs and shake dry.",),
   ("Put everything in the blender with 3 or 4 ice cubes and the lemon juice.",
    "The ice keeps the blade cool and the colour bright green."),
   ("Blend in short bursts, scraping down, until smooth. Add as little water as you can.",),
   ("Taste for salt, sourness and heat, and adjust; it should be sharper than seems comfortable on its own.",
    "It is eaten with fried food, so it needs to cut through."),
   ("Store in a jar with a film of oil on top if keeping more than a day.",)],
  "Keeps 4 days refrigerated in a sealed jar and freezes well in ice cube trays for 3 months. It darkens after a day but the flavour holds.",
  []),

R("tamarind-date-chutney", "Tamarind-Date Chutney", "Punjabi",
  "the dark sweet-sour chutney that every chaat needs",
  10, 10, 30, E, [STOVE, BLEND], [VEG, VGN, GF, DF, NF, NOG], [],
  [("tamarind", "150g block", None, True),
   ("dates", "150g, pitted", None, True),
   ("jaggery", "100g", None, True),
   ("cumin-powder", "2 tsp, roasted", None, True),
   ("fennel-powder", "1 tsp", None, False),
   ("dry-ginger-powder", "1 tsp", None, True),
   ("chilli-powder", "1 tsp", None, True),
   ("black-salt", "1.5 tsp", None, True),
   ("salt", "to taste", None, True)],
  ["Dates do more than sweeten: they give the body that stops the chutney being watery. Jaggery alone gives a thin syrup.",
   "Make it looser than you want. It thickens considerably as it cools."],
  [("Soak the tamarind and dates in 600ml hot water for 30 minutes.",),
   ("Simmer the lot for 15 minutes until the dates collapse.",),
   ("Cool, then blend and pass through a sieve, pressing hard to get everything through.",
    "Sieving is what makes it glossy rather than fibrous."),
   ("Return to the pan with the jaggery and cook 10 minutes until it coats a spoon.",),
   ("Stir in the roasted cumin, dry ginger, fennel, chilli powder, black salt and salt.",),
   ("Cool completely before bottling. It thickens as it stands.",)],
  "Keeps 3 weeks refrigerated in a sterile jar and freezes for 6 months. If it sets too firm, loosen with a little hot water.",
  []),

R("mango-pickle", "Mango Pickle", "Punjabi",
  "raw mango cured in salt then packed with mustard, fennel and oil",
  20, 40, 0, M, [], [VEG, VGN, GF, DF, NF, NOG], [],
  [("raw-mango", "1kg firm and sour, cut into 2cm pieces with the stone shell", None, True),
   ("mustard-oil", "400ml", None, True),
   ("mustard-seeds", "5 tbsp, coarsely ground", None, True),
   ("fennel-seeds", "4 tbsp, coarsely ground", None, True),
   ("fenugreek-seeds", "2 tbsp, coarsely ground", None, True),
   ("nigella", "1 tbsp", None, True),
   ("turmeric", "3 tbsp", None, True),
   ("chilli-powder", "3 tbsp", None, True),
   ("asafoetida", "1/2 tsp", None, False),
   ("salt", "120g", "the preservative, so do not reduce it", True)],
  ["Everything must be bone dry: the mango, the jar, the spoon, your hands. A single drop of water is how a pickle grows mould.",
   "The first salting draws out the water that would otherwise spoil it. Do not shorten it."],
  [("Wash and dry the mango pieces thoroughly, then spread them on a cloth for 2 hours until the surface is completely dry.",
    "Completely dry. This is not a step to rush."),
   ("Toss with the salt and turmeric, pack into a dry jar, and leave 2 days, shaking daily.",),
   ("Drain off the liquid that has collected and dry the pieces again in the sun or a low oven for an hour.",),
   ("Heat the mustard oil to smoking, then cool it completely.",
    "Smoking then cooled: raw mustard oil is harsh and can spoil the pickle."),
   ("Mix the ground spices, nigella and asafoetida with the mango, then pour over enough cooled oil to submerge everything.",),
   ("Seal and leave in the sun 7 to 10 days, shaking daily, until the mango softens and darkens.",
    "The oil must always sit above the mango. Top it up if the level drops.")],
  "Keeps a year in a cool dark place if the oil covers the pickle and only a dry spoon ever goes in. Refrigeration is unnecessary and dulls it.",
  ["hing"]),

R("mango-lassi", "Mango Lassi", "Punjabi",
  "ripe mango blended with yogurt into a thick, cold drink",
  2, 5, 0, E, [BLEND], [VEG, GF, NF, NOG], ["dairy"],
  [("raw-mango", "2 ripe, flesh only, about 350g", "ripe and sweet, not the sour pickling kind", True),
   ("yogurt", "300g, cold", None, True),
   ("milk", "100ml, cold", None, False),
   ("sugar", "2 tbsp, or to taste", None, True),
   ("cardamom", "2, seeds ground", None, False),
   ("saffron", "a few strands", None, False),
   ("salt", "a pinch", "lifts the mango", False)],
  ["Chill everything first. Ice thins the drink; cold ingredients keep it thick.",
   "Taste the mango before you add sugar. A good ripe mango may need none at all."],
  [("Cut the mango flesh away from the stone and chill it, along with the yogurt and milk.",),
   ("Blend the mango to a smooth puree on its own first.",
    "On its own, so any fibres break down before the yogurt is added."),
   ("Add the cold yogurt, milk, sugar and the pinch of salt, and blend briefly.",
    "Briefly. Over-blending yogurt makes it thin and frothy."),
   ("Taste and adjust the sugar.",),
   ("Pour into chilled glasses and finish with ground cardamom and a few saffron strands.",)],
  "Drink within a few hours. It separates in the fridge; whisk to bring it back. Freezes well as kulfi-style lollies.",
  []),

R("lassi", "Sweet or Salted Lassi", "Punjabi",
  "yogurt churned with water until light and foaming, sweet or salted",
  2, 5, 0, E, [BLEND], [VEG, GF, NF, NOG], ["dairy"],
  [("yogurt", "400g, cold and not too sour", None, True),
   ("water", "200ml, cold", None, True),
   ("sugar", "3 tbsp", "for the sweet version", False),
   ("salt", "1/2 tsp", "for the salted version", False),
   ("cumin-powder", "1 tsp, roasted", "salted version only", False),
   ("black-salt", "1/4 tsp", "salted version only", False),
   ("cardamom", "2, ground", "sweet version only", False),
   ("rose-water", "a few drops", "sweet version only", False)],
  ["Sweet and salted are not variations of one drink; they are two drinks. Do not try to make something in between.",
   "The froth is the point. Churn hard, and serve before it settles."],
  [("Whisk the cold yogurt alone until completely smooth, with no lumps.",),
   ("Add the cold water gradually, whisking or blending, until it lightens and a head of foam forms.",
    "Gradually. Dumping the water in gives a thin, flat drink."),
   ("For sweet lassi, add sugar, ground cardamom and a drop of rose water.",),
   ("For salted, add salt, black salt and roasted cumin instead.",),
   ("Churn once more to raise the foam and pour into chilled glasses.",),
   ("Serve at once, with the foam still standing.",)],
  "Drink fresh. It separates within an hour and never quite recovers.",
  []),

R("masala-chai", "Masala Chai", "Punjabi",
  "black tea boiled hard with milk, ginger and whole spices",
  4, 5, 12, E, [STOVE], [VEG, GF, NF, NOG], ["dairy"],
  [("milk", "400ml", None, True),
   ("water", "400ml", None, True),
   ("sugar", "4 tsp, or to taste", None, True),
   ("ginger", "3cm piece, crushed", "crushed, not sliced, so it gives up its heat", True),
   ("cardamom", "4, crushed", None, True),
   ("cloves", "2", None, False),
   ("cinnamon", "1 small piece", None, False),
   ("black-pepper", "3 corns, crushed", None, False),
   ("fennel-seeds", "1/2 tsp", None, False)],
  ["Chai is boiled, not steeped. The tea, spices, milk and sugar go through several hard boils together.",
   "Crush the ginger and cardamom rather than chopping. Bruised, they release more into a short boil."],
  [("Bring the water to the boil with the crushed ginger and whole spices, and let it boil 3 minutes.",
    "Water and spices first, alone. Milk added now would blunt them."),
   ("Add the tea leaves and boil 2 minutes until very dark.",),
   ("Pour in the milk and the sugar and bring it back to a rolling boil.",),
   ("Let it rise up the pan, pull it off the heat as it climbs, and return it. Do this three times.",
    "The repeated rise is what thickens chai and marries the milk with the tea."),
   ("Strain into cups from a height so it froths.",)],
  "Make it fresh. Reheated chai turns bitter and stewed. The dry spice mix keeps a month in a jar.",
  []),

R("gulab-jamun", "Gulab Jamun", "Awadhi/Lucknowi",
  "milk-solid dumplings fried slowly and soaked in cardamom syrup",
  6, 25, 40, A, [STOVE, KADHAI], [VEG, NF], ["dairy", "gluten"],
  [("khoya", "250g, grated", None, True),
   ("maida", "50g", None, True),
   ("baking-soda", "1/4 tsp", None, True),
   ("milk", "3 tbsp, for binding", None, True),
   ("sugar", "500g", None, True),
   ("cardamom", "5, crushed", None, True),
   ("rose-water", "1 tsp", None, False),
   ("saffron", "a pinch", None, False),
   ("ghee", "600ml", "for deep frying", True)],
  ["The oil must be barely warm when the jamuns go in and rise slowly over ten minutes. Hot fat browns the outside while the centre stays raw dough.",
   "The syrup should be of one-string consistency and warm, not boiling, when the jamuns go in."],
  [("Make the syrup: 500g sugar to 500ml water with the crushed cardamom, boiled 8 minutes to a slightly sticky, one-string syrup. Keep it warm.",),
   ("Knead the grated khoya with maida and baking soda, adding milk a teaspoon at a time, to a smooth soft dough. Do not overwork it.",
    "Overworked dough gives hard jamuns. Stop as soon as it is smooth."),
   ("Roll into 18 smooth balls with no cracks, rolling between your palms with a little ghee.",
    "Any crack becomes a split in the oil."),
   ("Heat the ghee to only 120C, barely warm, and slide the balls in.",
    "Barely warm. If they sizzle, the ghee is too hot."),
   ("Let them rise on their own and colour slowly over 10 minutes, turning gently, until deep brown all over.",),
   ("Lift out, rest 2 minutes, then drop into the warm syrup.",),
   ("Soak at least 2 hours before serving. They will double in size.",
    "Soaking is not a finishing touch. It is half the cooking.")],
  "Keeps 4 days refrigerated in its syrup and is better on day two. Warm gently before serving. Freezes 2 months in syrup.",
  []),

R("jalebi", "Jalebi", "Punjabi",
  "fermented batter piped into hot ghee in coils and steeped in saffron syrup",
  6, 20, 30, A, [STOVE, KADHAI], [VEG, NF], ["gluten", "dairy"],
  [("maida", "200g", None, True),
   ("besan", "2 tbsp", None, False),
   ("yogurt", "3 tbsp", "starts the ferment", True),
   ("sugar", "400g", None, True),
   ("saffron", "a good pinch", None, True),
   ("cardamom", "4, crushed", None, True),
   ("lemon", "1/2", "keeps the syrup from crystallising", True),
   ("ghee", "600ml", "for deep frying", True),
   ("salt", "a pinch", None, False)],
  ["The batter must ferment. Twelve hours in a warm place gives jalebi its sourness and the bubbles that make it crisp.",
   "Syrup warm, ghee hot, jalebi crisp. Get any of those three wrong and it goes limp."],
  [("Whisk the maida, besan and yogurt with water into a thick, smooth batter, cover, and leave 12 hours in a warm place.",
    "It should smell faintly sour and show bubbles. That is the ferment working."),
   ("Make a one-string syrup with the sugar, 250ml water, saffron, cardamom and lemon juice. Keep it warm, not hot.",),
   ("Whisk the fermented batter hard for a minute to knock it back to a piping consistency.",),
   ("Fill a piping bag or a squeeze bottle and pipe spirals directly into ghee at 180C.",
    "Start at the centre and work outward, two or three turns."),
   ("Fry 1 minute a side until crisp and pale gold, not brown.",),
   ("Lift straight into the warm syrup for 30 seconds only, then out onto a rack.",
    "Thirty seconds. Longer and the jalebi goes soft."),
   ("Serve immediately, ideally with rabri.",)],
  "Best within an hour. Jalebi loses its crispness quickly and cannot be revived. The syrup keeps a week.",
  []),

R("rasmalai", "Rasmalai", "Bengali",
  "flattened chhena discs simmered in syrup then steeped in thickened saffron milk",
  6, 30, 45, A, [STOVE], [VEG], ["dairy", "nuts"],
  [("milk", "2 litres, plus 1 litre for the rabri", None, True),
   ("lemon", "2, juiced", "to split the milk", True),
   ("sugar", "300g", None, True),
   ("cardamom", "5, crushed", None, True),
   ("saffron", "a good pinch", None, True),
   ("pistachios", "3 tbsp, slivered", None, True),
   ("almonds", "2 tbsp, slivered", None, False),
   ("rose-water", "1 tsp", None, False)],
  ["Chhena for rasmalai must be kneaded until it is genuinely smooth and slightly greasy to the touch. Grainy chhena gives grainy discs.",
   "The discs double in the syrup, so leave room in the pan and do not crowd them."],
  [("Bring 2 litres of milk to the boil, take it off the heat, and add lemon juice a little at a time until it splits cleanly.",
    "Stop as soon as the whey runs clear green. Extra acid makes the chhena tough."),
   ("Strain through muslin, rinse under cold water to wash off the lemon, and hang 30 minutes.",),
   ("Knead the chhena on a board for 8 minutes until completely smooth and it leaves a slight film on your palm.",
    "Eight minutes is not an exaggeration. This is the whole dish."),
   ("Shape into 12 balls, flatten each into a disc, and rest 10 minutes.",),
   ("Simmer them in a light syrup of 300g sugar to 1 litre water, covered, for 15 minutes. They will swell.",),
   ("Separately reduce 1 litre of milk by half with saffron, cardamom and sugar to make the rabri.",),
   ("Squeeze the discs gently to remove the syrup and slip them into the warm rabri.",
    "Squeeze gently or they tear. This is what lets them drink the milk."),
   ("Chill 4 hours and serve cold, scattered with pistachios.",)],
  "Keeps 3 days refrigerated and improves overnight as the discs absorb the milk. Does not freeze.",
  []),

R("kulfi", "Kulfi", "Awadhi/Lucknowi",
  "milk reduced by half, spiced with cardamom and frozen dense in moulds",
  6, 10, 60, M, [STOVE], [VEG, GF], ["dairy", "nuts"],
  [("milk", "1.5 litres full fat", None, True),
   ("sugar", "120g", None, True),
   ("cardamom", "6, ground", None, True),
   ("pistachios", "50g, chopped", None, True),
   ("almonds", "30g, chopped", None, False),
   ("saffron", "a pinch", None, False),
   ("khoya", "50g", "shortens the reduction if you have it", False)],
  ["Kulfi is not ice cream. It is not churned, so the density comes entirely from reducing the milk hard before freezing.",
   "Scrape the skin back into the milk as it reduces. Those solids are what give kulfi its texture."],
  [("Bring the milk to the boil in a wide, heavy pan and keep it at a steady simmer.",
    "Wide pan. Reduction is about surface area, not time."),
   ("Reduce by half over 45 minutes, stirring often and scraping the sides back in.",
    "Push the cream that forms on the sides back into the pan as you go."),
   ("Add the sugar, khoya if using, cardamom and saffron, and cook 10 minutes more until it coats a spoon thickly.",),
   ("Stir in most of the nuts and cool to room temperature.",),
   ("Pour into kulfi moulds or small cups, cover, and freeze at least 6 hours.",
    "Cover tightly. Uncovered kulfi takes up freezer smells."),
   ("To unmould, dip briefly in warm water. Serve with the remaining nuts on top.",)],
  "Keeps a month frozen, tightly covered. Once softened it should not be refrozen; the texture goes icy.",
  []),

R("plain-dosa", "Plain Dosa", "Tamil Nadu",
  "fermented rice and urad batter spread paper thin and crisped on a griddle",
  4, 20, 30, M, [TAWA, BLEND, STOVE], [VEG, VGN, GF, DF, NF, NOG], [],
  [("rice", "300g parboiled or short-grain", None, True),
   ("urad-dal", "100g, skinned", None, True),
   ("fenugreek-seeds", "1 tsp", "helps the ferment and the colour", True),
   ("poha", "2 tbsp", "gives crispness", False),
   ("neutral-oil", "4 tbsp, for the griddle", None, True),
   ("salt", "to taste", None, True)],
  ["The batter ferments for 8 to 12 hours in a warm place. That is the whole recipe; everything else is technique.",
   "Grind the urad dal separately and until genuinely fluffy. It is what makes the batter rise."],
  [("Rinse and soak the rice with the fenugreek, and the urad dal separately, for 5 hours.",),
   ("Grind the urad dal first with cold water to a light, fluffy paste, then the rice with the poha to a slightly grainy one.",
    "Cold water. Heat from the grinder kills the ferment before it starts."),
   ("Combine the two by hand, add salt, and leave 8 to 12 hours in a warm place until risen and faintly sour.",
    "By hand. The warmth of your hands helps it along, which is not superstition."),
   ("Stir the batter down and thin it with water to the consistency of pouring cream.",),
   ("Heat a tawa until a flick of water skitters. Rub with a halved onion dipped in oil.",
    "The onion seasons the surface and stops the first dosa sticking."),
   ("Pour a ladle at the centre and spread outward in a spiral, quickly and lightly, to a thin round.",),
   ("Drizzle oil round the edge and cook 2 minutes until the underside is gold and the edges lift. Do not flip a plain dosa.",
    "No flip. It cooks through from one side."),
   ("Fold and serve at once with sambar and coconut chutney.",)],
  "The batter keeps 4 days refrigerated and sours further, which suits dosa. Cooked dosa must be eaten immediately.",
  []),
]
