"""Core pan-Indian dishes the collection was missing: restaurant standards,
the foundational breads, and the biryanis people search by generic name."""
from add_recipes import R

E, M, A = "easy", "moderate", "advanced"
STOVE, PC, STEAM, BLEND, OVEN, KADHAI, TAWA = (
    "stovetop", "pressure-cooker", "steamer", "blender", "oven", "kadhai", "tawa")
VEG, VGN, GF, DF, NF, NOG = (
    "vegetarian", "vegan", "gluten-free", "dairy-free", "nut-free", "no-onion-garlic")

BATCH = [

R("paneer-butter-masala", "Paneer Butter Masala", "Punjabi",
  "paneer in a glossy tomato and cashew gravy, sweet with butter and finished with cream",
  4, 20, 35, E, [STOVE, KADHAI, BLEND], [VEG, GF], ["dairy", "nuts"],
  [("paneer", "400g, cut into 2cm cubes", None, True),
   ("tomato", "700g, roughly chopped", "ripe and red; pale tomatoes give a dull gravy", True),
   ("cashew", "60g, soaked 20 minutes in hot water", "the body of the sauce, not a garnish", True),
   ("butter", "60g", None, True),
   ("cream", "60ml", None, True),
   ("onion", "1, quartered", None, True),
   ("ginger", "1 tbsp, roughly chopped", None, True),
   ("garlic", "6 cloves", None, True),
   ("kashmiri-chilli", "2 tsp", "for colour without much heat", True),
   ("garam-masala", "1 tsp", None, True),
   ("kasuri-methi", "1 tbsp, crushed between the palms", "the flavour people cannot place", True),
   ("sugar", "1 tsp", "balances the tomato, it should not taste sweet", True),
   ("cardamom", "3", None, False),
   ("salt", "to taste", None, True)],
  ["The gravy is boiled and blended, not fried in the usual bhuna way. That is what keeps it smooth and bright rather than dark.",
   "Soak the cashews properly. Under-soaked nuts leave a grainy sauce that no amount of blending fixes."],
  [("Simmer the tomato, onion, ginger, garlic, cardamom and soaked cashews with 200ml water for 20 minutes, until everything collapses.",
    "No oil at this stage. It is a stock, not a fry."),
   ("Cool slightly, blend to a completely smooth puree, then pass it through a sieve. The sieve is what separates this from a home-style curry.",),
   ("Melt the butter in the pan, add the kashmiri chilli off the heat so it blooms without burning, then pour the puree back in.",
    "Off the heat for the chilli: it scorches in seconds and turns bitter."),
   ("Simmer 10 minutes until it thickens and the butter shows at the edges. Season with salt and the sugar.",),
   ("Stir in the paneer and cook 4 minutes, no longer. Add the garam masala, crushed kasuri methi and cream.",
    "Long cooking makes paneer rubbery. It only needs to warm through."),
   ("Rest 5 minutes off the heat before serving with naan or jeera rice.",)],
  "Keeps 2 days refrigerated. The sauce thickens as it stands, so loosen with a splash of milk or water and reheat gently. Freezing splits the cream.",
  []),

R("chicken-tikka", "Chicken Tikka", "Punjabi",
  "yogurt and spice marinated chicken, charred at the edges and still juicy inside",
  4, 30, 20, E, [OVEN, TAWA], [GF, NF], ["dairy"],
  [("chicken", "700g boneless thigh, cut into 4cm pieces", "thigh, not breast: it survives the heat", True),
   ("yogurt", "200g, thick and hung 30 minutes", "watery yogurt slides off the meat", True),
   ("ginger", "1 tbsp paste", None, True),
   ("garlic", "1 tbsp paste", None, True),
   ("kashmiri-chilli", "2 tsp", None, True),
   ("chilli-powder", "1/2 tsp", None, False),
   ("turmeric", "1/2 tsp", None, True),
   ("garam-masala", "1 tsp", None, True),
   ("cumin-powder", "1 tsp", None, True),
   ("coriander-powder", "1 tsp", None, True),
   ("kasuri-methi", "1 tsp, crushed", None, True),
   ("lemon", "1", None, True),
   ("mustard-oil", "2 tbsp, heated to smoking and cooled", "the smoke point kills its raw pungency", True),
   ("chaat-masala", "1 tsp, to finish", None, False),
   ("salt", "to taste", None, True)],
  ["Marinate twice. A short salt and lemon rub first, then the yogurt marinade, gives seasoning through the meat rather than only on the surface.",
   "Hang the yogurt in a cloth for 30 minutes. This is the single change that stops the marinade sliding off in the oven."],
  [("Rub the chicken with lemon juice, salt and half the chilli powder. Rest 20 minutes.",),
   ("Whisk the hung yogurt with the ginger, garlic, remaining spices, kasuri methi and the cooled mustard oil until smooth.",),
   ("Fold the chicken through and refrigerate at least 4 hours, better overnight.",
    "Longer than 12 hours and the yogurt starts to break the meat down."),
   ("Thread onto skewers, leaving a small gap between pieces so the heat gets round them.",
    "Crowded skewers steam instead of charring."),
   ("Cook at the highest heat your oven allows, around 240C, for 12 minutes. Turn once, baste with the leftover marinade and give it 5 minutes more.",),
   ("Finish under a grill or over a direct flame for 2 minutes to get the char, then dust with chaat masala and squeeze over lemon.",
    "The char is the point. Without it this is just baked chicken.")],
  "Best within the hour. Cooked tikka keeps 2 days refrigerated and reheats acceptably in a hot pan, not a microwave. The raw marinated chicken freezes well for a month.",
  []),

R("chicken-tikka-masala", "Chicken Tikka Masala", "Punjabi",
  "grilled chicken tikka finished in a creamy spiced tomato gravy",
  4, 30, 40, M, [STOVE, OVEN, KADHAI, BLEND], [GF, NF], ["dairy"],
  [("chicken", "700g boneless thigh, cut into 4cm pieces", None, True),
   ("yogurt", "150g, thick", None, True),
   ("tomato", "600g, chopped", None, True),
   ("onion", "2, finely sliced", None, True),
   ("cream", "80ml", None, True),
   ("butter", "40g", None, True),
   ("ginger", "1 tbsp paste", None, True),
   ("garlic", "1 tbsp paste", None, True),
   ("kashmiri-chilli", "2 tsp", None, True),
   ("garam-masala", "1.5 tsp", None, True),
   ("cumin-powder", "1 tsp", None, True),
   ("coriander-powder", "1 tsp", None, True),
   ("turmeric", "1/2 tsp", None, True),
   ("kasuri-methi", "1 tbsp, crushed", None, True),
   ("coriander-leaves", "a handful, chopped", None, False),
   ("neutral-oil", "3 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["The chicken is cooked separately and hard, then added to the gravy at the end. Simmering raw chicken in the sauce gives a different, flatter dish.",
   "The dish is British-Indian in origin and there is no single authentic version. What is consistent is charred tikka meeting a tomato-cream gravy."],
  [("Marinate the chicken in yogurt, half the ginger and garlic, the kashmiri chilli, turmeric and salt for at least 2 hours.",),
   ("Grill or roast it at 240C for 15 minutes until the edges catch. Set aside with any juices.",
    "Take the colour seriously here. It is the only smoke the dish gets."),
   ("Fry the onion in oil over medium heat for 12 minutes until properly brown, not merely soft.",
    "This is where the sweetness comes from. Rushing it leaves the gravy thin."),
   ("Add the remaining ginger and garlic, then the ground spices, and cook 1 minute.",),
   ("Add the tomato and a splash of water, cover and cook 15 minutes until it collapses. Blend smooth and return to the pan.",),
   ("Simmer with the butter until the fat separates, then add the chicken with its juices and cook 5 minutes.",),
   ("Stir in the cream, garam masala and crushed kasuri methi. Rest off the heat 5 minutes, then scatter the coriander.",)],
  "Keeps 3 days refrigerated and is better on day two. Reheat gently. Freeze without the cream and add it on reheating.",
  ["bhuna"]),

R("kadai-paneer", "Kadai Paneer", "Punjabi",
  "paneer and peppers in a coarse, freshly pounded coriander and chilli masala",
  4, 15, 25, E, [STOVE, KADHAI], [VEG, GF, NF], ["dairy"],
  [("paneer", "350g, cut into thick fingers", None, True),
   ("capsicum", "2, cut into 3cm squares", None, True),
   ("onion", "2, cut into petals", None, True),
   ("tomato", "400g, chopped", None, True),
   ("coriander-powder", "2 tbsp, coarsely pounded", "coarse, not fine: kadai masala has texture", True),
   ("dried-red-chilli", "4, pounded with the coriander", None, True),
   ("ginger", "1 tbsp, julienned", None, True),
   ("garlic", "1 tbsp, chopped", None, True),
   ("kasuri-methi", "1 tbsp, crushed", None, True),
   ("garam-masala", "1/2 tsp", None, False),
   ("cream", "2 tbsp", None, False),
   ("neutral-oil", "3 tbsp", None, True),
   ("coriander-leaves", "a handful", None, False),
   ("salt", "to taste", None, True)],
  ["Kadai masala is pounded, not powdered. Whole coriander seed and dried chilli crushed together in a mortar is the whole character of the dish.",
   "Everything stays in large pieces. This is not a smooth gravy."],
  [("Dry-roast the coriander seed and dried chillies until they smell nutty, cool, then pound coarsely.",
    "Coarse means you can still see the pieces."),
   ("Fry the onion petals and capsicum in hot oil for 3 minutes on high, so they take colour but stay crisp. Lift out and reserve.",),
   ("In the same pan cook the garlic and half the ginger, add the tomato and half the pounded masala, and cook 10 minutes until the oil separates.",),
   ("Return the vegetables, add the paneer and the rest of the masala, and toss 3 minutes over high heat.",
    "Toss rather than stir. The pieces should stay whole."),
   ("Finish with crushed kasuri methi, garam masala, the remaining ginger julienne and the cream if using.",),
   ("Scatter coriander and serve straight from the kadai with roti.",)],
  "Best fresh: the peppers soften and lose their point overnight. Keeps 2 days refrigerated.",
  ["kadhai"]),

R("malai-kofta", "Malai Kofta", "Punjabi",
  "fried paneer and potato dumplings in a pale, sweet cashew gravy",
  4, 35, 35, A, [STOVE, KADHAI, BLEND], [VEG], ["dairy", "gluten", "nuts"],
  [("paneer", "250g, grated", None, True),
   ("potato", "300g, boiled, cooled and grated", "cooled and dry, or the koftas burst", True),
   ("cornflour", "3 tbsp", None, True),
   ("maida", "1 tbsp", None, True),
   ("cashew", "50g, soaked", None, True),
   ("raisins", "2 tbsp", None, False),
   ("onion", "2, quartered", None, True),
   ("tomato", "300g", None, True),
   ("cream", "80ml", None, True),
   ("milk", "150ml", None, True),
   ("ginger", "1 tbsp", None, True),
   ("garlic", "4 cloves", None, False),
   ("cardamom", "4", None, True),
   ("garam-masala", "1 tsp", None, True),
   ("sugar", "1 tsp", None, True),
   ("neutral-oil", "500ml", "for deep frying", True),
   ("salt", "to taste", None, True)],
  ["The potato must be boiled ahead and completely cold. Warm potato holds water and the koftas fall apart in the oil.",
   "Fry one kofta first as a test. If it breaks, work in another spoon of cornflour before frying the rest."],
  [("Mix the grated paneer and potato with the cornflour, maida and salt into a smooth, firm dough. Do not knead hard.",),
   ("Shape into 12 balls, pressing a few raisins and a piece of cashew into the centre of each.",),
   ("Heat the oil to 170C and fry the koftas in batches until pale gold, 3 minutes. Drain on paper.",
    "Pale gold, not brown. They fry again in the mouth of the gravy."),
   ("For the gravy, simmer the onion, tomato, ginger, garlic, cardamom and soaked cashews in 200ml water for 15 minutes, then blend and sieve.",),
   ("Cook the puree in 2 tbsp of the frying oil for 8 minutes, add the milk, sugar and salt, and simmer to a pouring consistency.",),
   ("Stir in the cream and garam masala off the heat.",),
   ("Put the koftas in the serving dish and pour the hot gravy over them at the table.",
    "Never simmer the koftas in the gravy. They dissolve.")],
  "The koftas and gravy keep 2 days refrigerated but must be stored apart. Reheat the gravy and pour it over koftas warmed briefly in the oven.",
  []),

R("egg-curry", "Egg Curry", "Punjabi",
  "boiled eggs in an onion-tomato gravy, the fastest curry in the repertoire",
  4, 10, 30, E, [STOVE, KADHAI], [GF, NF, DF], [],
  [("eggs", "8, hard-boiled and peeled", None, True),
   ("onion", "3, finely chopped", None, True),
   ("tomato", "400g, chopped", None, True),
   ("ginger", "1 tbsp paste", None, True),
   ("garlic", "1 tbsp paste", None, True),
   ("turmeric", "1 tsp", None, True),
   ("chilli-powder", "1.5 tsp", None, True),
   ("coriander-powder", "2 tsp", None, True),
   ("cumin-seeds", "1 tsp", None, True),
   ("garam-masala", "1 tsp", None, True),
   ("coriander-leaves", "a handful", None, False),
   ("mustard-oil", "3 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["Prick or lightly score the boiled eggs before they go in. Whole smooth eggs sit in the gravy without taking any of it up.",
   "Frying the eggs briefly in turmeric and salt before adding them gives a skin that holds the masala."],
  [("Halve or score the peeled eggs. Toss them in a little turmeric and salt.",),
   ("Fry the eggs in hot mustard oil for 2 minutes until blistered and golden. Lift out.",
    "Stand back, they spit."),
   ("In the same oil crackle the cumin, then fry the onion for 10 minutes until deep brown.",),
   ("Add ginger and garlic, cook a minute, then the ground spices with a splash of water so they do not burn.",),
   ("Add the tomato and cook 10 minutes until the oil separates from the masala.",),
   ("Pour in 300ml hot water, season, and simmer 5 minutes. Return the eggs and cook 5 minutes more.",),
   ("Finish with garam masala and coriander.",)],
  "Keeps 2 days refrigerated. The eggs firm up as they sit; the gravy improves. Do not freeze, boiled egg whites turn rubbery.",
  ["bhuna"]),

R("egg-bhurji", "Egg Bhurji", "Punjabi",
  "eggs scrambled hard with onion, chilli and tomato, the ten-minute dinner",
  2, 5, 12, E, [STOVE, KADHAI], [GF, NF, DF], [],
  [("eggs", "5", None, True),
   ("onion", "1, finely chopped", None, True),
   ("tomato", "1, finely chopped", None, True),
   ("green-chilli", "2, finely chopped", None, True),
   ("ginger", "1 tsp, grated", None, False),
   ("turmeric", "1/4 tsp", None, True),
   ("chilli-powder", "1/2 tsp", None, False),
   ("cumin-seeds", "1/2 tsp", None, True),
   ("coriander-leaves", "a handful", None, False),
   ("neutral-oil", "2 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["Bhurji is deliberately dry and crumbly, not soft and creamy. Cook the eggs harder than you would for a Western scramble.",
   "Salt the eggs only as they go in. Salted early, they weep."],
  [("Crackle the cumin in hot oil, then fry the onion 4 minutes until soft and just colouring.",),
   ("Add the green chilli and ginger, then the tomato, and cook 3 minutes until it breaks down.",),
   ("Add the turmeric and chilli powder and cook 30 seconds.",),
   ("Break the eggs straight into the pan, season, and stir constantly over medium heat.",
    "Straight into the pan, not beaten first: it gives the loose curds bhurji wants."),
   ("Keep going 3 minutes until the eggs are dry and crumbly with no wet patches.",),
   ("Scatter coriander and eat immediately with pav or roti.",)],
  "Eat straight away. Bhurji reheats badly and turns watery in the fridge.",
  []),

R("jeera-rice", "Jeera Rice", "Punjabi",
  "basmati tossed with cumin in ghee, the rice that goes with everything",
  4, 5, 20, E, [STOVE], [VEG, GF, NF, NOG], ["dairy"],
  [("basmati-rice", "300g, rinsed and soaked 20 minutes", None, True),
   ("cumin-seeds", "2 tsp", None, True),
   ("ghee", "3 tbsp", None, True),
   ("bay-leaf", "1", None, False),
   ("cinnamon", "1 small piece", None, False),
   ("cloves", "3", None, False),
   ("coriander-leaves", "a little, chopped", None, False),
   ("salt", "to taste", None, True)],
  ["Soaking is not optional for basmati. Twenty minutes lets the grain absorb water evenly so it lengthens instead of breaking.",
   "Drain the soaked rice properly. Wet rice going into hot ghee spits and steams."],
  [("Rinse the rice until the water runs clear, then soak 20 minutes and drain well.",),
   ("Heat the ghee, add the whole spices and let the cumin darken by a shade and smell toasted.",
    "A shade darker, no more. Burnt cumin is bitter and cannot be rescued."),
   ("Add the drained rice and turn it gently in the ghee for 2 minutes until every grain is coated.",),
   ("Pour in 540ml hot water, add salt, and bring to a hard boil.",
    "Hot water, not cold. Cold water stalls the pan and the grains cook unevenly."),
   ("Cover, drop to the lowest heat and cook 12 minutes without lifting the lid.",),
   ("Rest 10 minutes off the heat, then fork through with the coriander.",
    "The rest is when the grains firm up. Forking too early breaks them.")],
  "Keeps 2 days refrigerated. Reheat with a sprinkle of water under a lid, or fry in a little ghee. Cool leftover rice quickly and refrigerate within the hour.",
  []),

R("naan", "Naan", "Punjabi",
  "soft leavened flatbread, blistered on top and chewy underneath",
  6, 20, 20, M, [OVEN, TAWA], [VEG, NF], ["gluten", "dairy"],
  [("maida", "400g", "plain flour, not bread flour: naan should be soft, not chewy", True),
   ("yogurt", "120g", None, True),
   ("milk", "150ml, warm", None, True),
   ("baking-soda", "1/2 tsp", None, True),
   ("eno", "1 tsp", "or 1 tsp baking powder", False),
   ("sugar", "1 tsp", None, True),
   ("ghee", "3 tbsp, for brushing", None, True),
   ("nigella", "1 tsp", None, False),
   ("salt", "1 tsp", None, True)],
  ["Naan needs a very hot surface and a soft, slack dough. Both matter more than the exact flour.",
   "The dough should be softer than you think is sensible, close to sticky. A stiff dough gives a biscuit."],
  [("Mix the flour, salt, sugar, baking soda and eno. Work in the yogurt and enough warm milk to make a soft, slightly sticky dough.",),
   ("Knead 8 minutes until smooth, oil the surface, cover and rest 2 hours in a warm place.",
    "The rest does the work here, not the kneading."),
   ("Heat a tawa until a drop of water skitters across it, or the oven with a tray inside at maximum.",),
   ("Divide into 6, roll each into a teardrop about 5mm thick, and scatter nigella on top.",),
   ("Wet the underside with a little water and slap it onto the hot tawa, wet side down. It will stick.",
    "The water is what makes it grip the surface, exactly like a tandoor wall. Do not skip it."),
   ("When bubbles rise and the top sets, invert the pan over a flame to blister the top, 30 seconds.",),
   ("Brush with ghee and stack under a cloth so they stay soft.",)],
  "Best within the hour. They keep a day wrapped in a cloth, and reheat well sprinkled with water in a hot pan. Freeze cooked with baking paper between them.",
  ["resting-dough"]),

R("garlic-naan", "Garlic Naan", "Punjabi",
  "naan pressed with raw garlic and coriander before it hits the heat",
  6, 20, 20, M, [OVEN, TAWA], [VEG, NF], ["gluten", "dairy"],
  [("maida", "400g", None, True),
   ("yogurt", "120g", None, True),
   ("milk", "150ml, warm", None, True),
   ("garlic", "8 cloves, very finely chopped", "chopped, not crushed: crushed garlic burns", True),
   ("coriander-leaves", "a large handful, chopped", None, True),
   ("baking-soda", "1/2 tsp", None, True),
   ("eno", "1 tsp", None, False),
   ("sugar", "1 tsp", None, True),
   ("ghee", "3 tbsp, for brushing", None, True),
   ("salt", "1 tsp", None, True)],
  ["The garlic goes on raw and is pressed into the rolled dough, so it cooks in contact with the bread rather than in the pan.",
   "Chop the garlic rather than crushing it. Crushed garlic weeps and scorches on the tawa."],
  [("Make the naan dough: flour, salt, sugar, baking soda and eno, brought together with yogurt and warm milk into a soft, slightly sticky dough.",),
   ("Knead 8 minutes, oil, cover and rest 2 hours.",),
   ("Divide into 6 and roll each into a teardrop about 5mm thick.",),
   ("Scatter the chopped garlic and coriander over the top and roll once more, lightly, to press them in.",
    "Press them in or they fall off in the pan and burn on the metal."),
   ("Wet the plain underside, slap onto a screaming-hot tawa, and cook until bubbles rise.",),
   ("Invert over a flame to blister the garlic side, 30 seconds, watching that the garlic colours but does not blacken.",),
   ("Brush generously with ghee and serve at once.",)],
  "Best straight off the heat. Keeps a day wrapped in a cloth; the garlic dulls quickly, so these are worth making to order.",
  ["resting-dough"]),

R("chapati", "Chapati / Phulka", "Punjabi",
  "everyday wholewheat flatbread that puffs into a ball over the flame",
  4, 20, 20, M, [TAWA, STOVE], [VEG, VGN, DF, NF, NOG], ["gluten"],
  [("atta", "300g", None, True),
   ("water", "about 200ml, warm", None, True),
   ("ghee", "for brushing", "omit to keep it vegan and dairy-free; a phulka is dry anyway", False),
   ("salt", "1/2 tsp", None, False)],
  ["Four ingredients and no margin for error: the whole dish is dough hydration and heat.",
   "The dough should be soft enough to take a fingerprint without resistance. Most home chapatis fail because the dough is too stiff."],
  [("Mix the atta and salt, then add warm water a little at a time, bringing it together into a soft dough.",
    "Soft. If it feels firm, it is already too dry."),
   ("Knead 8 minutes until smooth and springy, then cover and rest 30 minutes.",
    "Resting relaxes the gluten. Skip it and the rounds fight back as you roll."),
   ("Divide into 8, roll each into a 16cm round of even thickness, dusting sparingly.",
    "Even thickness matters more than a perfect circle. A thin patch stops the puff."),
   ("Cook on a hot tawa 30 seconds, until small bubbles appear, then flip.",),
   ("After another 30 seconds, lift it onto a direct flame with tongs. It should balloon in a few seconds.",
    "If it will not puff, the tawa was not hot enough or the round has a thin spot."),
   ("Brush with ghee if you want a chapati, leave it dry for a phulka, and stack under a cloth.",)],
  "Best hot. They keep a few hours under a cloth and go leathery in the fridge. Dough keeps 24 hours refrigerated and rolls better cold.",
  ["resting-dough"]),

R("chole-bhature", "Chole Bhature", "Punjabi",
  "dark spiced chickpeas with a puffed, fried bread the size of a plate",
  4, 30, 60, A, [STOVE, PC, KADHAI], [VEG], ["gluten", "dairy"],
  [("chickpeas", "250g dried, soaked overnight", None, True),
   ("maida", "300g", "for the bhature", True),
   ("rava", "3 tbsp", "gives the bhatura its crisp edge", True),
   ("yogurt", "100g", None, True),
   ("onion", "2, finely chopped", None, True),
   ("tomato", "300g, pureed", None, True),
   ("ginger", "1 tbsp paste", None, True),
   ("garlic", "1 tbsp paste", None, True),
   ("chaat-masala", "1 tsp", None, True),
   ("amchur", "1 tsp", None, True),
   ("garam-masala", "1.5 tsp", None, True),
   ("coriander-powder", "2 tsp", None, True),
   ("chilli-powder", "1.5 tsp", None, True),
   ("black-salt", "1/2 tsp", None, False),
   ("bay-leaf", "2", None, False),
   ("black-cardamom", "1", "the smoke behind the colour", False),
   ("neutral-oil", "600ml", "for deep frying", True),
   ("salt", "to taste", None, True)],
  ["The colour is not from chilli. Traditionally the chickpeas are boiled with a tea bag or amla; here the black cardamom and long bhuna do the work.",
   "Bhatura dough needs a warm 2-hour rest. Under-rested dough does not puff, it fries flat and hard."],
  [("Make the bhatura dough first: maida, rava, yogurt, a pinch of salt and enough warm water for a soft dough. Knead 10 minutes, cover, rest 2 hours in a warm place.",),
   ("Pressure cook the soaked chickpeas with the bay leaf, black cardamom and salt for 6 whistles, until they crush easily between finger and thumb.",
    "Undercooked chana never softens later in the masala."),
   ("Fry the onion in 4 tbsp of oil for 12 minutes until dark brown, then add ginger and garlic.",),
   ("Add the ground spices and the tomato puree, and cook 12 minutes until the oil separates and the masala darkens.",),
   ("Add the chickpeas with a cup of their cooking liquid, crush a spoonful against the side of the pan to thicken, and simmer 15 minutes.",
    "Crushing a few is what gives the gravy body without any flour."),
   ("Finish with amchur, chaat masala, black salt and garam masala.",),
   ("Roll the rested dough into ovals 4mm thick and slide into oil at 190C. Press gently with a slotted spoon and it will balloon; turn once and lift when pale gold.",
    "The oil must be properly hot. Cool oil gives a heavy, greasy bread."),
   ("Serve immediately with sliced onion and a green chilli.",)],
  "The chole keep 3 days refrigerated and are better the next day. Bhature must be eaten within minutes of frying; the dough keeps 24 hours refrigerated.",
  ["bhuna", "resting-dough"]),

R("samosa", "Samosa", "Punjabi",
  "crisp pastry triangles with a spiced potato and pea filling",
  6, 40, 30, A, [STOVE, KADHAI], [VEG, VGN, DF, NF], ["gluten"],
  [("maida", "300g", None, True),
   ("ajwain", "1 tsp", "the flavour that says samosa", True),
   ("potato", "500g, boiled and roughly crushed", "crushed, not mashed", True),
   ("peas", "150g", None, True),
   ("green-chilli", "2, chopped", None, True),
   ("ginger", "1 tbsp, grated", None, True),
   ("cumin-seeds", "1 tsp", None, True),
   ("coriander-powder", "2 tsp, coarsely crushed", None, True),
   ("amchur", "1.5 tsp", None, True),
   ("garam-masala", "1 tsp", None, True),
   ("fennel-seeds", "1 tsp, crushed", None, False),
   ("coriander-leaves", "a handful", None, False),
   ("neutral-oil", "600ml", "for deep frying", True),
   ("salt", "to taste", None, True)],
  ["The pastry is short, not soft: rub plenty of oil into the flour until it holds a shape when squeezed. That is what makes it crisp rather than chewy.",
   "Fry low and slow. Samosas dropped into hot oil blister and go soft within minutes."],
  [("Rub 6 tbsp of the oil and the ajwain into the maida until the mixture holds together when pressed in your fist.",
    "This test matters. Too little fat and the crust will be tough."),
   ("Add cold water sparingly to make a stiff dough. Knead only until smooth, then rest 30 minutes covered.",
    "Stiff, not soft. A soft dough gives bubbles and a wavy shell."),
   ("For the filling, crackle cumin in 2 tbsp oil, add ginger and chilli, then the peas and a splash of water, and cook until tender.",),
   ("Add the crushed potato, coriander powder, amchur, garam masala, fennel and salt. Cook 4 minutes and cool completely.",
    "Warm filling makes the pastry damp and it splits in the oil."),
   ("Roll a ball of dough into an oval, cut it in half, form a cone from each, fill, and seal the edge with a wet finger, pressing firmly.",
    "Any gap and the samosa drinks oil."),
   ("Rest the shaped samosas 15 minutes uncovered so the surface dries.",),
   ("Fry at 140C, low, for 10 minutes until pale and blistering slowly, then raise to 180C for 3 minutes to colour.",
    "The low first fry sets the layers. Straight into hot oil gives a bubbled, greasy shell."),
   ("Drain and serve with tamarind and mint chutneys.",)],
  "Best within a few hours. Fried samosas keep a day and revive in a hot oven, never a microwave. Shaped uncooked samosas freeze for a month and fry from frozen.",
  ["resting-dough"]),

R("veg-biryani", "Vegetable Biryani", "Hyderabadi",
  "layered rice and mixed vegetables sealed and steamed, the meatless dum biryani",
  6, 30, 45, M, [STOVE, KADHAI], [VEG, NF], ["dairy"],
  [("basmati-rice", "450g, soaked 30 minutes", None, True),
   ("cauliflower", "200g, in florets", None, True),
   ("carrot", "150g, in batons", None, True),
   ("peas", "100g", None, True),
   ("french-beans", "100g, cut into 3cm", None, True),
   ("potato", "200g, quartered", None, True),
   ("yogurt", "200g, whisked", None, True),
   ("onion", "3, finely sliced and fried brown", None, True),
   ("ginger", "1 tbsp paste", None, True),
   ("garlic", "1 tbsp paste", None, True),
   ("mint", "a large handful", None, True),
   ("coriander-leaves", "a large handful", None, True),
   ("garam-masala", "1.5 tsp", None, True),
   ("chilli-powder", "1.5 tsp", None, True),
   ("turmeric", "1/2 tsp", None, True),
   ("saffron", "a pinch in 3 tbsp warm milk", None, True),
   ("cardamom", "5", None, True),
   ("cinnamon", "1 piece", None, True),
   ("cloves", "4", None, True),
   ("bay-leaf", "2", None, False),
   ("ghee", "4 tbsp", None, True),
   ("lemon", "1", None, True),
   ("salt", "to taste", None, True)],
  ["Vegetables release water in a way meat does not, so they are fried hard first. Raw vegetables layered under rice make it soggy.",
   "Cook the rice to 70 per cent only. It finishes in the steam of the sealed pot."],
  [("Fry the sliced onion in ghee until deep brown and crisp. Drain and reserve; this birista carries the sweetness of the dish.",
    "Pull them out a shade lighter than you want, they darken as they cool."),
   ("Fry the potato, cauliflower, carrot and beans in the same ghee over high heat until the edges colour. Do not cook them through.",),
   ("Fold the vegetables into the whisked yogurt with ginger, garlic, chilli, turmeric, half the herbs, half the birista and salt. Rest 20 minutes.",),
   ("Boil the rice in heavily salted water with the whole spices until 70 per cent done, about 5 minutes, then drain at once.",
    "Test by crushing a grain: it should still have a hard white core."),
   ("Spread the vegetable mixture in a heavy pot, layer the rice over it, and top with the remaining birista, herbs, saffron milk, lemon juice and ghee.",),
   ("Seal with a tight lid or foil. Cook 5 minutes on high to build steam, then 25 minutes on the lowest heat.",),
   ("Rest 15 minutes before opening. Lift from the bottom to serve so every plate gets both layers.",)],
  "Keeps 2 days refrigerated. Reheat covered with a sprinkle of water; the microwave dries the top layer. Do not freeze, the vegetables collapse.",
  ["dum"]),

R("chicken-biryani", "Chicken Biryani", "Hyderabadi",
  "marinated chicken layered under part-cooked rice and sealed for the dum",
  6, 30, 50, M, [STOVE, KADHAI], [GF, NF], ["dairy"],
  [("chicken", "1kg bone-in pieces", "on the bone: it holds together and gives the rice flavour", True),
   ("basmati-rice", "500g, soaked 30 minutes", None, True),
   ("yogurt", "250g, whisked", None, True),
   ("onion", "4, finely sliced and fried brown", None, True),
   ("ginger", "2 tbsp paste", None, True),
   ("garlic", "2 tbsp paste", None, True),
   ("green-chilli", "4, slit", None, True),
   ("mint", "a large handful", None, True),
   ("coriander-leaves", "a large handful", None, True),
   ("chilli-powder", "2 tsp", None, True),
   ("turmeric", "1 tsp", None, True),
   ("garam-masala", "1.5 tsp", None, True),
   ("saffron", "a pinch in 4 tbsp warm milk", None, True),
   ("cardamom", "6", None, True),
   ("cinnamon", "2 pieces", None, True),
   ("cloves", "5", None, True),
   ("bay-leaf", "2", None, False),
   ("ghee", "5 tbsp", None, True),
   ("lemon", "1", None, True),
   ("salt", "to taste", None, True)],
  ["Marinate for at least 4 hours. The yogurt needs time to work into bone-in chicken, and this is the difference between a biryani and rice with chicken in it.",
   "Weigh the rice and the water. Biryani is unforgiving of guesswork."],
  [("Fry the onions slowly in ghee until deep brown and crisp. Drain and reserve.",),
   ("Marinate the chicken with yogurt, ginger, garlic, chilli powder, turmeric, garam masala, half the birista, half the herbs, lemon juice and salt. Refrigerate 4 hours.",),
   ("Bring the chicken to room temperature and spread it in a heavy pot with 3 tbsp ghee and the slit chillies.",),
   ("Boil the rice in well-salted water with the whole spices until 70 per cent done, then drain immediately.",
    "Drain the second it is ready. Thirty seconds too long and the finished biryani is mush."),
   ("Layer the rice over the raw chicken and top with the remaining birista, herbs, saffron milk and ghee.",),
   ("Seal the pot with a tight lid or foil. Cook 6 minutes on high, then 35 minutes on the lowest heat.",),
   ("Rest 15 minutes before opening, then lift from the bottom so each plate gets rice and chicken.",
    "The rest lets the steam settle. Opening early releases it and the top layer dries.")],
  "Keeps 2 days refrigerated. Reheat covered with a splash of water. Biryani freezes poorly: the rice turns to paste.",
  ["dum"]),

R("kolkata-biryani", "Kolkata Biryani", "Bengali",
  "pale, lightly spiced biryani with a whole potato and a boiled egg",
  6, 30, 50, M, [STOVE, KADHAI], [GF, NF], ["dairy"],
  [("mutton", "800g, on the bone", None, True),
   ("basmati-rice", "500g, soaked 30 minutes", None, True),
   ("potato", "6 medium, peeled and left whole", "the potato is not a filler here, it is the point", True),
   ("eggs", "6, hard-boiled", None, False),
   ("yogurt", "200g", None, True),
   ("onion", "3, fried brown", None, True),
   ("ginger", "2 tbsp paste", None, True),
   ("garlic", "1 tbsp paste", None, True),
   ("cardamom", "6", None, True),
   ("cinnamon", "2 pieces", None, True),
   ("cloves", "6", None, True),
   ("mace", "1/2 tsp", None, True),
   ("nutmeg", "a scraping", None, True),
   ("kewra-water", "1 tsp", "the perfume that marks a Kolkata biryani", True),
   ("saffron", "a pinch in warm milk", None, True),
   ("turmeric", "1/2 tsp", "for the potatoes", True),
   ("ghee", "5 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["This is the quiet biryani. Very little chilli, no tomato, and the spicing leans on mace, nutmeg and kewra rather than heat.",
   "The potato is fried in turmeric first so it takes colour and holds its shape through the dum."],
  [("Rub the whole potatoes with turmeric and salt and fry in ghee until golden all over. Set aside.",),
   ("Fry the onions brown, drain, and reserve.",),
   ("Marinate the mutton in yogurt, ginger, garlic, mace, nutmeg, half the birista and salt for 4 hours.",),
   ("Cook the marinated mutton gently, covered, for 40 minutes until nearly tender, then add the fried potatoes.",
    "Unlike Hyderabadi kachchi, the meat here is cooked before layering."),
   ("Boil the rice with the whole spices until 70 per cent done and drain.",),
   ("Layer rice over meat and potato, add the boiled eggs, and top with birista, saffron milk, kewra water and ghee.",),
   ("Seal and cook on the lowest heat 25 minutes, then rest 15 minutes before opening.",
    "Kewra goes in before the seal, not after. It needs the steam to carry it through the rice.")],
  "Keeps 2 days refrigerated. The potato is best on the day; it goes grainy after. Reheat covered with a splash of water.",
  ["dum"]),

]
