"""The rest of the gap list: Bengali, Bihari, Parsi, Maharashtrian, Punjabi,
Awadhi, Gujarati, Kashmiri and Northeast.

Mostly things that were missing not because they are obscure but because they
sit between categories: the breads nobody lists as a dish, the sweets that are
assumed, and two Himalayan ferments that had no representation at all.
"""
from add_recipes import R

E, M, A = "easy", "moderate", "advanced"
STOVE, PC, STEAM, BLEND, OVEN, KADHAI, TAWA = (
    "stovetop", "pressure-cooker", "steamer", "blender", "oven", "kadhai", "tawa")
VEG, VGN, GF, DF, NF, NOG = (
    "vegetarian", "vegan", "gluten-free", "dairy-free", "nut-free", "no-onion-garlic")

BATCH = [

# --------------------------------------------------------------- Bengali

R("muri-ghonto", "Muri Ghonto", "Bengali",
  "fish head cooked down with rice and potato, the dish that wastes nothing",
  4, 20, 40, M, [STOVE], [GF, DF, NF], ["fish"],
  [("fish", "1 large head, halved, plus 200g of steaks", "rohu or katla; the head is the dish, not a garnish", True),
   ("basmati-rice", "150g, washed and drained", "gobindobhog is traditional; any short fragrant rice works", True),
   ("potato", "2, cubed", None, True),
   ("onion", "2, sliced", None, True),
   ("ginger", "1 tbsp paste", None, True),
   ("turmeric", "1 tsp", None, True),
   ("cumin-powder", "1 tsp", None, True),
   ("bay-leaf", "2", None, True),
   ("garam-masala", "1 tsp", None, True),
   ("green-chilli", "4, slit", None, True),
   ("mustard-oil", "5 tbsp", None, True),
   ("sugar", "1 tsp", None, True),
   ("salt", "to taste", None, True)],
  ["The head is fried hard first and then broken up in the pot. That breaking is the technique.",
   "Heat the mustard oil to smoking and let it cool a little before cooking. Raw mustard oil is harsh."],
  [("Rub the fish head with turmeric and salt and fry in the hot mustard oil until dark and crisp. Break it into pieces in the pan.",),
   ("Fry the potato cubes until golden. Lift out.",),
   ("Temper the bay leaves, add the onion and fry until brown, then the ginger paste and cumin.",),
   ("Return the fish and potato, add the drained rice and toss 3 minutes so every grain is coated in oil.",),
   ("Add 400ml hot water, cover and cook 15 minutes until the rice is done and almost dry.",),
   ("Finish with the garam masala, green chillies and sugar. Rest 10 minutes.",)],
  "Keeps 2 days refrigerated. It contains cooked rice and fish, so cool it quickly and refrigerate within two hours. Reheat thoroughly.",
  []),

R("chitol-macher-muitha", "Chitol Macher Muitha", "Bengali",
  "clown knifefish scraped from the bone, rolled into dumplings and simmered in gravy",
  4, 45, 40, A, [STOVE], [GF, DF, NF], ["fish"],
  [("fish", "600g, flesh scraped from the bone", "chitol is traditional; any firm white fish scraped fine will hold", True),
   ("potato", "1, boiled and mashed", "the binder", True),
   ("onion", "2, one grated and one sliced", None, True),
   ("ginger", "2 tbsp paste", None, True),
   ("garlic", "1 tbsp paste", None, True),
   ("turmeric", "1.5 tsp", None, True),
   ("cumin-powder", "1.5 tsp", None, True),
   ("coriander-powder", "1 tsp", None, True),
   ("chilli-powder", "1 tsp", None, True),
   ("garam-masala", "1 tsp", None, True),
   ("bay-leaf", "2", None, True),
   ("mustard-oil", "6 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["Muitha means a fistful. The paste is squeezed in the hand to shape it, which is where the name comes from.",
   "The dumplings are boiled first, then fried, then simmered. All three steps matter."],
  [("Mix the scraped fish with the mashed potato, grated onion, half the ginger, turmeric and salt into a stiff paste.",),
   ("Squeeze fistfuls into rough dumplings and drop into simmering salted water for 8 minutes until they float.",),
   ("Lift out, cool slightly and fry in the mustard oil until browned on all sides. Set aside.",
    "Boiling first is what stops them disintegrating in the gravy."),
   ("In the same oil, temper the bay leaves, fry the sliced onion until brown, then add the remaining ginger, garlic and the ground spices with a splash of water.",),
   ("Cook until the oil separates, add 400ml water and bring to a boil.",),
   ("Slide the dumplings back in and simmer 10 minutes. Finish with garam masala.",)],
  "Keeps 2 days refrigerated and the dumplings firm up, which is no bad thing. Reheat gently so they stay whole.",
  []),

R("kochu-bata", "Kochu Bata", "Bengali",
  "colocasia mashed with mustard and green chilli, eaten first with rice",
  4, 15, 25, E, [STOVE, BLEND], [VEG, VGN, GF, DF, NF], [],
  [("colocasia", "500g, peeled and cubed", "wear gloves peeling it; the raw sap irritates", True),
   ("mustard-seeds", "2 tbsp, soaked and ground to a paste", None, True),
   ("green-chilli", "5", None, True),
   ("mustard-oil", "4 tbsp", "raw, stirred in at the end, which is the Bengali way with a bata", True),
   ("nigella", "1/2 tsp", None, True),
   ("turmeric", "1/2 tsp", None, True),
   ("salt", "to taste", None, True)],
  ["A bata is a mash, eaten at the start of the meal with plain rice and a little raw mustard oil.",
   "Colocasia must be cooked through completely. Undercooked it scratches the throat."],
  [("Boil the colocasia in salted water with the turmeric until completely soft, about 20 minutes. Drain thoroughly.",
    "Thoroughly. Any water left makes a sloppy bata."),
   ("Mash it smooth while hot, or pulse briefly in a blender.",),
   ("Grind the soaked mustard seeds with three of the green chillies and a pinch of salt into a paste.",),
   ("Beat the mustard paste through the mash with the raw mustard oil and salt.",),
   ("Temper the nigella and remaining chillies in a spoonful of hot oil and stir through.",)],
  "Keeps 2 days refrigerated. The mustard sharpens as it stands. Serve at room temperature, never hot.",
  []),

R("bhapa-doi", "Bhapa Doi", "Bengali",
  "sweetened yogurt steamed until it sets like a baked custard",
  6, 10, 30, E, [STEAM, OVEN], [VEG, GF, NF], ["dairy"],
  [("yogurt", "500g, thick and hung 2 hours", "hung, or it will not set", True),
   ("condensed-milk", "200g", None, True),
   ("milk", "100ml", None, True),
   ("cardamom", "4 pods, seeds ground", None, True),
   ("pistachios", "2 tbsp, slivered", None, False),
   ("saffron", "a pinch", None, False)],
  ["Three ingredients and one variable: how thick your yogurt is. Watery yogurt will not set no matter how long you steam it.",
   "It should still wobble when you take it out. It firms in the fridge."],
  [("Hang the yogurt in muslin for 2 hours to drain off the whey.",),
   ("Whisk it smooth with the condensed milk, milk and cardamom. Do not aerate it.",
    "Whisk to combine, not to fluff. Air bubbles give a pitted surface."),
   ("Pour into ramekins or a single dish and cover tightly with foil.",),
   ("Steam over simmering water 25 minutes, or bake in a water bath at 160C for 30 minutes.",),
   ("Test with a skewer: it should come out clean but the centre should still wobble.",),
   ("Cool, then refrigerate at least 4 hours. Top with pistachio and saffron before serving.",)],
  "Keeps 3 days refrigerated. It is a set dairy custard, so keep it cold and do not leave it out.",
  []),

R("aam-doi", "Aam Doi", "Bengali",
  "mango folded into set yogurt, the summer version of mishti doi",
  6, 15, 20, E, [STEAM], [VEG, GF, NF], ["dairy"],
  [("yogurt", "500g, hung 2 hours", None, True),
   ("raw-mango", "400g ripe mango, pureed", "ripe and sweet, despite the ingredient name", True),
   ("condensed-milk", "150g", None, True),
   ("sugar", "2 tbsp", None, False),
   ("cardamom", "3 pods, seeds ground", None, True)],
  ["Use a sweet, fibreless mango and pass the puree through a sieve. Fibres ruin the texture.",
   "The mango carries a lot of water, so the yogurt has to be hung longer than for plain bhapa doi."],
  [("Hang the yogurt 2 hours until quite firm.",),
   ("Puree the mango and pass it through a sieve.",),
   ("Whisk the yogurt with the condensed milk, cardamom and mango puree until even.",),
   ("Pour into a dish, cover with foil and steam 20 minutes until just set at the edges.",),
   ("Cool and refrigerate 4 hours before serving.",
    "It sets in the fridge, not in the steamer. Do not overcook it looking for firmness.")],
  "Keeps 2 days refrigerated. Fresh mango shortens its life compared with plain mishti doi, so eat it sooner.",
  []),

# ---------------------------------------------------------------- Bihari

R("bafauri", "Bafauri", "Bihari",
  "steamed chana dal dumplings, the light cousin of the fried snack",
  4, 20, 30, E, [STEAM, BLEND], [VEG, VGN, GF, DF, NF], [],
  [("chana-dal", "250g, soaked 4 hours", None, True),
   ("onion", "1, finely chopped", None, True),
   ("green-chilli", "4, chopped", None, True),
   ("ginger", "1 tbsp, grated", None, True),
   ("coriander-leaves", "a handful", None, True),
   ("ajwain", "1/2 tsp", None, True),
   ("turmeric", "1/2 tsp", None, True),
   ("asafoetida", "a pinch", None, True),
   ("neutral-oil", "1 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["Steamed, not fried, which makes it the rare Bihari snack you can eat a lot of.",
   "Grind the dal coarse. A smooth paste steams into something rubbery."],
  [("Drain the dal and grind coarse with almost no water. It should still have grit to it.",),
   ("Mix in the onion, green chilli, ginger, coriander, ajwain, turmeric, asafoetida, oil and salt.",),
   ("Shape into balls the size of a lime with wet hands.",),
   ("Steam 20 minutes until firm and a skewer comes out clean.",
    "Steam, do not boil. Boiled bafauri falls apart."),
   ("Rest 5 minutes before lifting them off, and serve with a sharp chutney.",)],
  "Keeps 2 days refrigerated. Re-steam for 5 minutes to soften rather than microwaving, which toughens them.",
  ["hing"]),

R("bihari-ghugni", "Bihari Ghugni", "Bihari",
  "white peas simmered with ginger and eaten from a leaf bowl at the roadside",
  4, 15, 45, E, [STOVE, PC], [VEG, VGN, GF, DF, NF], [],
  [("dried-peas", "300g white peas, soaked overnight", None, True),
   ("onion", "2, finely chopped", None, True),
   ("tomato", "2, chopped", None, True),
   ("ginger", "2 tbsp, julienned", "half cooked in, half raw on top", True),
   ("green-chilli", "4, chopped", None, True),
   ("cumin-seeds", "1 tsp", None, True),
   ("turmeric", "1/2 tsp", None, True),
   ("coriander-powder", "2 tsp", None, True),
   ("chilli-powder", "1 tsp", None, True),
   ("amchur", "1 tsp", None, True),
   ("mustard-oil", "3 tbsp", None, True),
   ("coriander-leaves", "a handful", None, True),
   ("salt", "to taste", None, True)],
  ["Bihari ghugni is drier and more sharply spiced than the Bengali version, and it is finished with raw ginger and amchur.",
   "The peas should hold their shape. Cooked to mush it becomes a dal."],
  [("Pressure cook the soaked peas with turmeric and salt for 2 whistles, or boil 40 minutes until tender but whole.",),
   ("Temper the cumin in the mustard oil, add the onion and fry until golden.",),
   ("Add half the ginger, the green chilli, tomato, coriander powder and chilli powder. Cook until the oil separates.",),
   ("Add the drained peas with a little of their liquid and simmer 10 minutes, mashing a few against the pan to thicken.",),
   ("Finish with the amchur, the remaining raw ginger and coriander.",)],
  "Keeps 3 days refrigerated and thickens; loosen with hot water. Add the raw ginger fresh each time you serve it.",
  []),

R("bihari-malpua", "Bihari Malpua", "Bihari",
  "banana and flour pancakes fried in ghee and steeped in syrup",
  12, 20, 30, E, [STOVE, KADHAI], [VEG, NF], ["gluten", "dairy"],
  [("maida", "200g", None, True),
   ("raw-banana", "2 very ripe bananas, mashed", None, True),
   ("milk", "250ml", None, True),
   ("sugar", "300g, for the syrup", None, True),
   ("fennel-seeds", "1 tsp, crushed", "the Bihari signature in a malpua", True),
   ("cardamom", "4 pods, seeds ground", None, True),
   ("ghee", "6 tbsp, for shallow frying", None, True),
   ("water", "150ml", None, True)],
  ["The batter rests. An hour minimum; overnight is better and gives a slight sourness that the syrup needs.",
   "Fry them small. A large malpua cooks unevenly and stays raw at the centre."],
  [("Whisk the flour, mashed banana, milk, fennel and cardamom into a batter the thickness of double cream. Rest 1 hour.",),
   ("Boil the sugar and water 5 minutes into a thin syrup and keep it warm.",),
   ("Heat the ghee in a shallow pan and pour in small ladles of batter, no wider than 8cm.",),
   ("Fry 2 minutes a side until the edges are lacy and dark and the centre is set.",
    "The lacy edge is the mark of a good malpua. It comes from enough fat and a hot enough pan."),
   ("Lift straight into the warm syrup and leave 5 minutes, then drain and serve.",
    "In and out. Left in the syrup they go soggy.")],
  "Best the day they are made. They keep 2 days refrigerated in their syrup but soften considerably.",
  []),

R("silbatte-ki-chutney", "Silbatte ki Chutney", "Bihari",
  "tomato, chilli and garlic crushed on a stone, not blended",
  4, 15, 10, E, [STOVE], [VEG, VGN, GF, DF, NF], [],
  [("tomato", "4, roasted whole over a flame", None, True),
   ("green-chilli", "6, roasted", None, True),
   ("garlic", "8 cloves, roasted in their skins", None, True),
   ("coriander-leaves", "a large handful", None, True),
   ("mustard-oil", "2 tbsp, raw", None, True),
   ("lemon", "1/2", None, False),
   ("salt", "to taste", None, True)],
  ["Silbatta is the stone and roller. A blender gives you a smooth sauce; the stone gives you a chutney with texture, which is the whole difference.",
   "If you must use a blender, pulse two or three times only."],
  [("Char the tomatoes, chillies and unpeeled garlic directly over a flame until blackened and blistered.",),
   ("Rest them under a cloth for 5 minutes, then rub off the burnt skins. Do not rinse them.",
    "Rinsing washes away the smoke, which is the point of roasting."),
   ("Crush the garlic and chillies first with the salt, then work in the tomatoes.",),
   ("Add the coriander and crush briefly so it is bruised, not pulped.",),
   ("Beat in the raw mustard oil and sharpen with lemon if the tomatoes were sweet.",)],
  "Keeps 3 days refrigerated. The raw garlic strengthens overnight. Serve at room temperature with litti or rice.",
  []),

# ----------------------------------------------------------------- Parsi

R("parsi-chelo-kebab", "Chelo Kebab", "Parsi",
  "minced kebabs over buttered rice with a raw egg yolk, the Bombay club dish",
  4, 30, 30, M, [STOVE, OVEN], [GF, NF], ["dairy", "egg"],
  [("mutton", "600g minced, with some fat", None, True),
   ("basmati-rice", "400g", None, True),
   ("onion", "1, grated and squeezed dry", "squeeze it, or the kebabs fall apart", True),
   ("eggs", "4 yolks, to serve", "traditionally raw on the hot rice; cook them if you prefer", True),
   ("butter", "80g", None, True),
   ("saffron", "a pinch, soaked in warm milk", None, True),
   ("ginger", "1 tbsp paste", None, True),
   ("garlic", "1 tbsp paste", None, True),
   ("black-pepper", "1.5 tsp", None, True),
   ("chilli-powder", "1 tsp", None, True),
   ("salt", "to taste", None, True)],
  ["Borrowed from Iranian chelo kabab and kept alive by Bombay's Irani restaurants. The butter, the saffron rice and the yolk are all part of it.",
   "A raw yolk on hot rice is traditional. If you would rather not, a soft-cooked yolk does the same job."],
  [("Mix the mince with the squeezed onion, ginger, garlic, pepper, chilli powder and salt. Knead 5 minutes until sticky.",
    "The kneading develops the bind. Under-worked mince crumbles off the skewer."),
   ("Rest the mixture in the refrigerator 30 minutes, then shape onto skewers in long flat kebabs.",),
   ("Cook the rice, drain, and fold through half the butter and the saffron milk.",),
   ("Grill or pan-fry the kebabs on high 4 minutes a side until charred outside and just cooked within.",),
   ("Serve the kebabs on the rice, dot with the remaining butter and slide a yolk on top of each plate.",)],
  "The kebabs keep 2 days refrigerated. Cook the rice fresh and add the yolk at the table, never in advance.",
  []),

R("parsi-akoori-toast", "Akoori on Toast", "Parsi",
  "soft-scrambled spiced eggs piled on buttered toast",
  2, 10, 10, E, [STOVE], [VEG, NF], ["egg", "dairy", "gluten"],
  [("eggs", "6", None, True),
   ("onion", "1, finely chopped", None, True),
   ("tomato", "1, chopped small", None, True),
   ("green-chilli", "3, chopped", None, True),
   ("ginger", "1 tsp, grated", None, True),
   ("turmeric", "1/4 tsp", None, True),
   ("coriander-leaves", "a handful", None, True),
   ("butter", "40g", None, True),
   ("cream", "2 tbsp", None, False),
   ("bread", "4 slices, toasted and buttered", None, True),
   ("salt", "to taste", None, True)],
  ["Akoori is defined by being underdone. It should pour slightly, not hold its shape.",
   "Everything else is cooked before the eggs go anywhere near the pan."],
  [("Soften the onion in the butter, add the ginger, green chilli and turmeric and cook 2 minutes.",),
   ("Add the tomato and cook just until it slumps, 2 minutes.",),
   ("Beat the eggs with the cream and salt and pour them in over low heat.",),
   ("Stir slowly and constantly, taking the pan off the heat every few seconds.",
    "Off the heat repeatedly. That is how you get curds this soft."),
   ("Pull it off while still visibly wet, fold in the coriander and pile onto the hot toast.",
    "It carries on cooking on the plate. Wet in the pan is right.")],
  "Eat immediately. Scrambled eggs do not keep or reheat.",
  []),

R("parsi-mawa-cake", "Mawa Cake", "Parsi",
  "dense cardamom cake made with reduced milk, sold by every Irani bakery",
  8, 20, 45, E, [OVEN], [VEG, NF], ["dairy", "egg", "gluten"],
  [("khoya", "200g, crumbled", "mawa; it is what makes this a mawa cake and not a sponge", True),
   ("maida", "200g", None, True),
   ("butter", "150g, softened", None, True),
   ("sugar", "180g", None, True),
   ("eggs", "3", None, True),
   ("milk", "80ml", None, True),
   ("cardamom", "10 pods, seeds ground", "generous; the cake should smell of it across the room", True),
   ("baking-soda", "1 tsp", None, True),
   ("almonds", "2 tbsp, slivered", None, False)],
  ["Mawa cake is deliberately dense. If it comes out light and airy, something has gone wrong.",
   "Crumble the khoya finely and warm it slightly so it blends rather than sitting in lumps."],
  [("Cream the butter and sugar until pale, then beat in the crumbled khoya.",),
   ("Add the eggs one at a time, beating well between each.",),
   ("Fold in the flour, soda and ground cardamom, then loosen with the milk to a thick dropping consistency.",
    "Fold, do not beat. Beating at this stage is what makes it rise like a sponge, which is not what this is."),
   ("Pour into a lined tin, scatter the almonds and bake at 170C for 40 minutes.",),
   ("Test with a skewer at the centre; a few moist crumbs are right, wet batter is not.",),
   ("Cool completely in the tin before cutting.",)],
  "Keeps 4 days in an airtight tin at room temperature and is better on day two. It contains egg and milk, so refrigerate in hot weather.",
  []),

# -------------------------------------------------------- Maharashtrian

R("kolhapuri-tambda-rassa", "Tambda Rassa", "Maharashtrian",
  "the fierce red mutton broth of Kolhapur, served alongside its white twin",
  4, 25, 60, M, [STOVE, PC, BLEND], [GF, DF, NF], [],
  [("mutton", "700g on the bone", None, True),
   ("dried-red-chilli", "15", "Kolhapuri lavangi if you can find them; this is meant to be hot", True),
   ("coconut", "80g, dry roasted until dark", None, True),
   ("onion", "3, two roasted dark and one sliced", None, True),
   ("garlic", "10 cloves", None, True),
   ("ginger", "2 tbsp", None, True),
   ("coriander-powder", "2 tbsp", "whole seeds dry roasted and ground are better if you have them", True),
   ("cumin-seeds", "1 tbsp", None, True),
   ("black-pepper", "1 tsp", None, True),
   ("turmeric", "1/2 tsp", None, True),
   ("neutral-oil", "6 tbsp", None, True),
   ("coriander-leaves", "a handful", None, True),
   ("salt", "to taste", None, True)],
  ["Tambda means red. It is served with pandhra rassa, the white coconut broth, and the pair is the point of a Kolhapuri meal.",
   "The rassa is thin, drunk from a bowl alongside the meat. Do not reduce it into a curry."],
  [("Dry roast the coconut, coriander seeds, cumin and chillies separately until each darkens and smells toasted.",
    "Separately. They brown at different speeds and a burnt chilli ruins the pot."),
   ("Grind them with the roasted onion, garlic and ginger into a smooth dark paste with a little water.",),
   ("Boil the mutton with turmeric, salt and 1.2 litres water until tender, about 45 minutes. Keep the stock.",),
   ("Fry the sliced onion in the oil until brown, add the ground paste and fry until the oil separates, 8 minutes.",),
   ("Add the mutton and its stock, bring to a boil and simmer 15 minutes.",),
   ("Skim the red oil that rises and spoon it back over each serving. Finish with coriander.",
    "That floating red oil is the signature. Do not skim it away.")],
  "Keeps 3 days refrigerated and improves overnight. Freezes well for a month. Reheat to a full boil.",
  []),

R("chakli", "Chakli", "Maharashtrian",
  "spiralled savoury crisps from a multi-grain flour, the centre of the Diwali faral",
  20, 30, 30, M, [STOVE, KADHAI, STEAM], [VEG, VGN, GF, DF, NF], [],
  [("rice-flour", "250g", None, True),
   ("besan", "60g", None, True),
   ("urad-dal", "40g, roasted and ground", None, True),
   ("sesame", "2 tbsp", None, True),
   ("cumin-seeds", "1 tsp", None, True),
   ("ajwain", "1/2 tsp", None, True),
   ("chilli-powder", "1.5 tsp", None, True),
   ("asafoetida", "1/2 tsp", None, True),
   ("neutral-oil", "3 tbsp hot, for the dough, plus 500ml for frying", "the hot oil rubbed into the flour is what makes it crumble", True),
   ("water", "as needed", None, True),
   ("salt", "to taste", None, True)],
  ["Bhajani, the roasted multigrain flour, is what a Maharashtrian household uses. This is a workable version from separate flours.",
   "The hot oil moyan is not optional. Without it the chakli is hard rather than short."],
  [("Mix the flours with the sesame, cumin, ajwain, chilli powder, asafoetida and salt.",),
   ("Pour the hot oil over and rub it in until the mixture holds shape when pressed.",
    "It should clump in your fist and break cleanly."),
   ("Add warm water gradually to a smooth, firm dough. Cover and rest 15 minutes.",),
   ("Press spirals onto a greased sheet with a chakli press.",),
   ("Fry on medium until the bubbling stops and they turn even gold, about 5 minutes.",
    "Medium, and do not crowd the pan. Rushed chaklis are raw inside."),
   ("Drain and cool completely before storing.",)],
  "Keeps 3 weeks in an airtight tin at room temperature.",
  ["hing"]),

R("shankarpali", "Shankarpali", "Maharashtrian",
  "sweet fried diamonds of flour and semolina, made by the tinful at Diwali",
  25, 20, 30, E, [STOVE, KADHAI], [VEG, NF], ["gluten", "dairy"],
  [("maida", "300g", None, True),
   ("rava", "50g, fine", "the semolina is what gives the bite", True),
   ("sugar", "150g", None, True),
   ("milk", "150ml", None, True),
   ("ghee", "80g, melted", None, True),
   ("cardamom", "4 pods, seeds ground", None, False),
   ("neutral-oil", "500ml for deep frying", None, True),
   ("salt", "a pinch", None, True)],
  ["Fry on low. This is the one rule; shankarpali browned fast is raw in the middle and goes soft the next day.",
   "The dough should be firm, closer to pastry than to chapati dough."],
  [("Warm the milk with the sugar until it dissolves, then cool. Stir in the melted ghee.",),
   ("Work in the flour, rava, cardamom and salt to a firm dough. Rest 20 minutes.",),
   ("Roll out 4mm thick and cut into diamonds.",),
   ("Fry on genuinely low heat, turning often, for about 8 minutes until pale gold throughout.",
    "Low and slow. If they colour in three minutes the oil is too hot."),
   ("Drain and cool completely before storing.",)],
  "Keeps 3 weeks in an airtight tin at room temperature.",
  []),

# --------------------------------------------------------------- Punjabi

R("laccha-paratha", "Laccha Paratha", "Punjabi",
  "flaky layered paratha, pleated and coiled so it pulls apart in threads",
  6, 30, 25, M, [TAWA], [VEG, NF], ["gluten", "dairy"],
  [("atta", "400g", None, True),
   ("ghee", "80g, melted", "the layers are ghee; oil gives fewer and softer ones", True),
   ("maida", "3 tbsp, for dusting between layers", None, True),
   ("water", "250ml, warm", None, True),
   ("salt", "1 tsp", None, True)],
  ["The pleating is the whole dish. Roll thin, brush with ghee, dust with flour, pleat like a fan, then coil.",
   "Rest the dough properly. Under-rested dough springs back and will not roll thin enough to layer."],
  [("Make a soft dough with the flour, salt and warm water. Knead 8 minutes, oil the surface and rest 30 minutes.",),
   ("Roll a ball out as thin as you can manage, almost translucent.",),
   ("Brush generously with melted ghee and dust with maida.",
    "The flour dusting keeps the layers from fusing back together."),
   ("Pleat the sheet like a paper fan, stretch it gently, then coil it into a spiral and tuck the end under. Rest 10 minutes.",),
   ("Roll the coil out gently to 18cm, keeping the spiral intact.",
    "Gently. Press hard and you crush the layers you just built."),
   ("Cook on a hot tawa with ghee, 2 minutes a side, then crush lightly between your palms to open the layers.",)],
  "Best straight off the tawa. They keep a day wrapped in a cloth at room temperature; reheat on a dry tawa, not a microwave.",
  ["resting-dough"]),

R("mooli-paratha", "Mooli Paratha", "Punjabi",
  "radish-stuffed paratha, the winter breakfast that defeats most people",
  6, 30, 25, M, [TAWA], [VEG, NF], ["gluten", "dairy"],
  [("atta", "400g", None, True),
   ("radish", "500g, grated", "white mooli; the water in it is the whole problem", True),
   ("green-chilli", "3, chopped", None, True),
   ("ginger", "1 tbsp, grated", None, True),
   ("ajwain", "1 tsp", None, True),
   ("coriander-leaves", "a handful", None, True),
   ("amchur", "1 tsp", None, True),
   ("ghee", "6 tbsp", None, True),
   ("water", "250ml", None, True),
   ("salt", "to taste", None, True)],
  ["The reason mooli parathas tear is water. Salt the grated radish, wait, and squeeze it hard. Squeeze it again.",
   "Use the squeezed radish water to knead the dough. Nothing is wasted and it tastes better."],
  [("Grate the radish, mix with 1 tsp salt and leave 20 minutes. Then squeeze it out in a cloth, hard.",
    "You should get a surprising amount of liquid. Keep it for the dough."),
   ("Knead the flour with the radish water, topping up with plain water, into a soft dough. Rest 20 minutes.",),
   ("Mix the squeezed radish with the green chilli, ginger, ajwain, coriander and amchur. Do not add salt again.",),
   ("Roll a small disc, place a ball of filling in the centre, gather the edges over and pinch shut.",),
   ("Roll out gently to 16cm, dusting well.",
    "If it starts to tear, stop and patch with a little dry flour rather than pressing on."),
   ("Cook on a hot tawa with ghee, 2 minutes a side, pressing the edges down.",)],
  "Best fresh. They keep a day wrapped in a cloth; reheat on a dry tawa.",
  ["resting-dough"]),

R("achari-chicken", "Achari Chicken", "Punjabi",
  "chicken cooked in pickling spices, sour and sharp rather than rich",
  4, 20, 40, M, [STOVE, KADHAI], [GF, NF], ["dairy"],
  [("chicken", "800g on the bone", None, True),
   ("yogurt", "200g, whisked", None, True),
   ("mustard-seeds", "1 tsp", "the achari five: mustard, fennel, fenugreek, nigella and cumin", True),
   ("fennel-seeds", "1.5 tsp", None, True),
   ("fenugreek-seeds", "1/2 tsp", None, True),
   ("nigella", "1 tsp", None, True),
   ("cumin-seeds", "1 tsp", None, True),
   ("onion", "3, sliced", None, True),
   ("ginger", "1 tbsp paste", None, True),
   ("garlic", "1 tbsp paste", None, True),
   ("turmeric", "1/2 tsp", None, True),
   ("chilli-powder", "1.5 tsp", None, True),
   ("amchur", "1 tsp", None, True),
   ("mustard-oil", "5 tbsp", "mustard oil, because the dish is imitating a pickle", True),
   ("salt", "to taste", None, True)],
  ["Achari means pickled. The five whole seeds are the panch phoran of the pickle jar, and they go in whole, not ground.",
   "Marinate in the refrigerator for an hour if you have it."],
  [("Marinate the chicken in the yogurt, ginger, garlic, turmeric and salt for 1 hour in the refrigerator.",),
   ("Heat the mustard oil to smoking, then cool slightly. Splutter all five whole seeds together.",
    "Smoking first takes the raw bite out of mustard oil. Then let it cool or the seeds burn."),
   ("Add the onion and fry until deep gold.",),
   ("Add the marinated chicken and chilli powder and fry on high 10 minutes until the yogurt tightens around the meat.",),
   ("Cover and cook 20 minutes on low until done, adding a splash of water only if it catches.",),
   ("Finish with the amchur and rest 10 minutes.",)],
  "Keeps 3 days refrigerated and sharpens as it sits, which suits it. Reheat gently.",
  []),

R("pindi-chana", "Pindi Chana", "Punjabi",
  "chickpeas blackened with tea and whole spice, with no tomato and no onion",
  4, 20, 60, M, [STOVE, PC], [VEG, VGN, GF, DF, NF, NOG], [],
  [("chickpeas", "300g, soaked overnight", None, True),
   ("black-pepper", "1 tsp", None, True),
   ("dried-red-chilli", "4", None, True),
   ("cinnamon", "1 stick", None, True),
   ("black-cardamom", "2", "the smoke in the dish", True),
   ("cloves", "4", None, True),
   ("bay-leaf", "2", None, True),
   ("amchur", "2 tsp", None, True),
   ("anardana", "1 tbsp, ground", "pomegranate seed; the sourness that makes it pindi", True),
   ("ginger", "2 tbsp, julienned, to finish", None, True),
   ("green-chilli", "4, slit, to finish", None, True),
   ("neutral-oil", "4 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["Named for Rawalpindi. It has no onion, no garlic and no tomato: the colour comes from cooking the chickpeas with the whole spices, traditionally in a muslin bag with tea leaves.",
   "It should be almost dry and very dark, not a gravy."],
  [("Boil the soaked chickpeas with the cinnamon, black cardamom, cloves and bay leaves until soft and dark, about 45 minutes or 5 whistles.",
    "The whole spices go in the water, not the pan. That is where the colour comes from."),
   ("Drain, keeping a cup of the cooking liquid. Fish out the whole spices.",),
   ("Grind the pepper, dried chillies and anardana together coarsely.",),
   ("Heat the oil, add the ground mixture and fry 1 minute, then the chickpeas.",),
   ("Toss on high 8 minutes, crushing a handful against the pan, adding splashes of the reserved liquid to keep it moving.",),
   ("Finish with the amchur, raw ginger julienne and slit green chillies.",)],
  "Keeps 3 days refrigerated and improves overnight. Add the ginger fresh when serving.",
  []),

# ------------------------------------------------------- Awadhi/Lucknowi

R("imarti", "Imarti", "Awadhi/Lucknowi",
  "urad dal batter piped into flower coils and soaked in syrup, denser than jalebi",
  15, 30, 30, A, [STOVE, KADHAI, BLEND], [VEG, GF, NF], [],
  [("urad-dal", "250g, soaked 4 hours", "imarti is dal, not flour; that is the whole difference from jalebi", True),
   ("sugar", "400g", None, True),
   ("water", "200ml", None, True),
   ("saffron", "a pinch", None, True),
   ("cardamom", "4 pods, seeds ground", None, True),
   ("lemon", "1/2", "keeps the syrup from crystallising", True),
   ("neutral-oil", "500ml for deep frying", None, True)],
  ["Imarti is thicker, darker and chewier than jalebi because it is made from ground urad dal rather than fermented flour.",
   "The batter must be beaten until it floats. That aeration is what stops the imarti being a solid lump."],
  [("Grind the drained dal with as little water as possible into a smooth, stiff paste.",),
   ("Beat it hard by hand for 5 minutes until pale and airy.",
    "Drop a little in water. If it floats, it is ready. If it sinks, keep beating."),
   ("Boil the sugar and water with the saffron and cardamom to a one-thread syrup, add the lemon juice and keep warm.",),
   ("Pipe the batter into hot oil in a flower shape: a ring with loops around the outside.",),
   ("Fry on medium until crisp on both sides, about 3 minutes, keeping the colour pale.",),
   ("Lift straight into the warm syrup for 2 minutes, then drain on a rack.",
    "Two minutes only. Longer and they go limp.")],
  "Best the day they are made. They keep 2 days at room temperature in a covered tin, going softer each day.",
  []),

R("rabri", "Rabri", "Awadhi/Lucknowi",
  "milk reduced for an hour with the skin folded back in at every stage",
  4, 5, 75, M, [STOVE], [VEG, GF, NF], ["dairy"],
  [("milk", "2 litres, full fat", "full fat, and nothing less; skimmed milk will not layer", True),
   ("sugar", "80g", None, True),
   ("cardamom", "5 pods, seeds ground", None, True),
   ("saffron", "a pinch", None, False),
   ("pistachios", "2 tbsp, slivered", None, False),
   ("almonds", "2 tbsp, slivered", None, False)],
  ["Rabri is not thickened milk, it is collected milk skin. The layers are the dish, so it should never be smooth.",
   "Use the widest pan you own. More surface area means more skin, which means better rabri."],
  [("Bring the milk to a boil in a wide heavy pan, then lower to a bare simmer.",),
   ("As a skin forms, push it to the side of the pan with a spatula and leave it stuck there.",
    "Do not stir it back in. You are collecting layers on the wall of the pan."),
   ("Keep going for about an hour, until the milk has reduced by three quarters.",),
   ("Add the sugar, cardamom and saffron and stir to dissolve.",),
   ("Scrape all the collected skin off the sides back into the milk and fold once, no more.",
    "Once. Stirring it smooth undoes the entire hour."),
   ("Cool and refrigerate. Serve cold, topped with the nuts.",)],
  "Keeps 3 days refrigerated. It is reduced dairy, so keep it cold and do not leave it out.",
  []),

R("nalli-nihari", "Nalli Nihari", "Awadhi/Lucknowi",
  "marrow bones and shank stewed overnight, eaten at dawn",
  4, 30, 240, A, [STOVE], [NF], ["gluten"],
  [("mutton", "1kg shank with marrow bones", "the marrow is the point; ask for nalli specifically", True),
   ("onion", "4, sliced", None, True),
   ("ginger", "3 tbsp paste, plus julienne to finish", None, True),
   ("garlic", "2 tbsp paste", None, True),
   ("atta", "5 tbsp", "the thickener; nihari gravy is flour-bound, not reduced", True),
   ("fennel-powder", "2 tbsp", None, True),
   ("dry-ginger-powder", "1 tbsp", None, True),
   ("chilli-powder", "2 tsp", None, True),
   ("turmeric", "1 tsp", None, True),
   ("garam-masala", "2 tsp", None, True),
   ("black-cardamom", "3", None, True),
   ("neutral-oil", "150ml", None, True),
   ("lemon", "1", None, True),
   ("salt", "to taste", None, True)],
  ["Nihar means dawn. It was cooked overnight on dying coals and eaten at first light, and the long cook is not negotiable.",
   "Nalli is the marrow bone. Serve it with a thin skewer so people can get the marrow out."],
  [("Brown the onions in the oil until deep and dark. Lift half out and reserve for the top.",),
   ("Add the ginger and garlic pastes, then the fennel, dry ginger, chilli, turmeric and black cardamom. Fry 3 minutes.",),
   ("Add the meat and bones and fry hard until sealed and coloured, 10 minutes.",),
   ("Add 2 litres water, bring to a boil, then cover and cook on the lowest heat for 3 hours.",
    "The lowest heat you can hold. A hard boil makes the meat stringy rather than soft."),
   ("Slake the flour in cold water and stir it in. Simmer uncovered 30 minutes until the gravy coats a spoon.",
    "Slaked in cold water, always, or it lumps."),
   ("Finish with garam masala. Serve topped with the reserved onions, ginger julienne and lemon.",)],
  "Keeps 3 days refrigerated and is famously better the next day. Reheat to a full simmer, loosening with hot water.",
  ["dum"]),

R("zarda-pulao", "Zarda Pulao", "Awadhi/Lucknowi",
  "sweet saffron rice with dried fruit, served at weddings",
  6, 20, 35, M, [STOVE], [VEG, GF], ["dairy", "nuts"],
  [("basmati-rice", "400g, soaked 30 minutes", None, True),
   ("sugar", "300g", None, True),
   ("ghee", "80g", None, True),
   ("saffron", "a generous pinch, soaked in warm milk", "zarda means yellow; this is where it comes from", True),
   ("cardamom", "6 pods", None, True),
   ("cloves", "4", None, True),
   ("cashew", "40g", None, True),
   ("almonds", "40g, slivered", None, True),
   ("raisins", "40g", None, True),
   ("khoya", "80g, crumbled", None, False),
   ("water", "700ml", None, True)],
  ["The rice is boiled first and only then met with sugar. Sugar added to raw rice stops it softening.",
   "It should be dry and separate, not sticky. Zarda is a pulao, not a kheer."],
  [("Boil the soaked rice in plenty of water with the cardamom and cloves until 80 per cent done. Drain well.",),
   ("Fry the nuts and raisins in the ghee until golden and lift out.",),
   ("Add the drained rice to the ghee with the saffron milk and fold gently.",),
   ("Scatter the sugar over the top, cover tightly and cook on the lowest heat 12 minutes.",
    "The sugar melts down through the rice. Do not stir it in or you will break the grains."),
   ("Fold in the fried nuts, raisins and khoya with a fork.",),
   ("Rest 10 minutes covered before serving.",)],
  "Keeps 2 days refrigerated. Cool quickly and refrigerate within two hours as with any cooked rice. Steam to reheat.",
  []),

# -------------------------------------------------------------- Gujarati

R("khakhra", "Khakhra", "Gujarati",
  "wheat rounds roasted paper-thin and pressed until they snap",
  10, 25, 35, M, [TAWA], [VEG, VGN, DF, NF], ["gluten"],
  [("atta", "300g", None, True),
   ("besan", "2 tbsp", None, False),
   ("ajwain", "1 tsp", None, True),
   ("turmeric", "1/2 tsp", None, True),
   ("chilli-powder", "1 tsp", None, False),
   ("neutral-oil", "3 tbsp", None, True),
   ("water", "170ml", None, True),
   ("salt", "1 tsp", None, True)],
  ["The pressing is the technique. Each round is roasted slowly and pressed with a cloth-covered pad until every bubble is flattened out.",
   "Roll them thinner than you think reasonable. A thick khakhra is a chapati."],
  [("Make a stiff dough with everything and knead 8 minutes. Rest 20 minutes.",
    "Stiffer than chapati dough. A soft dough will not roll thin enough."),
   ("Roll each ball out as thin as possible, at least 20cm across.",),
   ("Cook on a low tawa for 30 seconds a side to set it.",),
   ("Now press continuously with a folded cloth, moving around the round, for 2 minutes a side.",
    "Low heat and constant pressure. Rushing it gives a leathery khakhra with soft spots."),
   ("It is done when it is uniformly pale brown, rigid and free of any give.",),
   ("Cool completely on a rack before stacking.",)],
  "Keeps 3 weeks in an airtight tin at room temperature. If they soften, 3 minutes in a low oven restores the snap.",
  []),

R("ghughra", "Ghughra", "Gujarati",
  "sweet fried crescents filled with coconut, semolina and nuts",
  16, 35, 30, M, [STOVE, KADHAI], [VEG, NF], ["gluten", "dairy"],
  [("maida", "300g", None, True),
   ("ghee", "60g for the dough, plus 2 tbsp for the filling", None, True),
   ("rava", "100g", None, True),
   ("coconut", "80g, grated", None, True),
   ("khoya", "100g, crumbled", None, False),
   ("sugar", "150g, ground", None, True),
   ("cardamom", "6 pods, seeds ground", None, True),
   ("almonds", "40g, chopped", None, True),
   ("raisins", "30g", None, True),
   ("neutral-oil", "500ml for deep frying", None, True),
   ("water", "as needed", None, True)],
  ["Also called gujiya further north. The dough is short with ghee so the shell stays crisp rather than chewy.",
   "The filling must be cold before it goes in, or the seal opens in the oil."],
  [("Rub the 60g ghee into the flour until it clumps, then bring together with cold water into a firm dough. Rest 30 minutes.",),
   ("Roast the rava in 2 tbsp ghee until it smells nutty. Add the coconut and roast 2 minutes more.",),
   ("Take off the heat, stir in the khoya, sugar, cardamom, almonds and raisins, and cool completely.",),
   ("Roll small discs, place filling on one half, wet the rim and fold over. Press out any air and crimp firmly.",
    "Trapped air expands and bursts the seam. Press it out as you fold."),
   ("Fry on medium-low until pale gold and blistered, about 5 minutes.",
    "Low and slow. High heat browns the shell before the pastry cooks through."),
   ("Drain and cool completely.",)],
  "Keeps 10 days in an airtight tin at room temperature. If you used khoya, refrigerate after 3 days.",
  []),

# -------------------------------------------------------------- Kashmiri

R("harissa-kashmiri", "Harissa", "Kashmiri",
  "mutton pounded with rice into a smooth paste, eaten at dawn in a Srinagar winter",
  6, 30, 300, A, [STOVE], [GF, DF, NF], [],
  [("mutton", "1kg, boneless shoulder", None, True),
   ("rice", "150g, soaked", "cooked down with the meat until neither is distinguishable", True),
   ("fennel-powder", "2 tbsp", None, True),
   ("dry-ginger-powder", "1 tbsp", None, True),
   ("black-cardamom", "3", None, True),
   ("cinnamon", "1 stick", None, True),
   ("cloves", "5", None, True),
   ("shallot", "8, fried crisp to finish", None, True),
   ("mustard-oil", "150ml", None, True),
   ("water", "2 litres", None, True),
   ("salt", "to taste", None, True)],
  ["Nothing to do with the North African chilli paste of the same name. This is a Kashmiri winter breakfast, sold from specialist shops that make nothing else.",
   "It is pounded, not blended, for five or more hours until it is a smooth paste with no fibre left."],
  [("Boil the mutton with the whole spices, fennel, dry ginger, salt and the water. Skim carefully.",),
   ("Simmer 3 hours until the meat collapses at a touch. Fish out the whole spices.",),
   ("Add the soaked rice and cook a further hour until it has disintegrated.",),
   ("Now pound. Work it against the side of the pot with a heavy wooden spoon for at least an hour, until no fibre remains.",
    "This is the dish. Blending gives you a puree, which is a different and lesser thing."),
   ("Adjust with hot water to a thick, pourable paste and check the salt.",),
   ("Serve in bowls with a ladle of smoking mustard oil and the crisp fried shallots over the top.",
    "The hot oil poured over at the table is part of it.")],
  "Keeps 3 days refrigerated and sets solid when cold. Reheat with hot water, stirring hard to bring it back. Freezes for a month.",
  []),

# ------------------------------------------------------ Northeast Indian

R("chhurpi-soup", "Chhurpi Soup", "Northeast Indian",
  "fermented cheese simmered with greens, the Sikkimese winter bowl",
  4, 15, 30, E, [STOVE], [VEG, GF, NF], ["dairy"],
  [("paneer", "200g, cut small and dried hard", "standing in for soft chhurpi, the fermented yak cheese", True),
   ("spinach", "200g, chopped", None, True),
   ("bamboo-shoot", "100g, sliced", None, True),
   ("onion", "1, chopped", None, True),
   ("garlic", "6 cloves, chopped", None, True),
   ("ginger", "1 tbsp, chopped", None, True),
   ("green-chilli", "3, slit", None, True),
   ("black-pepper", "1 tsp", None, True),
   ("neutral-oil", "2 tbsp", None, True),
   ("water", "1 litre", None, True),
   ("salt", "to taste", None, True)],
  ["Chhurpi is yak or cow milk cheese, fermented and either eaten soft or dried into a block hard enough to chew for hours.",
   "Paneer is the honest substitute available here. It gives the texture but not the sourness, so the bamboo shoot is doing more work than usual."],
  [("Fry the onion, garlic and ginger in the oil until soft.",),
   ("Add the bamboo shoot and cook 5 minutes.",),
   ("Add the water, bring to a boil and simmer 10 minutes.",),
   ("Add the cheese and the green chillies and simmer 8 minutes until it softens and begins to melt at the edges.",),
   ("Stir in the spinach, cook 3 minutes, and season heavily with pepper and salt.",)],
  "Keeps 2 days refrigerated. The cheese firms up again when cold; reheat gently to a simmer rather than boiling.",
  []),

R("kinema-curry", "Kinema", "Northeast Indian",
  "fermented soybeans cooked with tomato and chilli, pungent and deeply savoury",
  4, 15, 25, M, [STOVE], [VEG, VGN, GF, DF, NF], ["soy"],
  [("tofu", "250g, crumbled and left uncovered overnight", "standing in for kinema, fermented whole soybeans; the flavour is milder but the base is right", True),
   ("tomato", "3, chopped", None, True),
   ("onion", "2, chopped", None, True),
   ("garlic", "8 cloves", None, True),
   ("ginger", "1 tbsp", None, True),
   ("green-chilli", "5", None, True),
   ("turmeric", "1/2 tsp", None, True),
   ("coriander-leaves", "a handful", None, True),
   ("mustard-oil", "3 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["Kinema is a Limbu and Nepali ferment of the eastern Himalaya, close kin to Japanese natto. It smells strong and tastes savoury rather than sour.",
   "Real kinema cannot be improvised. This uses crumbled tofu for texture and leans on the mustard oil and chilli for character; it is a version, not the thing itself."],
  [("Fry the crumbled tofu in the mustard oil until browned and dry at the edges, 8 minutes.",),
   ("Add the onion, garlic, ginger and green chillies and cook until soft.",),
   ("Add the turmeric and tomato and cook down until the oil separates, about 8 minutes.",),
   ("Add 150ml water and simmer 5 minutes into a thick, spoonable curry.",),
   ("Season and finish with coriander. Serve with rice.",)],
  "Keeps 3 days refrigerated. Reheat to a full simmer.",
  []),
]
