"""Street food and chaat, the thinnest category in the collection, plus the
fried snacks and two restaurant curries that were missing."""
from add_recipes import R

E, M, A = "easy", "moderate", "advanced"
STOVE, PC, STEAM, BLEND, OVEN, KADHAI, TAWA = (
    "stovetop", "pressure-cooker", "steamer", "blender", "oven", "kadhai", "tawa")
VEG, VGN, GF, DF, NF, NOG = (
    "vegetarian", "vegan", "gluten-free", "dairy-free", "nut-free", "no-onion-garlic")

BATCH = [

R("onion-pakora", "Onion Pakora", "Punjabi",
  "shredded onion bound with gram flour and fried into crisp, irregular clusters",
  4, 15, 20, E, [STOVE, KADHAI], [VEG, VGN, GF, DF, NF], [],
  [("onion", "4 large, sliced very thin", "thin slices, not chopped: they knit together", True),
   ("besan", "150g", None, True),
   ("rice-flour", "3 tbsp", "the crispness insurance", True),
   ("green-chilli", "3, chopped", None, True),
   ("ajwain", "1 tsp", None, True),
   ("chilli-powder", "1 tsp", None, True),
   ("turmeric", "1/2 tsp", None, True),
   ("coriander-leaves", "a handful", None, False),
   ("neutral-oil", "500ml", "for deep frying", True),
   ("salt", "to taste", None, True)],
  ["Salt the onions first and let them weep. That water is the only liquid the batter needs, and it is what makes the pakora taste of onion rather than flour.",
   "Add no water at all if you can help it. A loose batter gives a soft, doughy pakora."],
  [("Slice the onions thin, salt them, and leave 15 minutes until they release water and go limp.",
    "Do not rinse or squeeze. That liquid is the batter."),
   ("Add the green chilli, ajwain, chilli powder, turmeric and coriander and mix with your hands.",),
   ("Scatter the besan and rice flour over and bring it together into a thick, barely-holding mass.",
    "It should look too dry. Resist adding water."),
   ("Heat the oil to 170C. Drop in irregular clumps with your fingers, not neat balls.",
    "Irregular shapes give the spiky edges that go crispest."),
   ("Fry 4 minutes until pale gold, lift out and rest 5 minutes.",),
   ("Return them to oil raised to 190C for 1 minute to crisp. Drain and salt.",
    "The double fry is what keeps them crisp for more than two minutes."),
   ("Serve with mint chutney and hot tea.",)],
  "Eat within the hour. They soften as they sit and reheat only passably in a hot oven. Never refrigerate, they go leathery.",
  []),

R("mixed-vegetable-pakora", "Mixed Vegetable Pakora", "Punjabi",
  "whatever is in the vegetable drawer, battered in gram flour and fried",
  4, 20, 25, E, [STOVE, KADHAI], [VEG, VGN, GF, DF, NF], [],
  [("potato", "2, sliced 3mm thick", None, True),
   ("onion", "2, sliced", None, True),
   ("cauliflower", "150g, small florets", None, False),
   ("spinach", "a handful of whole leaves", None, False),
   ("capsicum", "1, in rings", None, False),
   ("besan", "200g", None, True),
   ("rice-flour", "3 tbsp", None, True),
   ("ajwain", "1 tsp", None, True),
   ("chilli-powder", "1.5 tsp", None, True),
   ("turmeric", "1/2 tsp", None, True),
   ("baking-soda", "a pinch", "opens the batter slightly", False),
   ("neutral-oil", "600ml", "for deep frying", True),
   ("salt", "to taste", None, True)],
  ["Cut everything to a thickness that cooks in the time the batter takes to colour. Potato 3mm, cauliflower in small florets, leaves whole.",
   "The batter should coat the back of a spoon and drip slowly. Too thick and you are eating fried batter."],
  [("Whisk the besan, rice flour, spices, salt and baking soda with enough cold water to make a batter that coats a spoon.",
    "Cold water. It keeps the batter from absorbing oil."),
   ("Rest the batter 10 minutes, then check the consistency again; it thickens as it stands.",),
   ("Heat the oil to 175C. Dip each piece, let the excess run off, and lower it in.",),
   ("Fry in small batches so the oil temperature holds. Crowding the pan is what makes pakora greasy.",
    "Watch the oil, not the clock. If it stops bubbling briskly, wait before the next batch."),
   ("Cook 4 minutes until gold, drain on a rack rather than paper so the underside stays crisp.",),
   ("Salt while hot and serve with chutney.",)],
  "Eat immediately. Fried vegetables lose their point within the hour and cannot be revived properly.",
  []),

R("bread-pakora", "Bread Pakora", "Punjabi",
  "bread stuffed with spiced potato, dipped in gram flour batter and fried",
  4, 20, 20, E, [STOVE, KADHAI], [VEG, VGN, DF, NF], ["gluten"],
  [("bread", "8 slices, a day old", "day-old bread absorbs less oil", True),
   ("potato", "400g, boiled and crushed", None, True),
   ("besan", "180g", None, True),
   ("green-chilli", "2, chopped", None, True),
   ("ginger", "1 tsp, grated", None, True),
   ("amchur", "1 tsp", None, True),
   ("chaat-masala", "1 tsp", None, True),
   ("turmeric", "1/2 tsp", None, True),
   ("chilli-powder", "1 tsp", None, True),
   ("coriander-leaves", "a handful", None, False),
   ("neutral-oil", "600ml", "for deep frying", True),
   ("salt", "to taste", None, True)],
  ["Use bread that has dried a little. Fresh soft bread drinks oil and collapses.",
   "Press the sandwich firmly before battering so the filling does not escape into the pan."],
  [("Mix the crushed potato with chilli, ginger, amchur, chaat masala, coriander and salt.",),
   ("Spread thickly on four slices, top with the rest and press down hard. Cut each into two triangles.",),
   ("Whisk the besan with turmeric, chilli powder, salt and water into a batter thick enough to cling.",
    "Thicker than a pakora batter. It has to seal the cut edges."),
   ("Heat the oil to 175C. Dip each triangle, making sure the cut sides are covered, and lower it in.",),
   ("Fry 3 minutes a side until deep gold and crisp.",),
   ("Drain, cut once more if you like, dust with chaat masala and serve with tamarind chutney.",)],
  "Eat straight away. These go soggy faster than any other fried snack.",
  []),

R("aloo-tikki", "Aloo Tikki", "Punjabi",
  "shallow-fried potato patties, crisp outside and soft within",
  4, 20, 25, E, [STOVE, TAWA], [VEG, VGN, GF, DF, NF], [],
  [("potato", "700g, boiled the day before and grated", "cold, dry potato is the whole trick", True),
   ("cornflour", "3 tbsp", None, True),
   ("green-chilli", "2, chopped", None, True),
   ("ginger", "1 tbsp, grated", None, True),
   ("cumin-powder", "1 tsp", None, True),
   ("coriander-powder", "1 tsp", None, True),
   ("amchur", "1 tsp", None, True),
   ("chaat-masala", "1 tsp", None, True),
   ("coriander-leaves", "a handful", None, False),
   ("neutral-oil", "6 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["Boil the potatoes a day ahead and refrigerate them unpeeled. Warm or freshly boiled potato holds water and the tikki spreads in the pan.",
   "Grate rather than mash. Mashing develops starch and gives a gluey patty."],
  [("Grate the cold potatoes coarsely. Do not mash.",),
   ("Mix in the cornflour, chilli, ginger, ground spices, coriander and salt with a light hand.",
    "Work it as little as possible."),
   ("Shape into 8 patties about 2cm thick and chill 20 minutes.",
    "Chilling firms them so they hold in the pan."),
   ("Heat oil on a tawa over medium heat and lay the tikkis in without crowding.",),
   ("Cook 5 minutes a side without moving them. Turn once only.",
    "Moving them early tears the crust that is forming."),
   ("Press gently at the end to crisp the edges, dust with chaat masala and serve with both chutneys.",)],
  "Best hot. The shaped raw patties keep 2 days refrigerated and fry better cold; cooked tikkis reheat well in a dry pan.",
  []),

R("aloo-chaat", "Aloo Chaat", "Punjabi",
  "fried potato cubes tossed with chaat masala, tamarind and lemon",
  4, 10, 20, E, [STOVE, KADHAI], [VEG, VGN, GF, DF, NF], [],
  [("potato", "600g, boiled, cooled and cubed", None, True),
   ("chaat-masala", "2 tsp", None, True),
   ("black-salt", "1 tsp", None, True),
   ("cumin-powder", "1 tsp, roasted", None, True),
   ("chilli-powder", "1 tsp", None, True),
   ("amchur", "1 tsp", None, False),
   ("lemon", "1", None, True),
   ("tamarind", "3 tbsp thick extract", None, True),
   ("green-chilli", "2, chopped", None, False),
   ("coriander-leaves", "a large handful", None, True),
   ("neutral-oil", "4 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["The potato must be fried hard enough to develop a crust. Boiled potato tossed in spice is a salad, not a chaat.",
   "Dress it at the last second. Chaat that has sat is limp chaat."],
  [("Boil the potatoes until just tender, cool completely, and cut into 2cm cubes.",
    "Cooled potato fries; hot potato steams and breaks."),
   ("Fry the cubes in hot oil, in batches, until the outsides are properly crisp and brown, about 6 minutes.",),
   ("Drain on a rack and let them stop steaming.",),
   ("Toss while still hot with chaat masala, black salt, roasted cumin, chilli powder and amchur.",),
   ("Add the tamarind extract, lemon juice, green chilli and coriander, and toss once more.",
    "Once. Over-tossing knocks the crust off."),
   ("Serve immediately, in a bowl, with a spoon.",)],
  "Has to be eaten within minutes. There is no way to store dressed chaat.",
  []),

R("papdi-chaat", "Papdi Chaat", "Punjabi",
  "crisp flour discs under yogurt, potato, chickpeas and two chutneys",
  4, 30, 25, M, [STOVE, KADHAI], [VEG, NF], ["gluten", "dairy"],
  [("maida", "200g", "for the papdi", True),
   ("ajwain", "1 tsp", None, True),
   ("potato", "300g, boiled and cubed small", None, True),
   ("chickpeas", "200g, cooked", None, True),
   ("yogurt", "400g, whisked smooth and chilled", None, True),
   ("tamarind", "5 tbsp thick sweet extract", None, True),
   ("mint", "a large handful", "for the green chutney", True),
   ("coriander-leaves", "a large handful", None, True),
   ("green-chilli", "2", None, True),
   ("chaat-masala", "2 tsp", None, True),
   ("black-salt", "1 tsp", None, True),
   ("cumin-powder", "1 tsp, roasted", None, True),
   ("chilli-powder", "1 tsp", None, True),
   ("besan", "60g", "for the sev", False),
   ("neutral-oil", "500ml", "for deep frying", True),
   ("salt", "to taste", None, True)],
  ["Everything is assembled at the table, in this order: papdi, then potato and chana, then yogurt, then chutneys, then spice, then sev.",
   "The yogurt must be cold and the papdi crisp. Warm yogurt on warm papdi is a paste."],
  [("Make a stiff dough from maida, ajwain, 2 tbsp oil and cold water. Rest 20 minutes.",),
   ("Roll thin, cut 4cm discs, prick each all over with a fork, and fry at 160C until hard and pale, 4 minutes.",
    "Pricking stops them puffing into puris."),
   ("Blend the mint, coriander, green chilli, a little salt and lemon into a thick green chutney.",),
   ("Whisk the yogurt with a pinch of salt and sugar until pourable, and chill it.",),
   ("Arrange the papdi on a plate, scatter over the potato and chickpeas.",),
   ("Spoon the cold yogurt over, then the tamarind chutney and the green chutney.",),
   ("Dust with chaat masala, black salt, roasted cumin and chilli powder, and finish with sev.",
    "Serve the second it is assembled. Papdi goes soft in about ninety seconds.")],
  "The papdi keep two weeks in an airtight tin and the chutneys a week refrigerated. Assembled chaat cannot be kept at all.",
  []),

R("dahi-puri", "Dahi Puri", "Maharashtrian",
  "hollow puris filled with potato and chilled sweet yogurt",
  4, 25, 15, M, [STOVE, KADHAI], [VEG, NF], ["gluten", "dairy"],
  [("rava", "150g", "for the puris", True),
   ("maida", "3 tbsp", None, True),
   ("potato", "300g, boiled and crushed fine", None, True),
   ("yogurt", "500g, whisked, sweetened and chilled", None, True),
   ("tamarind", "5 tbsp sweet extract", None, True),
   ("mint", "a handful", None, True),
   ("coriander-leaves", "a handful", None, True),
   ("green-chilli", "2", None, True),
   ("chaat-masala", "2 tsp", None, True),
   ("black-salt", "1 tsp", None, True),
   ("cumin-powder", "1 tsp, roasted", None, True),
   ("besan", "50g", "for sev", False),
   ("pomegranate", "3 tbsp seeds", None, False),
   ("neutral-oil", "500ml", "for deep frying", True),
   ("salt", "to taste", None, True)],
  ["The puris are the same shells as pani puri, so if you are buying them, buy once and make both.",
   "Sweeten the yogurt. Plain sour yogurt fights the tamarind instead of balancing it."],
  [("Make a stiff dough of rava, maida, salt and water. Knead well and rest 30 minutes under a damp cloth.",),
   ("Roll very thin and cut 4cm discs. Fry at 190C, pressing each with a slotted spoon until it balloons, then crisp it.",
    "Hot oil and thin rolling. Either one wrong and they will not puff."),
   ("Cool the shells completely. Crack a small hole in the top of each.",),
   ("Season the crushed potato with a little chaat masala and salt, and fill each puri.",),
   ("Whisk the yogurt with sugar and a pinch of salt until pourable and thoroughly chilled.",),
   ("Spoon the cold yogurt over the filled puris, then tamarind and green chutney.",),
   ("Finish with roasted cumin, black salt, sev and pomegranate. Eat at once.",)],
  "Unfilled shells keep two weeks airtight. Once the yogurt goes on you have about a minute.",
  []),

R("pani-puri", "Pani Puri / Golgappa", "Maharashtrian",
  "hollow crisp shells filled with spiced mint water and drunk whole",
  4, 30, 20, A, [STOVE, KADHAI, BLEND], [VEG, VGN, DF, NF], ["gluten"],
  [("rava", "150g", None, True),
   ("maida", "3 tbsp", None, True),
   ("mint", "a very large handful", "the pani is mostly mint, so be generous", True),
   ("coriander-leaves", "a large handful", None, True),
   ("green-chilli", "3", None, True),
   ("ginger", "2cm piece", None, True),
   ("tamarind", "4 tbsp extract", None, True),
   ("black-salt", "2 tsp", "the flavour that makes pani taste like pani", True),
   ("cumin-powder", "2 tsp, roasted", None, True),
   ("chaat-masala", "1 tsp", None, True),
   ("potato", "200g, boiled and crushed", None, True),
   ("chickpeas", "150g, cooked", None, False),
   ("neutral-oil", "500ml", "for deep frying", True),
   ("salt", "to taste", None, True)],
  ["Two things decide whether the shells puff: the dough must be stiff and rested, and the oil must be genuinely hot.",
   "Make the pani hours ahead and chill it hard. Warm pani is unpleasant and the flavours have not married."],
  [("Knead a stiff dough from rava, maida, salt and just enough water. Cover with a damp cloth and rest 30 minutes.",
    "Stiff. A soft dough gives flat, oily discs."),
   ("Blend the mint, coriander, chilli and ginger with a little water to a fine paste.",),
   ("Stir the paste into 1.2 litres cold water with the tamarind, black salt, roasted cumin, chaat masala and salt. Chill at least 2 hours.",
    "Taste it cold. Chilling flattens salt, so it needs more than seems right when warm."),
   ("Roll the dough very thin and cut small discs, keeping them under a cloth so they do not dry.",),
   ("Fry a few at a time at 190C, holding each under with a slotted spoon until it balloons, then turning to crisp.",
    "If they are not puffing, the oil is too cool or the dough too thick."),
   ("Drain and cool completely. They must be bone dry to stay crisp.",),
   ("At the table, crack a hole in each shell, add potato and chana, fill with cold pani and eat whole, immediately.",)],
  "Shells keep two weeks in an airtight tin. The pani keeps 3 days refrigerated and improves overnight. Never store them together.",
  ["resting-dough"]),

R("bhel-puri", "Bhel Puri", "Maharashtrian",
  "puffed rice tossed with onion, tomato, chutneys and sev, assembled in seconds",
  4, 15, 0, E, [], [VEG, VGN, GF, DF, NF], [],
  [("murmura", "150g puffed rice", None, True),
   ("onion", "1, very finely chopped", None, True),
   ("tomato", "1, deseeded and finely chopped", "deseeded, or the bhel goes wet", True),
   ("potato", "150g, boiled and diced small", None, False),
   ("tamarind", "5 tbsp sweet extract", None, True),
   ("mint", "a handful", None, True),
   ("coriander-leaves", "a large handful", None, True),
   ("green-chilli", "2", None, True),
   ("besan", "60g", "for sev", True),
   ("chaat-masala", "2 tsp", None, True),
   ("black-salt", "1 tsp", None, True),
   ("lemon", "1", None, True),
   ("raw-mango", "2 tbsp, diced", None, False),
   ("neutral-oil", "400ml", "for frying the sev", True),
   ("salt", "to taste", None, True)],
  ["Bhel has no cooking. It has assembly, and the entire skill is doing it fast and serving it faster.",
   "Dry-roast the puffed rice for two minutes before you start. It is almost always slightly stale."],
  [("Dry-roast the murmura in a wide pan over low heat for 2 minutes until it smells toasted. Cool.",
    "This is what separates good bhel from cardboard."),
   ("Blend mint, coriander and green chilli with a splash of water into a thick green chutney.",),
   ("Push a stiff besan batter through a sev press into hot oil and fry until crisp, or use bought sev.",),
   ("Put the murmura in a wide bowl with the onion, tomato, potato and raw mango.",),
   ("Add both chutneys, the chaat masala, black salt and lemon juice, and toss hard for 10 seconds.",
    "Ten seconds. Longer and the puffed rice starts to soften."),
   ("Top with sev and coriander and serve immediately, in paper cones if you have them.",)],
  "Cannot be stored once mixed; it is soggy within two minutes. Keep the components separate and assemble to order.",
  []),

R("sev-puri", "Sev Puri", "Maharashtrian",
  "flat crisp puris loaded with potato, chutneys and a mound of fine sev",
  4, 20, 15, E, [STOVE, KADHAI], [VEG, VGN, DF, NF], ["gluten"],
  [("maida", "200g", "for the flat puris", True),
   ("potato", "300g, boiled and diced small", None, True),
   ("onion", "1, finely chopped", None, True),
   ("besan", "100g", "for sev", True),
   ("tamarind", "5 tbsp sweet extract", None, True),
   ("mint", "a large handful", None, True),
   ("coriander-leaves", "a large handful", None, True),
   ("green-chilli", "2", None, True),
   ("chaat-masala", "2 tsp", None, True),
   ("black-salt", "1 tsp", None, True),
   ("chilli-powder", "1 tsp", None, True),
   ("lemon", "1", None, True),
   ("neutral-oil", "500ml", "for deep frying", True),
   ("salt", "to taste", None, True)],
  ["Sev puri uses the flat papdi, not the hollow shell. Pricking the discs before frying is what keeps them flat.",
   "The sev should be fine, not thick. Thick sev turns the dish chewy."],
  [("Make a stiff maida dough with 2 tbsp oil and cold water. Rest 20 minutes.",),
   ("Roll thin, cut 5cm discs, prick all over, and fry at 160C until hard and barely coloured.",),
   ("Blend mint, coriander, chilli and lemon into a thick green chutney.",),
   ("Fry fine sev from a stiff besan batter, or use bought.",),
   ("Lay the puris out, top each with potato and onion.",),
   ("Spoon on tamarind chutney and green chutney, dust with chaat masala, black salt and chilli powder.",),
   ("Bury the lot in sev and serve at once.",
    "Sev last, and generously. It is the name of the dish.")],
  "Puris and sev keep two weeks airtight. Assembled, they last about a minute.",
  []),

R("ragda-pattice", "Ragda Pattice", "Maharashtrian",
  "potato patties drowned in a thin white pea curry with chutneys on top",
  4, 30, 45, M, [STOVE, PC, TAWA], [VEG, VGN, GF, DF, NF], [],
  [("dried-peas", "250g white peas, soaked overnight", None, True),
   ("potato", "700g, boiled and grated", None, True),
   ("cornflour", "3 tbsp", None, True),
   ("onion", "1, finely chopped", None, True),
   ("tamarind", "4 tbsp sweet extract", None, True),
   ("mint", "a handful", None, True),
   ("coriander-leaves", "a large handful", None, True),
   ("green-chilli", "3", None, True),
   ("ginger", "1 tbsp, grated", None, True),
   ("turmeric", "1 tsp", None, True),
   ("chilli-powder", "1 tsp", None, True),
   ("chaat-masala", "2 tsp", None, True),
   ("cumin-seeds", "1 tsp", None, True),
   ("neutral-oil", "6 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["The ragda should be thin enough to pour, not a thick curry. It is a sauce for the pattice, not a dal.",
   "Crush a ladle of the cooked peas against the pan to thicken it rather than adding flour."],
  [("Pressure cook the soaked peas with turmeric and salt for 5 whistles until completely soft.",),
   ("Temper cumin in oil, add ginger and chilli, then tip in the peas with their liquid.",),
   ("Crush a ladleful against the side of the pan and simmer 10 minutes to a pouring consistency.",
    "Pouring, not spooning. Add hot water if it tightens."),
   ("Mix the grated potato with cornflour, chaat masala and salt, and shape into 8 patties.",),
   ("Shallow-fry the pattice on a tawa, 5 minutes a side, until a hard crust forms.",),
   ("Put two pattice in each bowl and ladle the hot ragda over them.",),
   ("Top with chopped onion, both chutneys, chaat masala and coriander.",)],
  "The ragda keeps 3 days refrigerated and thickens; loosen with hot water. Pattice are best fresh but the raw shaped patties keep 2 days.",
  []),

R("dabeli", "Dabeli", "Gujarati",
  "a spiced potato bun from Kutch, pressed on a griddle and edged with sev and pomegranate",
  4, 25, 20, M, [STOVE, TAWA], [VEG], ["gluten", "dairy", "nuts"],
  [("pav", "8 rolls", None, True),
   ("potato", "500g, boiled and mashed", None, True),
   ("coriander-powder", "2 tsp", "with the cinnamon and clove below, this is dabeli masala", True),
   ("chilli-powder", "1.5 tsp", None, True),
   ("cinnamon", "1/2 tsp ground", None, True),
   ("cloves", "1/4 tsp ground", None, True),
   ("tamarind", "4 tbsp sweet extract", None, True),
   ("jaggery", "2 tbsp", None, True),
   ("peanut", "80g, roasted", None, True),
   ("pomegranate", "4 tbsp seeds", None, True),
   ("onion", "1, finely chopped", None, True),
   ("besan", "60g", "for sev", True),
   ("butter", "4 tbsp", None, True),
   ("coriander-leaves", "a handful", None, False),
   ("neutral-oil", "400ml", "for frying the sev", True),
   ("salt", "to taste", None, True)],
  ["Dabeli means pressed, and that is the technique: the filled bun is pressed hard on a buttered griddle until the outside crisps.",
   "The filling should be sweet, sour and hot at once. If it tastes of only one of those, it is not finished."],
  [("Mix the ground spices with the tamarind and jaggery into a thick paste.",),
   ("Fold this through the mashed potato with salt until evenly coloured, and spread it flat on a plate.",),
   ("Press pomegranate seeds, roasted peanuts and coriander over the surface.",
    "Pressed into the surface, not stirred through. You want them in every bite of the cut face."),
   ("Slit the pav without cutting through, spread a little tamarind chutney inside, and fill generously.",),
   ("Roll the open edges in sev so the filling face is crusted.",),
   ("Griddle in butter, pressing down firmly with a spatula, until both faces are crisp and golden.",),
   ("Serve hot with more sev, chopped onion and roasted peanuts alongside.",)],
  "Best hot off the griddle. The filling keeps 2 days refrigerated and is arguably better on day two; assemble to order.",
  []),

R("kathi-roll", "Kathi Roll", "Bengali",
  "an egg-coated paratha wrapped around spiced vegetables and onion",
  4, 25, 30, M, [TAWA, STOVE], [VEG, NF], ["gluten", "dairy"],
  [("maida", "300g", None, True),
   ("eggs", "3", None, True),
   ("paneer", "250g, in fingers", None, True),
   ("capsicum", "1, sliced", None, True),
   ("onion", "2, sliced, half for the filling and half raw", None, True),
   ("yogurt", "3 tbsp", None, True),
   ("ginger", "1 tbsp paste", None, True),
   ("garlic", "1 tbsp paste", None, True),
   ("garam-masala", "1 tsp", None, True),
   ("chilli-powder", "1.5 tsp", None, True),
   ("chaat-masala", "1 tsp", None, True),
   ("lemon", "1", None, True),
   ("green-chilli", "2, chopped", None, False),
   ("neutral-oil", "5 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["The egg is cooked onto the paratha, not scrambled into the filling. That layer is what holds the roll together.",
   "Raw onion and lemon at the end are not a garnish. Without them the roll is heavy."],
  [("Make a soft maida dough with a little oil and water, and rest it 30 minutes.",),
   ("Marinate the paneer in yogurt, ginger, garlic, chilli powder and salt for 20 minutes, then sear it hard with the capsicum.",),
   ("Roll the dough into thin parathas and cook on a tawa with a little oil until just done.",),
   ("Beat an egg with salt, pour it onto the tawa and lay the cooked paratha on top, pressing so it sticks. Flip after a minute.",
    "Paratha onto egg, not egg onto paratha. It bonds cleanly that way."),
   ("Lay the filling along one edge, add raw onion, lemon juice, chaat masala and green chilli.",),
   ("Roll tight, wrap the base in paper, and eat standing up.",)],
  "Eat immediately. The parathas keep a day and the filling two, but a rolled kathi roll goes soft within minutes.",
  ["resting-dough"]),

R("chicken-kathi-roll", "Chicken Kathi Roll", "Bengali",
  "the Calcutta original: egg paratha rolled around spiced chicken and raw onion",
  4, 30, 35, M, [TAWA, STOVE], [NF], ["gluten", "dairy"],
  [("maida", "300g", None, True),
   ("chicken", "500g boneless thigh, in strips", None, True),
   ("eggs", "4", None, True),
   ("yogurt", "150g", None, True),
   ("onion", "3, half for cooking and half sliced raw", None, True),
   ("ginger", "1 tbsp paste", None, True),
   ("garlic", "1 tbsp paste", None, True),
   ("chilli-powder", "2 tsp", None, True),
   ("turmeric", "1/2 tsp", None, True),
   ("garam-masala", "1 tsp", None, True),
   ("chaat-masala", "1.5 tsp", None, True),
   ("green-chilli", "3, chopped", None, True),
   ("lemon", "2", None, True),
   ("neutral-oil", "6 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["The roll was invented for eating on the move, so it is built to hold: egg layer, dry filling, tight wrap.",
   "Keep the chicken dry. A wet filling turns the paratha to pulp before you finish it."],
  [("Marinate the chicken strips in yogurt, ginger, garlic, chilli powder, turmeric and salt for at least 2 hours.",),
   ("Make a soft maida dough with oil and water; rest 30 minutes.",),
   ("Cook the chicken over high heat until the liquid has gone completely and the edges char, about 10 minutes.",
    "Cook it dry. This is the single most important step."),
   ("Roll and griddle the parathas until just cooked, keeping them soft.",),
   ("Beat an egg, pour onto the tawa, press a paratha onto it, and flip after a minute.",),
   ("Lay chicken along the edge with plenty of raw onion, green chilli, chaat masala and a hard squeeze of lemon.",),
   ("Roll tight, wrap in paper and serve at once.",)],
  "Eat immediately. Cooked filling keeps 2 days refrigerated; dough keeps a day. Never assemble ahead.",
  ["resting-dough"]),

R("kadai-chicken", "Kadai Chicken", "Punjabi",
  "chicken with peppers in a coarse pounded coriander and chilli masala",
  4, 20, 35, M, [STOVE, KADHAI], [GF, DF, NF], [],
  [("chicken", "800g bone-in pieces", None, True),
   ("capsicum", "2, in 3cm squares", None, True),
   ("onion", "2, in petals", None, True),
   ("tomato", "400g, chopped", None, True),
   ("coriander-powder", "2 tbsp, coarsely pounded", None, True),
   ("dried-red-chilli", "5, pounded with the coriander", None, True),
   ("ginger", "2 tbsp, half paste half julienne", None, True),
   ("garlic", "1 tbsp paste", None, True),
   ("kasuri-methi", "1 tbsp", None, True),
   ("garam-masala", "1/2 tsp", None, True),
   ("coriander-leaves", "a handful", None, False),
   ("neutral-oil", "4 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["Kadai masala is pounded coarse from whole coriander and dried chilli. Ready-ground powder gives a different, flatter dish.",
   "Semi-dry is correct. If it is swimming, cook it down."],
  [("Dry-roast the coriander seed and dried chillies until fragrant, cool, and pound coarse.",),
   ("Sear the capsicum and onion petals on high for 2 minutes so they blister but stay firm. Lift out.",),
   ("Brown the chicken in the same pan, then add the ginger paste and garlic.",),
   ("Add the tomato and two-thirds of the pounded masala, cover, and cook 20 minutes until the chicken is done and the oil separates.",),
   ("Return the peppers and onion, add the rest of the masala, and toss on high for 3 minutes.",
    "High heat at the end drives off the last of the liquid."),
   ("Finish with kasuri methi, garam masala, ginger julienne and coriander.",)],
  "Keeps 2 days refrigerated. The peppers soften overnight, which is a loss but not a disaster. Reheat hard and fast.",
  ["kadhai", "bhuna"]),

R("navratan-korma", "Navratan Korma", "Awadhi/Lucknowi",
  "nine jewels: mixed vegetables, paneer, nuts and fruit in a pale sweet cream gravy",
  6, 30, 35, M, [STOVE, KADHAI, BLEND], [VEG, GF], ["dairy", "nuts"],
  [("carrot", "150g, diced", None, True),
   ("french-beans", "100g, cut small", None, True),
   ("peas", "100g", None, True),
   ("cauliflower", "150g, small florets", None, True),
   ("potato", "150g, diced", None, True),
   ("paneer", "200g, cubed", None, True),
   ("cashew", "80g, soaked", None, True),
   ("almonds", "30g, blanched", None, True),
   ("raisins", "3 tbsp", None, True),
   ("pomegranate", "3 tbsp seeds, to finish", None, False),
   ("onion", "2, quartered", None, True),
   ("cream", "100ml", None, True),
   ("milk", "150ml", None, True),
   ("ginger", "1 tbsp", None, True),
   ("cardamom", "5", None, True),
   ("garam-masala", "1 tsp", None, True),
   ("sugar", "2 tsp", None, True),
   ("ghee", "4 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["Navratan means nine gems, and the count is the point: vegetables, paneer, nuts and dried fruit should all be identifiable.",
   "No tomato and no chilli powder. The gravy is deliberately pale and mild; heat belongs in a different dish."],
  [("Boil the onion, ginger, cardamom and soaked cashews in 200ml water for 12 minutes, then blend to a smooth white paste.",),
   ("Blanch the carrot, beans, cauliflower and potato until just tender and refresh in cold water so they keep their colour.",
    "Refreshing matters. Vegetables left to sit hot go grey."),
   ("Fry the paneer cubes in ghee until pale gold and set aside.",),
   ("Cook the white paste in the remaining ghee for 8 minutes without letting it colour.",
    "It must not brown. The colour of this dish is its signature."),
   ("Add the milk, sugar and salt, and simmer to a coating consistency.",),
   ("Fold in the vegetables, paneer, almonds and raisins and warm through for 4 minutes.",),
   ("Finish off the heat with the cream and garam masala, and scatter pomegranate over.",)],
  "Keeps 2 days refrigerated. The cream can split on hard reheating, so warm it gently. Do not freeze.",
  []),
]
