"""Andhra and Anglo-Indian, the two thinnest regions in the collection.

Andhra had 12 recipes and no vepudu at all, which is half of how the state
eats: a pulusu (tamarind curry) and a vepudu (dry fry) on the same plate.
Anglo-Indian had 8, which is not a cuisine, it is a sample.
"""
from add_recipes import R

E, M, A = "easy", "moderate", "advanced"
STOVE, PC, STEAM, BLEND, OVEN, KADHAI, TAWA = (
    "stovetop", "pressure-cooker", "steamer", "blender", "oven", "kadhai", "tawa")
VEG, VGN, GF, DF, NF, NOG = (
    "vegetarian", "vegan", "gluten-free", "dairy-free", "nut-free", "no-onion-garlic")

BATCH = [

# ---------------------------------------------------------------- Andhra

R("gongura-mamsam", "Gongura Mamsam", "Andhra",
  "mutton braised with sour sorrel leaves, the dish Andhra is judged by",
  4, 20, 70, M, [STOVE, PC], [GF, DF, NF], [],
  [("mutton", "700g on the bone, 4cm pieces", "bone matters here, the gravy is thin without it", True),
   ("amaranth-greens", "300g leaves", "standing in for gongura (sorrel); if you find gongura use it and cut the tamarind by half", True),
   ("tamarind", "20g", "only to make up the sourness the substitute lacks", True),
   ("onion", "3 medium, finely sliced", None, True),
   ("dried-red-chilli", "8", "Guntur if you can get them", True),
   ("ginger", "1 tbsp paste", None, True),
   ("garlic", "1 tbsp paste", None, True),
   ("turmeric", "1/2 tsp", None, True),
   ("coriander-powder", "2 tsp", None, True),
   ("neutral-oil", "5 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["The greens go in twice. Half early, to melt into the gravy, half at the end so something still tastes green.",
   "Gongura is aggressively sour. If you are using amaranth, the tamarind is doing the work the leaf would."],
  [("Wilt the greens in a dry pan until they collapse and give up their water, about 5 minutes. Set aside.",
    "No oil. You want them dry, not fried."),
   ("Brown the onion in the oil until properly dark. Add the ginger and garlic pastes and cook out the raw smell.",),
   ("Add the mutton, turmeric, coriander powder and chillies. Fry on high until the meat is sealed and colouring.",
    "Do not add salt yet, it draws water and stews the meat."),
   ("Add 250ml water and the tamarind, cover and cook 50 minutes until the mutton yields, or 5 whistles in a pressure cooker.",),
   ("Stir in half the wilted greens and simmer uncovered 10 minutes until the gravy tightens around the meat.",),
   ("Fold in the rest of the greens, salt to taste, and rest 10 minutes before serving with rice.",)],
  "Keeps 3 days refrigerated and improves overnight as the sourness settles into the meat. Reheat gently with a splash of water. Freezes well for a month.",
  []),

R("kodi-vepudu", "Kodi Vepudu", "Andhra",
  "chicken fried dry with curry leaves and pepper until the masala clings to the bone",
  4, 15, 35, E, [STOVE, KADHAI], [GF, DF, NF], [],
  [("chicken", "700g on the bone, small pieces", "small pieces, this is eaten with fingers", True),
   ("onion", "2 medium, finely sliced", None, True),
   ("curry-leaves", "3 sprigs", None, True),
   ("dried-red-chilli", "6", None, True),
   ("black-pepper", "1.5 tsp, coarsely crushed", "crushed, not powdered, you want to meet it", True),
   ("ginger", "1 tbsp paste", None, True),
   ("garlic", "1 tbsp paste", None, True),
   ("turmeric", "1/2 tsp", None, True),
   ("chilli-powder", "1 tsp", None, True),
   ("neutral-oil", "4 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["Vepudu means fry. There is no gravy at the end and there should not be.",
   "Rub the chicken with the turmeric and salt and refrigerate 20 minutes while you slice the onion."],
  [("Heat the oil, splutter the dried chillies and one sprig of curry leaves, then add the onion and fry until golden.",),
   ("Add the ginger and garlic pastes, cook 2 minutes, then the chicken and chilli powder. Fry on high 5 minutes.",),
   ("Cover and cook 15 minutes on low. The chicken releases its own water and cooks in it.",
    "No added water at any point."),
   ("Uncover, raise the heat and fry until every drop has gone and the masala is stuck to the meat, about 10 minutes.",
    "This is the whole dish. Stop too early and it is a curry."),
   ("Add the crushed pepper and the remaining curry leaves, toss 2 minutes, and serve.",)],
  "Keeps 2 days refrigerated. Reheat dry in a pan rather than a microwave, which softens the crust you just built.",
  []),

R("chepa-vepudu", "Chepa Vepudu", "Andhra",
  "fish steaks rubbed with chilli and shallow fried until the edges crisp",
  4, 20, 15, E, [STOVE, TAWA], [GF, DF, NF], ["fish"],
  [("fish", "600g steaks, 2cm thick", "a firm fish; soft fillets break up", True),
   ("chilli-powder", "2 tsp", None, True),
   ("turmeric", "1 tsp", None, True),
   ("ginger", "1 tbsp paste", None, True),
   ("garlic", "1 tbsp paste", None, True),
   ("lemon", "1", None, True),
   ("rice-flour", "3 tbsp", "the crust; without it the spice slides off in the pan", True),
   ("curry-leaves", "2 sprigs", None, True),
   ("neutral-oil", "6 tbsp, for shallow frying", None, True),
   ("salt", "to taste", None, True)],
  ["Rub the fish with the turmeric, salt, chilli, ginger, garlic and lemon juice, then cover and refrigerate 30 minutes.",
   "Pat the pieces dry before they touch the oil. Wet fish steams instead of frying."],
  [("Toss the marinated fish in the rice flour so each piece carries a thin, even coat.",),
   ("Heat the oil until a pinch of flour sizzles at once. Lay the fish in without crowding the pan.",
    "Crowding drops the temperature and you get grey fish."),
   ("Fry 4 minutes without moving it. Turn once, add the curry leaves to the oil, and fry 3 minutes more.",
    "Turning it repeatedly is how the crust ends up in the pan instead of on the fish."),
   ("Drain on paper, squeeze over the rest of the lemon and serve hot with rice and a pulusu.",)],
  "Best within the hour. It keeps a day refrigerated but the crust goes soft; crisp it briefly in a dry pan rather than a microwave.",
  []),

R("royyala-vepudu", "Royyala Vepudu", "Andhra",
  "prawns tossed dry with onion, curry leaf and a lot of chilli",
  4, 20, 15, E, [STOVE, KADHAI], [GF, DF, NF], ["crustacean"],
  [("prawns", "500g, peeled and deveined", None, True),
   ("onion", "2 medium, finely chopped", None, True),
   ("curry-leaves", "3 sprigs", None, True),
   ("chilli-powder", "2 tsp", None, True),
   ("turmeric", "1/2 tsp", None, True),
   ("coriander-powder", "1 tsp", None, True),
   ("ginger", "1 tbsp paste", None, True),
   ("garlic", "1 tbsp paste", None, True),
   ("neutral-oil", "4 tbsp", None, True),
   ("coriander-leaves", "a handful", None, False),
   ("salt", "to taste", None, True)],
  ["Prawns take four minutes and not a minute more. Have everything else finished before they go in.",
   "Toss the prawns with the turmeric and salt and refrigerate 15 minutes while the masala cooks down."],
  [("Fry the onion in the oil until golden and soft, 8 minutes. Add the ginger and garlic and cook 2 minutes.",),
   ("Add the chilli powder, coriander powder and one sprig of curry leaves. Fry 2 minutes until the oil separates.",),
   ("Raise the heat, add the prawns and toss constantly for 4 minutes until they curl and turn opaque.",
    "They are done the moment they curl. Past that they tighten into rubber."),
   ("Add the remaining curry leaves, toss once, check the salt and finish with coriander.",)],
  "Eat the same day. Reheated prawns toughen, and the dish is dry enough that a day in the fridge does it no favours.",
  []),

R("natu-kodi-pulusu", "Natu Kodi Pulusu", "Andhra",
  "country chicken in a thin tamarind gravy, cooked long enough to matter",
  4, 20, 60, M, [STOVE, PC], [GF, DF, NF], [],
  [("chicken", "800g on the bone, large pieces", "free-range or older bird if you can, it is the point of the dish", True),
   ("tamarind", "40g, soaked in 300ml warm water", None, True),
   ("onion", "3 medium, sliced", None, True),
   ("tomato", "2, chopped", None, True),
   ("dried-red-chilli", "6", None, True),
   ("coriander-powder", "2 tsp", None, True),
   ("turmeric", "1/2 tsp", None, True),
   ("curry-leaves", "2 sprigs", None, True),
   ("neutral-oil", "5 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["Pulusu means sour. The tamarind is not a background note, it is the dish.",
   "Country chicken is tougher and better flavoured than broiler. If you use broiler, cut the cooking time by half."],
  [("Fry the onion in the oil until deep brown. Add the curry leaves and dried chillies.",),
   ("Add the chicken, turmeric and coriander powder and fry on high until the pieces colour, 8 minutes.",),
   ("Add the tomato and cook until it breaks down completely.",),
   ("Strain in the tamarind water, bring to a boil, then cover and simmer 40 minutes until the chicken is tender.",
    "It should stay thin. This is a gravy for pouring over rice, not for coating it."),
   ("Season and rest 10 minutes. The sourness rounds out as it stands.",)],
  "Keeps 3 days refrigerated and tastes better on day two. The tamarind keeps it stable. Reheat to a full simmer.",
  []),

R("menthi-kura-pappu", "Menthi Kura Pappu", "Andhra",
  "toor dal cooked with fenugreek leaves, bitter and soft and eaten every week",
  4, 15, 35, E, [STOVE, PC], [VEG, VGN, GF, DF, NF], [],
  [("toor-dal", "200g, rinsed", None, True),
   ("methi-leaves", "200g, chopped", "bitter; do not try to cook it out, it is meant to be there", True),
   ("onion", "1, chopped", None, True),
   ("tomato", "2, chopped", None, True),
   ("green-chilli", "4, slit", None, True),
   ("turmeric", "1/2 tsp", None, True),
   ("tamarind", "15g", None, True),
   ("mustard-seeds", "1 tsp", None, True),
   ("cumin-seeds", "1 tsp", None, True),
   ("dried-red-chilli", "3", None, True),
   ("garlic", "6 cloves, crushed", None, True),
   ("curry-leaves", "1 sprig", None, True),
   ("asafoetida", "a pinch", None, True),
   ("neutral-oil", "3 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["Wash the fenugreek in several changes of water. Grit hides in the leaf and there is no rescuing it later.",
   "The dal should be soft enough to smear, not soupy."],
  [("Pressure cook the dal with the turmeric, tomato, onion, green chilli and 500ml water for 4 whistles, or simmer 40 minutes.",),
   ("Stir in the fenugreek leaves and the tamarind and simmer 10 minutes uncovered until the leaves are soft.",),
   ("Mash the dal roughly against the side of the pan. Season.",
    "Roughly. A completely smooth dal loses the texture of the leaf."),
   ("Heat the oil, splutter the mustard seeds, then the cumin, dried chillies, garlic, curry leaves and asafoetida.",),
   ("Pour the tempering over the dal, stir once, and cover for 5 minutes before serving.",)],
  "Keeps 3 days refrigerated. It thickens considerably; loosen with hot water and re-season. Do not freeze, the leaves turn slimy.",
  ["tadka", "hing"]),

R("avakaya", "Avakaya", "Andhra",
  "the raw mango pickle Andhra households measure the year by",
  20, 40, 0, M, [], [VEG, VGN, GF, DF, NF], [],
  [("raw-mango", "1kg, firm and sour, cut into 3cm pieces with the shell of the stone", "the stone shell is traditional and holds the pieces together", True),
   ("chilli-powder", "200g", "a coarse, deep red pickle chilli, not the fine hot kind", True),
   ("mustard-seeds", "150g, ground to a coarse powder", "avakaya means mustard; this is the flavour", True),
   ("salt", "150g, non-iodised", "iodised salt clouds the pickle and softens the fruit", True),
   ("sesame-oil", "400ml", "Indian gingelly oil, and enough to cover", True),
   ("turmeric", "2 tbsp", None, True),
   ("fenugreek-seeds", "1 tbsp, ground", None, True),
   ("garlic", "20 cloves, peeled", None, False)],
  ["Everything must be bone dry. One drop of water and the jar spoils within a week.",
   "This is not a same-day pickle. It needs three days to come together and is better after a month."],
  [("Wipe the mango pieces with a dry cloth and spread them on a towel for an hour. There must be no moisture at all.",
    "Do not wash and use immediately. Wash the whole fruit, dry it thoroughly, then cut."),
   ("Mix the chilli powder, ground mustard, salt, turmeric and fenugreek in a wide dry bowl.",),
   ("Add half the oil and work it into a thick paste. Fold in the mango pieces and the garlic until every piece is coated.",),
   ("Pack into a dry glass or ceramic jar, pressing down to remove air pockets. Pour the remaining oil over so the surface is covered.",
    "The oil layer is the seal. If the pickle drinks it, top it up."),
   ("Close and leave three days at room temperature, turning the jar once a day, then refrigerate.",
    "Three days is the traditional cure. After that keep it cold: a jar left out all summer is a tradition, not a tested method.")],
  "Keeps 6 months refrigerated under a covering film of oil, using only a dry spoon. Traditionally kept in a cool larder for a year, but that rests on the salt and oil levels being judged by eye, which is not something this recipe can verify for your batch.",
  []),

R("perugu-vada", "Perugu Vada", "Andhra",
  "urad dal vadas soaked soft and drowned in seasoned yogurt",
  4, 30, 25, M, [STOVE, KADHAI, BLEND], [VEG, GF, NF], ["dairy"],
  [("urad-dal", "200g, soaked 4 hours", None, True),
   ("yogurt", "600g, whisked smooth", None, True),
   ("green-chilli", "3, chopped", None, True),
   ("ginger", "1 tbsp, grated", None, True),
   ("curry-leaves", "2 sprigs", None, True),
   ("mustard-seeds", "1 tsp", None, True),
   ("cumin-seeds", "1 tsp", None, True),
   ("dried-red-chilli", "2", None, True),
   ("asafoetida", "a pinch", None, True),
   ("neutral-oil", "500ml for frying", None, True),
   ("coriander-leaves", "a handful", None, False),
   ("salt", "to taste", None, True)],
  ["Grind the dal with as little water as possible. A wet batter gives flat, oily vadas.",
   "The soak in warm water after frying is what makes them spongy. Skip it and you get bread in yogurt."],
  [("Drain the dal and grind to a thick, fluffy paste, adding water a spoonful at a time. Beat it by hand for 2 minutes to aerate.",
    "A spoonful of batter dropped in water should float. If it sinks, beat it more."),
   ("Mix in the green chilli, ginger and salt. Shape into flat rounds with a hole in the middle and fry until golden.",),
   ("Drop the hot vadas into warm salted water for 10 minutes, then squeeze each one gently between your palms.",
    "Gently. You are pressing out water, not flattening them."),
   ("Season the yogurt with salt and pour it over the squeezed vadas. Refrigerate at least an hour.",),
   ("Heat 2 tbsp oil, splutter the mustard and cumin seeds with the dried chillies, curry leaves and asafoetida, and pour it over. Finish with coriander.",)],
  "Keeps 2 days refrigerated. The vadas go on drinking the yogurt, so add a few spoonfuls of fresh whisked yogurt before serving on day two.",
  ["tadka", "hing"]),

R("ragi-sangati", "Ragi Sangati", "Andhra",
  "finger millet and rice pounded into a smooth ball, the working staple of Rayalaseema",
  4, 10, 30, M, [STOVE], [VEG, VGN, GF, DF, NF], [],
  [("ragi-flour", "200g", None, True),
   ("rice", "100g, washed", "cooked soft with the millet, not separately", True),
   ("water", "1.2 litres", None, True),
   ("salt", "1/2 tsp", None, True)],
  ["Sangati is eaten with a hot, thin curry, usually natu kodi pulusu or a chilli and onion chutney. On its own it is deliberately plain.",
   "The pounding is the technique. A whisk gives lumps; a sturdy wooden spoon and some force gives the smooth, heavy texture the dish is named for."],
  [("Boil the rice in the water until completely soft and collapsing, about 20 minutes. Do not drain it.",),
   ("Lower the heat. Rain the ragi flour in with one hand while stirring hard with the other.",
    "All at once and you get a lump you will never break up."),
   ("Cook 8 minutes, stirring constantly, until it pulls away from the sides of the pan.",),
   ("Take it off the heat and pound it against the side of the pan with a wooden spoon until glossy and smooth, about 3 minutes.",),
   ("Wet your hands and shape into balls. Serve at once with a hot curry.",
    "It sets firm as it cools, so shape while hot.")],
  "Best eaten straight away. It keeps a day refrigerated but sets hard; steam it briefly to soften rather than microwaving, which dries the surface.",
  []),

R("pootharekulu", "Pootharekulu", "Andhra",
  "paper-thin rice sheets layered with ghee and sugar, the sweet that looks like parchment",
  12, 60, 30, A, [STOVE, TAWA], [VEG, GF, NF], ["dairy"],
  [("rice", "300g, soaked 6 hours", None, True),
   ("sugar", "200g, ground fine", None, True),
   ("ghee", "150g, melted", None, True),
   ("cardamom", "8 pods, seeds ground", None, True),
   ("cashew", "50g, finely chopped", None, False),
   ("water", "as needed for the batter", None, True)],
  ["This is the hardest sweet in the collection and the reason is the sheet: it has to be thin enough to read through.",
   "The traditional method lifts the film off an inverted clay pot. A heavy non-stick tawa held upside down over low heat is the workable substitute."],
  [("Grind the soaked rice with water to a very thin, pourable batter, about the consistency of milk.",
    "Too thick and the sheet will not be translucent."),
   ("Heat a tawa on low. Dip a clean muslin cloth in the batter and wipe it across the hot surface in one pass.",
    "One pass. Going over it twice tears the film."),
   ("Within seconds the film lifts at the edges. Peel it off whole and lay it on a dry surface.",
    "If it sticks, the tawa is too cool. If it browns, too hot."),
   ("Brush a sheet with ghee, dust generously with the sugar and cardamom, scatter cashew, and lay a second sheet on top.",),
   ("Brush again, fold in the sides and roll into a loose cylinder. Repeat with the rest.",),
   ("Leave 20 minutes for the sugar to draw and settle before eating.",)],
  "Keeps 4 days in an airtight tin at room temperature, layered with greaseproof paper so the sheets do not fuse. Do not refrigerate: the ghee sets and the sheets crack.",
  []),

R("bandar-laddu", "Bandar Laddu", "Andhra",
  "the coarse gram-flour laddu of Machilipatnam, more crumb than sphere",
  15, 20, 30, M, [STOVE, KADHAI], [VEG, GF, NF], ["dairy"],
  [("besan", "300g, coarse", "coarse besan is the point; fine flour gives a dense, pasty laddu", True),
   ("sugar", "300g, ground", None, True),
   ("ghee", "200g", None, True),
   ("cardamom", "8 pods, seeds ground", None, True),
   ("cashew", "40g, broken", None, False),
   ("raisins", "30g", None, False),
   ("water", "3 tbsp", None, True)],
  ["The boondi is made loose and coarse rather than as neat pearls, which is what gives Bandar laddu its crumbly bite.",
   "It is a GI-tagged sweet from Machilipatnam, which the British called Bandar."],
  [("Whisk the besan with the water into a thick batter that falls in ribbons.",),
   ("Heat half the ghee. Pour the batter through a slotted spoon so it falls in irregular drops and fry until pale gold.",
    "Pale gold, not brown. It cooks again in the syrup."),
   ("Drain and crush the fried boondi coarsely between your palms.",),
   ("Fry the cashew and raisins in a spoonful of ghee and stir them through with the sugar and cardamom.",),
   ("Pour over the remaining warm ghee and mix. While still warm, press firmly into balls.",
    "Warm is essential. Cold mixture will not hold and you will be left with sweet crumbs.")],
  "Keeps 10 days in an airtight tin at room temperature. The ghee firms up but the laddu stays crumbly, which is how it should be.",
  []),

R("ariselu", "Ariselu", "Andhra",
  "rice flour and jaggery discs fried for Sankranti, chewy and dark",
  12, 40, 30, A, [STOVE, KADHAI], [VEG, VGN, GF, DF, NF], [],
  [("rice", "400g, soaked 4 hours then dried and ground", "the flour must be slightly damp, which is why it is ground at home", True),
   ("jaggery", "300g", None, True),
   ("sesame", "3 tbsp", None, True),
   ("cardamom", "6 pods, seeds ground", None, True),
   ("neutral-oil", "500ml for frying", None, True),
   ("water", "100ml", None, True)],
  ["The jaggery syrup stage decides everything. Too soft and the discs dissolve in the oil; too hard and they are inedible.",
   "Test it: a drop of syrup in cold water should form a ball you can roll between your fingers."],
  [("Melt the jaggery with the water and boil to the soft-ball stage, about 8 minutes.",
    "Drop a little into cold water. It should gather into a soft ball, not a thread and not a brittle sheet."),
   ("Take off the heat and stir in the rice flour, sesame and cardamom quickly, while the syrup is still hot.",),
   ("Knead into a soft dough while just cool enough to handle. Rest it 4 hours or overnight.",
    "The rest lets the flour drink the syrup. Skipping it gives a hard ariselu."),
   ("Pat portions into 8cm discs between two greased sheets of plastic.",),
   ("Fry one at a time on medium, spooning oil over the top, until deep brown, about 3 minutes.",
    "One at a time. They are fragile and stick to each other."),
   ("Press each one between two flat spoons as it comes out to squeeze the oil back.",)],
  "Keeps 2 weeks in an airtight tin at room temperature and firms up over the first few days, which is normal.",
  []),

# ----------------------------------------------------------- Anglo-Indian

R("jalfrezi", "Jalfrezi", "Anglo-Indian",
  "yesterday's roast turned into something better with chilli, onion and vinegar",
  4, 20, 25, E, [STOVE, KADHAI], [GF, DF, NF], [],
  [("chicken", "500g cooked, torn into strips", "the dish exists to use up cold roast meat; raw chicken works but misses the point", True),
   ("onion", "3 medium, cut into petals", None, True),
   ("capsicum", "2, cut into strips", None, True),
   ("tomato", "2, quartered", None, True),
   ("green-chilli", "4, slit", None, True),
   ("ginger", "1 tbsp, julienned", None, True),
   ("garlic", "6 cloves, sliced", None, True),
   ("vinegar", "2 tbsp", "the Anglo-Indian signature; it is what separates this from a stir fry", True),
   ("cumin-powder", "1 tsp", None, True),
   ("turmeric", "1/2 tsp", None, True),
   ("chilli-powder", "1 tsp", None, True),
   ("neutral-oil", "3 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["Jalfrezi is a leftovers dish by design. The name comes from a Bengali word for hot frying, and the method is fast and dry.",
   "Everything is cut large and stays distinct. It should not collapse into a curry."],
  [("Heat the oil until nearly smoking. Add the garlic and ginger and fry 30 seconds.",),
   ("Add the onion petals and capsicum and fry on high 4 minutes. They should char at the edges and stay crisp.",
    "High heat throughout. On low they sweat and go soft."),
   ("Add the turmeric, cumin, chilli powder and green chillies. Toss 1 minute.",),
   ("Add the cooked meat and tomato and fry 4 minutes until heated through and glossy.",),
   ("Splash in the vinegar, let it hiss off, season and serve at once.",)],
  "Keeps 2 days refrigerated but the vegetables soften. Reheat fast on high heat rather than gently.",
  []),

R("dak-bungalow-curry", "Dak Bungalow Curry", "Anglo-Indian",
  "the chicken curry cooked in colonial rest houses, thickened with a boiled egg and a potato",
  4, 20, 50, M, [STOVE], [GF, DF, NF], ["egg"],
  [("chicken", "800g on the bone", None, True),
   ("potato", "3 medium, halved", "fried before it goes in, which is what makes it a dak bungalow curry", True),
   ("eggs", "4, hard-boiled and peeled", None, True),
   ("onion", "3, finely sliced", None, True),
   ("ginger", "1 tbsp paste", None, True),
   ("garlic", "1 tbsp paste", None, True),
   ("black-pepper", "1.5 tsp, crushed", "pepper rather than chilli leads this curry", True),
   ("garam-masala", "1 tsp", None, True),
   ("turmeric", "1/2 tsp", None, True),
   ("bay-leaf", "2", None, True),
   ("vinegar", "1 tbsp", None, True),
   ("neutral-oil", "5 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["Dak bungalows were the rest houses on the mail routes. The khansama cooked whatever was to hand, which is why the dish carries a potato and an egg.",
   "Fry the potato and the boiled eggs before they go in. That browning is the difference between this and an ordinary curry."],
  [("Fry the halved potatoes in the oil until golden on all sides. Lift out. Fry the boiled eggs until blistered. Lift out.",),
   ("In the same oil, brown the onion deeply with the bay leaves. Add the ginger and garlic and cook out.",),
   ("Add the chicken, turmeric and half the pepper. Fry on high until sealed and coloured, 8 minutes.",),
   ("Add 400ml water, cover and simmer 25 minutes. Return the potatoes for the last 15.",),
   ("Add the eggs, the rest of the pepper, the garam masala and the vinegar. Simmer uncovered 5 minutes.",
    "The vinegar goes in at the end. Boiled long it just tastes sour."),
   ("Rest 10 minutes before serving with bread or rice.",)],
  "Keeps 3 days refrigerated and is better on day two. Take the eggs out before freezing; boiled whites go rubbery.",
  []),

R("kedgeree", "Kedgeree", "Anglo-Indian",
  "smoked fish, rice and egg; the khichdi that went to England for breakfast",
  4, 15, 30, E, [STOVE], [GF, NF], ["fish", "egg", "dairy"],
  [("fish", "400g smoked, or any firm fish plus 1/2 tsp smoked paprika", None, True),
   ("basmati-rice", "300g, rinsed", None, True),
   ("eggs", "4, hard-boiled and quartered", None, True),
   ("onion", "2, finely sliced", None, True),
   ("butter", "50g", None, True),
   ("turmeric", "1 tsp", None, True),
   ("coriander-powder", "2 tsp", None, True),
   ("cumin-powder", "1 tsp", None, True),
   ("chilli-powder", "1/2 tsp", None, False),
   ("milk", "300ml, for poaching the fish", None, True),
   ("bay-leaf", "1", None, True),
   ("coriander-leaves", "a handful", None, True),
   ("lemon", "1", None, True),
   ("black-pepper", "1 tsp", None, True),
   ("salt", "to taste", None, True)],
  ["Kedgeree is khichdi rebuilt around smoked fish and eaten cold or warm at breakfast. It went home with returning families and stayed on British breakfast tables for a century.",
   "Poach the fish in milk rather than water. It keeps the flesh soft and takes the edge off the smoke."],
  [("Poach the fish gently in the milk with the bay leaf for 6 minutes. Lift out, flake coarsely and discard the milk and bones.",),
   ("Boil the rice in salted water with the turmeric until just done. Drain and spread out to cool slightly.",
    "Slightly undercook it. It gets stirred again."),
   ("Fry the onion in the butter until soft and golden, 10 minutes.",),
   ("Fold in the rice, then the flaked fish, keeping the pieces whole. Season with pepper.",
    "Fold, do not stir. Stirring shreds the fish and breaks the grains."),
   ("Top with the quartered eggs, scatter coriander, and finish with lemon.",)],
  "Keeps 2 days refrigerated. Cool it quickly and refrigerate within two hours, as with any cooked rice dish. Eat cold or reheat thoroughly.",
  []),

R("devilled-kidneys", "Devilled Kidneys", "Anglo-Indian",
  "lamb kidneys in a sharp, peppery sauce, eaten on toast at breakfast",
  2, 15, 12, M, [STOVE], [NF], ["dairy", "gluten"],
  [("mutton", "300g kidneys, cored and halved", "lamb kidney; soak 20 minutes in salted water and rinse", True),
   ("butter", "40g", None, True),
   ("onion", "1, finely chopped", None, True),
   ("black-pepper", "1.5 tsp, coarsely crushed", None, True),
   ("chilli-powder", "1 tsp", None, True),
   ("vinegar", "1 tbsp", None, True),
   ("cream", "3 tbsp", None, False),
   ("bread", "4 slices, toasted", None, True),
   ("coriander-leaves", "a handful", None, False),
   ("salt", "to taste", None, True)],
  ["Devilled means hot and sharp: pepper, mustard and something acid. It is a breakfast dish and a fast one.",
   "Kidneys are ruined by overcooking. Six minutes total, and they should still be pink at the centre."],
  [("Soak the cored kidneys in salted water 20 minutes, then rinse and pat completely dry.",
    "Drying matters. Wet kidneys stew."),
   ("Melt the butter and soften the onion 5 minutes.",),
   ("Raise the heat, add the kidneys and sear 2 minutes without moving them.",),
   ("Add the pepper and chilli powder, toss 2 minutes, then the vinegar and cream.",),
   ("Season, spoon over hot toast and scatter coriander.",
    "Serve the moment it is done. Held warm, kidneys go grey and tough.")],
  "Eat immediately. This does not keep or reheat.",
  []),

R("duck-buffath", "Duck Buffath", "Anglo-Indian",
  "duck stewed with vinegar and whole spice, a Christmas table dish",
  4, 25, 90, M, [STOVE], [GF, DF, NF], [],
  [("duck", "1.2kg, jointed, excess fat trimmed", None, True),
   ("onion", "4, thickly sliced", None, True),
   ("vinegar", "5 tbsp", "buffath is a vinegar stew; this is not a place to economise", True),
   ("garlic", "10 cloves, sliced", None, True),
   ("ginger", "2 tbsp, julienned", None, True),
   ("dried-red-chilli", "6", None, True),
   ("black-pepper", "2 tsp", None, True),
   ("cinnamon", "1 stick", None, True),
   ("cloves", "6", None, True),
   ("turmeric", "1 tsp", None, True),
   ("potato", "3, quartered", None, False),
   ("sugar", "1 tsp", None, True),
   ("salt", "to taste", None, True)],
  ["Buffath is close kin to Goan vindaloo and sorpotel: meat, vinegar, garlic and long keeping. It sat on Anglo-Indian Christmas tables because it improved for days.",
   "Render the duck fat off first and cook the onions in it. Nothing else gives the same depth."],
  [("Brown the duck pieces skin down in a dry heavy pot until the fat runs and the skin is deep gold. Lift out.",
    "No oil. There is more than enough fat in the bird."),
   ("Pour off all but 4 tbsp of the fat. Fry the onions in it until soft and brown, 15 minutes.",),
   ("Add the garlic, ginger, chillies, cinnamon, cloves, pepper and turmeric. Fry 3 minutes.",),
   ("Return the duck, add the vinegar and 400ml water, cover and simmer 70 minutes until the meat pulls easily.",),
   ("Add the potato for the last 25 minutes. Season with salt and the sugar.",
    "The sugar is not for sweetness, it takes the raw edge off the vinegar."),
   ("Rest overnight if you can. It is a better dish on day two.",)],
  "Keeps 4 days refrigerated and genuinely improves for the first two, which is the vinegar doing its work. Reheat to a full simmer. Freezes for a month.",
  []),

R("anglo-rissoles", "Rissoles", "Anglo-Indian",
  "minced meat folded into pastry crescents and fried, the Anglo-Indian tea plate staple",
  12, 40, 25, M, [STOVE, KADHAI], [NF], ["gluten", "egg", "dairy"],
  [("maida", "300g", None, True),
   ("butter", "60g, cold and cubed", None, True),
   ("eggs", "2, one for the dough and one for sealing", None, True),
   ("mutton", "400g minced", "beef or chicken mince works equally", True),
   ("onion", "2, finely chopped", None, True),
   ("potato", "2, boiled and mashed", None, True),
   ("black-pepper", "1.5 tsp", None, True),
   ("green-chilli", "3, chopped", None, True),
   ("coriander-leaves", "a handful", None, True),
   ("vinegar", "1 tbsp", None, True),
   ("neutral-oil", "500ml for frying", None, True),
   ("salt", "to taste", None, True)],
  ["Rissoles, croquettes and cutlets are the three fried things on every Anglo-Indian tea table. This is the pastry one.",
   "The filling must be completely cold and quite dry before it goes near the pastry, or the seal fails in the oil."],
  [("Rub the butter into the flour with a pinch of salt, bind with one beaten egg and a little cold water, and rest the dough 30 minutes.",),
   ("Fry the onion until golden, add the mince and cook until it is dry and browned, 12 minutes.",
    "Dry. Any moisture left will burst the pastry."),
   ("Stir in the mashed potato, pepper, green chilli, coriander and vinegar. Season and cool completely.",),
   ("Roll the dough thin, cut 10cm rounds, place a spoonful of filling on each and fold into a crescent.",),
   ("Seal the edges with beaten egg and crimp firmly with a fork.",
    "Crimp properly. A rissole that opens in the pan takes the oil with it."),
   ("Fry in batches on medium until deep gold, about 4 minutes, and drain on paper.",)],
  "Keeps 2 days refrigerated. Crisp them in a hot oven rather than a microwave. They freeze well uncooked: fry from frozen, adding 2 minutes.",
  []),

R("anglo-coconut-toffee", "Coconut Toffee", "Anglo-Indian",
  "coconut and milk boiled to a fudge, cut in diamonds at Christmas",
  20, 10, 35, E, [STOVE], [VEG, GF, NF], ["dairy"],
  [("coconut", "300g, freshly grated", None, True),
   ("sugar", "400g", None, True),
   ("milk", "200ml", None, True),
   ("butter", "40g", None, True),
   ("cardamom", "6 pods, seeds ground", None, True),
   ("cashew", "50g, chopped", None, False)],
  ["This is the Anglo-Indian Christmas sweet, made alongside kul kuls and rose cookies and given away in tins.",
   "It is a sugar-stage recipe. Stop at the wrong moment and you get either syrup or a brick."],
  [("Boil the sugar and milk together until the sugar dissolves completely.",),
   ("Add the coconut and cook on medium, stirring constantly, for 20 minutes.",
    "Constantly. The bottom catches the moment you look away."),
   ("Add the butter and cardamom and keep going until the mixture leaves the sides of the pan in one mass and a drop set in cold water holds its shape.",),
   ("Pour into a greased tray, scatter the cashew and press down flat.",),
   ("Mark into diamonds while still warm and cut through when cold.",
    "Mark warm, cut cold. Cutting it hot smears it; cutting it fully cold shatters it.")],
  "Keeps 2 weeks in an airtight tin at room temperature. It dries out slowly rather than spoiling, so eat it while it still yields.",
  []),

R("anglo-bread-pudding", "Bread Pudding", "Anglo-Indian",
  "stale bread, milk and dried fruit baked into the household dessert",
  6, 20, 55, E, [OVEN], [VEG, NF], ["gluten", "dairy", "egg"],
  [("bread", "300g stale, torn", "stale is not a compromise, fresh bread turns to paste", True),
   ("milk", "600ml", None, True),
   ("eggs", "3", None, True),
   ("sugar", "150g", None, True),
   ("butter", "50g, melted", None, True),
   ("raisins", "80g", None, True),
   ("cardamom", "6 pods, seeds ground", None, True),
   ("nutmeg", "1/4 tsp, grated", None, True),
   ("dried-apricot", "60g, chopped", None, False)],
  ["Every Anglo-Indian household made this and no two made it the same way. What is constant is stale bread, milk and whatever dried fruit was in the tin.",
   "Soak the bread properly. Twenty minutes, not five."],
  [("Warm the milk with the sugar until it dissolves. Pour it over the torn bread and leave 20 minutes.",),
   ("Mash the soaked bread roughly with a fork. It should be lumpy, not smooth.",),
   ("Beat in the eggs, melted butter, cardamom and nutmeg, then fold in the raisins and apricot.",),
   ("Pour into a greased dish and bake at 180C for 50 minutes until set with a browned top and a slight wobble at the centre.",
    "A slight wobble. Baked until firm all through, it is dry."),
   ("Cool 20 minutes before cutting. It firms as it settles.",)],
  "Keeps 3 days refrigerated. Serve at room temperature or warmed. It contains egg and milk, so keep it cold rather than on the counter.",
  []),
]
