"""Indo-Chinese, Tamil Nadu snacks and biryanis, Kerala and Karnataka coast.

Indo-Chinese had 12 recipes and no Chicken Manchurian, which is close to the
most ordered dish in the idiom. Tamil Nadu had 48 recipes and not one of the
fried snacks the state actually eats between meals.
"""
from add_recipes import R

E, M, A = "easy", "moderate", "advanced"
STOVE, PC, STEAM, BLEND, OVEN, KADHAI, TAWA = (
    "stovetop", "pressure-cooker", "steamer", "blender", "oven", "kadhai", "tawa")
VEG, VGN, GF, DF, NF, NOG = (
    "vegetarian", "vegan", "gluten-free", "dairy-free", "nut-free", "no-onion-garlic")

BATCH = [

# --------------------------------------------------------- Indo-Chinese

R("chicken-manchurian", "Chicken Manchurian", "Indo-Chinese",
  "fried chicken in a dark garlic and soy gravy, the dish that built Indian Chinese",
  4, 25, 25, M, [STOVE, KADHAI], [DF, NF], ["gluten", "soy", "egg"],
  [("chicken", "600g boneless, 3cm cubes", None, True),
   ("cornflour", "5 tbsp", None, True),
   ("maida", "3 tbsp", None, True),
   ("eggs", "1, beaten", None, True),
   ("garlic", "2 tbsp, finely chopped", "the dish is built on garlic; do not reduce this", True),
   ("ginger", "1 tbsp, finely chopped", None, True),
   ("spring-onion", "6, whites and greens separated", None, True),
   ("soy-sauce", "3 tbsp", None, True),
   ("vinegar", "2 tbsp", None, True),
   ("green-chilli", "4, slit", None, True),
   ("black-pepper", "1 tsp", None, True),
   ("sugar", "1 tsp", None, True),
   ("neutral-oil", "500ml for deep frying, plus 3 tbsp for the gravy", None, True),
   ("water", "250ml", None, True),
   ("salt", "to taste", None, True)],
  ["Invented in Kolkata, not Manchuria. Nelson Wang is generally credited with it at a Bombay hotel in the 1970s.",
   "Fry the chicken twice. The second fry is what keeps it crisp once the gravy is on it."],
  [("Toss the chicken with the egg, 3 tbsp cornflour, the maida, salt and pepper into a thick coating.",),
   ("Deep fry on medium until pale gold, 4 minutes. Rest 5 minutes, then fry again on high for 1 minute.",
    "The double fry is the whole technique. One fry and it goes soggy the moment it meets the sauce."),
   ("In 3 tbsp oil, fry the garlic, ginger, green chilli and spring onion whites hard for 1 minute.",
    "Hard and fast. Garlic browned slowly turns bitter."),
   ("Add the soy sauce, vinegar, sugar and water. Bring to a boil.",),
   ("Slake the remaining cornflour in cold water and stir it in until the sauce turns glossy and coats a spoon.",),
   ("Fold in the chicken, toss for 30 seconds only, and finish with the spring onion greens.",
    "Thirty seconds. Any longer and the crust you worked for is gone.")],
  "Best within the hour, which is true of anything fried and sauced. It keeps 2 days refrigerated; reheat in a hot pan, not a microwave.",
  []),

R("hot-and-sour-soup", "Hot and Sour Soup", "Indo-Chinese",
  "thick pepper and vinegar soup with shredded vegetables, on every Indian Chinese menu",
  4, 20, 20, E, [STOVE], [VEG, DF, NF], ["soy", "gluten"],
  [("cabbage", "150g, finely shredded", None, True),
   ("carrot", "2, julienned", None, True),
   ("capsicum", "1, julienned", None, True),
   ("mushroom", "100g, sliced", None, True),
   ("spring-onion", "4, chopped", None, True),
   ("garlic", "1 tbsp, chopped", None, True),
   ("ginger", "1 tbsp, chopped", None, True),
   ("soy-sauce", "3 tbsp", None, True),
   ("vinegar", "3 tbsp", "white vinegar, and more at the table", True),
   ("black-pepper", "2 tsp, coarsely crushed", "the heat here is pepper, not chilli", True),
   ("cornflour", "4 tbsp", None, True),
   ("water", "1.2 litres", None, True),
   ("neutral-oil", "2 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["Hot from pepper, sour from vinegar. Neither should be shy.",
   "The soup is thickened until a spoon leaves a track. Thin hot and sour soup is just vegetable water."],
  [("Fry the garlic and ginger in the oil for 30 seconds, then add all the vegetables and toss on high 3 minutes.",
    "They should keep their bite. This is not a stew."),
   ("Add the water, soy sauce and half the pepper. Simmer 8 minutes.",),
   ("Slake the cornflour in 150ml cold water and stir it in steadily until the soup thickens and turns glossy.",
    "Cold water. Dropped into hot liquid dry, cornflour lumps instantly."),
   ("Add the vinegar and the rest of the pepper off the heat.",
    "Vinegar boiled hard loses its edge, which is the point of it."),
   ("Check the salt, scatter spring onion, and serve with extra vinegar and chilli on the side.",)],
  "Keeps 2 days refrigerated. It thickens further as it cools, so loosen with hot water and re-sharpen with a splash of vinegar when reheating.",
  []),

R("kolkata-spring-rolls", "Spring Rolls", "Indo-Chinese",
  "crisp rolls of shredded vegetables and noodles, Kolkata Chinatown style",
  12, 40, 25, M, [STOVE, KADHAI], [VEG, DF, NF], ["gluten", "soy"],
  [("maida", "200g", "for the wrappers; shop-bought sheets work and save an hour", True),
   ("cabbage", "200g, finely shredded", None, True),
   ("carrot", "2, julienned", None, True),
   ("capsicum", "1, julienned", None, True),
   ("noodles", "80g, boiled and cut short", None, True),
   ("spring-onion", "4, chopped", None, True),
   ("garlic", "1 tbsp, chopped", None, True),
   ("soy-sauce", "2 tbsp", None, True),
   ("black-pepper", "1 tsp", None, True),
   ("cornflour", "3 tbsp, slaked, for sealing", None, True),
   ("neutral-oil", "500ml for deep frying, plus 2 tbsp", None, True),
   ("water", "as needed for the dough", None, True),
   ("salt", "to taste", None, True)],
  ["The filling must be cooked fast and cooled completely. Warm filling steams inside the wrapper and splits it.",
   "Roll tight. A loose roll fills with oil."],
  [("Make a soft dough with the flour, a pinch of salt and water. Rest 30 minutes, then roll paper thin and cut into squares.",),
   ("Fry the garlic in 2 tbsp oil, add the vegetables and toss on the highest heat for 3 minutes.",
    "High heat and keep them moving. Wilted vegetables make a wet filling."),
   ("Add the noodles, soy sauce, pepper and salt, toss once and spread on a tray to cool completely.",),
   ("Place a spoonful on each wrapper, fold in the sides and roll tightly, sealing the edge with slaked cornflour.",),
   ("Fry in batches on medium until deep gold, about 4 minutes, and drain upright so the oil runs out.",)],
  "Best within 2 hours. They keep a day refrigerated and crisp up again in a hot oven. Uncooked rolls freeze well for a month; fry from frozen.",
  []),

R("dragon-chicken", "Dragon Chicken", "Indo-Chinese",
  "crisp chicken strips in a sweet, hot red sauce with cashew",
  4, 25, 20, M, [STOVE, KADHAI], [DF], ["gluten", "soy", "egg", "nuts"],
  [("chicken", "500g boneless, cut into strips", None, True),
   ("cornflour", "4 tbsp", None, True),
   ("maida", "2 tbsp", None, True),
   ("eggs", "1, beaten", None, True),
   ("cashew", "60g", None, True),
   ("dried-red-chilli", "8", None, True),
   ("garlic", "2 tbsp, chopped", None, True),
   ("onion", "1, cut into petals", None, True),
   ("capsicum", "1, cut into squares", None, True),
   ("soy-sauce", "2 tbsp", None, True),
   ("vinegar", "1 tbsp", None, True),
   ("sugar", "2 tsp", None, True),
   ("kashmiri-chilli", "2 tsp", "for the colour the dish is named for", True),
   ("neutral-oil", "500ml for deep frying, plus 3 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["Restaurant dragon chicken gets its red from food colouring. Kashmiri chilli does it honestly and tastes better.",
   "The cashews go in whole and toasted, not ground. They are meant to be found."],
  [("Coat the chicken strips in the egg, cornflour, maida and salt.",),
   ("Deep fry on medium until crisp and gold, about 5 minutes. Drain.",),
   ("Toast the cashews in a dry pan until they colour. Set aside.",),
   ("In 3 tbsp oil, fry the dried chillies and garlic 30 seconds, then the onion and capsicum on high 2 minutes.",),
   ("Add the soy sauce, vinegar, sugar, kashmiri chilli and 100ml water. Boil until syrupy.",),
   ("Toss in the chicken and cashews, coat quickly and serve at once.",
    "At once. The crust softens within minutes of meeting the sauce.")],
  "Eat straight away. It keeps 2 days refrigerated but the texture is the dish, and that does not survive.",
  []),

R("crispy-chilli-baby-corn", "Crispy Chilli Baby Corn", "Indo-Chinese",
  "battered baby corn tossed in a hot garlic sauce, the vegetarian chilli chicken",
  4, 20, 20, E, [STOVE, KADHAI], [VEG, DF, NF], ["gluten", "soy"],
  [("corn", "300g baby corn, halved lengthways", None, True),
   ("cornflour", "5 tbsp", None, True),
   ("maida", "3 tbsp", None, True),
   ("garlic", "2 tbsp, chopped", None, True),
   ("green-chilli", "4, slit", None, True),
   ("capsicum", "1, cut into squares", None, True),
   ("onion", "1, cut into petals", None, True),
   ("spring-onion", "4, chopped", None, True),
   ("soy-sauce", "2 tbsp", None, True),
   ("vinegar", "1 tbsp", None, True),
   ("chilli-powder", "1 tsp", None, True),
   ("black-pepper", "1 tsp", None, True),
   ("neutral-oil", "500ml for deep frying, plus 3 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["Baby corn holds water. Blanch it and dry it properly or the batter slides off.",
   "The batter should coat like thin cream. Thick batter gives a doughy shell."],
  [("Blanch the baby corn 2 minutes in salted water, drain and dry thoroughly on a cloth.",),
   ("Whisk the cornflour, maida, salt and enough cold water into a thin batter. Coat the corn.",),
   ("Deep fry on medium-high until crisp and pale gold, 4 minutes. Drain.",),
   ("In 3 tbsp oil, fry the garlic and green chilli hard for 30 seconds, then the onion and capsicum for 2 minutes.",),
   ("Add the soy sauce, vinegar, chilli powder, pepper and a splash of water. Boil 1 minute.",),
   ("Toss in the corn, coat, and finish with spring onion.",)],
  "Eat immediately. This does not keep in any state worth serving.",
  []),

R("triple-schezwan-rice", "Triple Schezwan Rice", "Indo-Chinese",
  "fried rice, noodles and a schezwan gravy on one plate, the Bombay street order",
  4, 30, 30, M, [STOVE, KADHAI], [VEG, DF, NF], ["gluten", "soy"],
  [("rice", "300g, cooked and cooled", None, True),
   ("noodles", "150g, boiled and fried crisp", None, True),
   ("cabbage", "150g, shredded", None, True),
   ("carrot", "2, julienned", None, True),
   ("capsicum", "1, julienned", None, True),
   ("spring-onion", "6, chopped", None, True),
   ("garlic", "2 tbsp, chopped", None, True),
   ("dried-red-chilli", "10, soaked and ground to a paste", "the schezwan paste; buy it if you prefer", True),
   ("soy-sauce", "3 tbsp", None, True),
   ("vinegar", "2 tbsp", None, True),
   ("cornflour", "3 tbsp", None, True),
   ("neutral-oil", "6 tbsp, plus 300ml for frying the noodles", None, True),
   ("water", "300ml", None, True),
   ("salt", "to taste", None, True)],
  ["Three things on one plate: rice at the bottom, gravy over it, crisp noodles on top. Assembled at the last moment.",
   "Use cold, day-old rice. Warm rice turns to paste in the pan."],
  [("Fry the boiled noodles in hot oil until crisp and golden. Drain and set aside.",),
   ("In 3 tbsp oil, fry half the garlic hard, add half the vegetables, then the cold rice and 1 tbsp soy sauce. Toss on high 4 minutes.",
    "Highest heat you have. Fried rice is a heat technique, not a recipe."),
   ("For the gravy, fry the rest of the garlic in 3 tbsp oil, add the chilli paste and fry 3 minutes until the oil separates.",),
   ("Add the remaining vegetables, soy sauce, vinegar and water. Boil, then thicken with slaked cornflour.",),
   ("Plate the rice, ladle the gravy over, and pile the crisp noodles on top. Scatter spring onion and serve at once.",
    "Assemble at the table. The noodles go soft in about two minutes.")],
  "The components keep 2 days refrigerated separately. Cool the rice quickly and refrigerate within two hours. Assembled, it does not keep at all.",
  []),

R("wonton-soup", "Wonton Soup", "Indo-Chinese",
  "thin pastry dumplings in a clear peppery broth, Kolkata Chinatown",
  4, 40, 25, M, [STOVE], [DF, NF], ["gluten", "soy", "egg"],
  [("maida", "200g", None, True),
   ("eggs", "1", None, True),
   ("chicken", "250g minced", "or finely chopped mushroom and cabbage for a vegetarian version", True),
   ("spring-onion", "5, chopped", None, True),
   ("ginger", "1 tbsp, grated", None, True),
   ("garlic", "1 tbsp, chopped", None, True),
   ("soy-sauce", "2 tbsp", None, True),
   ("black-pepper", "1.5 tsp", None, True),
   ("water", "1.5 litres", None, True),
   ("neutral-oil", "1 tbsp", None, True),
   ("coriander-leaves", "a handful", None, False),
   ("salt", "to taste", None, True)],
  ["The broth should be clear and taste of pepper and ginger. Cloudy broth means it boiled hard; keep it at a bare simmer.",
   "Wrappers must be rolled genuinely thin. You should almost see the filling through them."],
  [("Make a firm dough with the flour, egg and a little water. Rest 30 minutes, roll very thin and cut 8cm squares.",),
   ("Mix the mince with half the spring onion, the ginger, 1 tbsp soy sauce, half the pepper and salt.",),
   ("Place a small spoonful on each square, wet the edges and pinch closed into a pouch.",
    "Small. An overfilled wonton splits in the water."),
   ("Bring the water to a bare simmer with the garlic, remaining soy sauce, pepper and oil. Season.",),
   ("Slide the wontons in and poach 6 minutes until they float and the wrappers turn translucent.",
    "A simmer, never a boil. A rolling boil tears them open."),
   ("Ladle into bowls with the broth and finish with spring onion and coriander.",)],
  "The broth keeps 3 days refrigerated. Cook wontons fresh; poached ones swell and go pasty. Uncooked wontons freeze well for a month.",
  []),

# ------------------------------------------------------------ Tamil Nadu

R("murukku", "Murukku", "Tamil Nadu",
  "spiralled rice flour crisps, the snack tin that is never empty",
  20, 25, 30, M, [STOVE, KADHAI], [VEG, VGN, GF, DF, NF], [],
  [("rice-flour", "300g", None, True),
   ("urad-dal", "80g, dry roasted and ground fine", "the roasted dal is what makes it crisp rather than hard", True),
   ("sesame", "2 tbsp", None, True),
   ("cumin-seeds", "1 tsp", None, True),
   ("asafoetida", "1/2 tsp", None, True),
   ("butter", "40g, softened", "or ghee; the fat is what stops it being a jaw-breaker", True),
   ("water", "as needed", None, True),
   ("neutral-oil", "500ml for deep frying", None, True),
   ("salt", "to taste", None, True)],
  ["The dough should be soft enough to press and stiff enough to hold a spiral. Too soft and it breaks in the oil.",
   "Fry on steady medium. High heat browns the outside while the inside stays raw and chewy."],
  [("Dry roast the urad dal until it smells nutty and turns pale gold, cool, and grind to a fine flour.",),
   ("Mix both flours with the sesame, cumin, asafoetida, salt and softened butter, rubbing until it resembles crumbs.",),
   ("Add water a little at a time to a smooth, soft dough. Do not let it get sticky.",),
   ("Press spirals directly onto a greased sheet using a murukku press with the star plate.",),
   ("Slide them into medium-hot oil and fry until the bubbling stops and they turn pale gold, about 5 minutes.",
    "When the hissing stops, the water has gone and they are done. Colour alone will mislead you."),
   ("Drain on paper and cool completely before storing.",
    "Completely. Stored warm they go soft overnight.")],
  "Keeps 3 weeks in an airtight tin at room temperature. Low moisture is what makes it keep, so seal the tin properly and never refrigerate.",
  ["hing"]),

R("thattai", "Thattai", "Tamil Nadu",
  "flat, crisp rice discs studded with dal and curry leaf",
  20, 25, 30, M, [STOVE, KADHAI], [VEG, VGN, GF, DF, NF], [],
  [("rice-flour", "300g", None, True),
   ("chana-dal", "3 tbsp, soaked 1 hour and drained", "the studs; they should stay whole and crunchy", True),
   ("urad-dal", "2 tbsp, roasted and ground", None, True),
   ("curry-leaves", "3 sprigs, torn", None, True),
   ("sesame", "1 tbsp", None, True),
   ("asafoetida", "1/2 tsp", None, True),
   ("chilli-powder", "1 tsp", None, True),
   ("butter", "40g", None, True),
   ("water", "as needed", None, True),
   ("neutral-oil", "500ml for deep frying", None, True),
   ("salt", "to taste", None, True)],
  ["Thattai means flat. They are pressed thin by hand between plastic sheets, not rolled.",
   "Prick each disc before frying or it puffs into a ball."],
  [("Mix the flours, soaked chana dal, torn curry leaves, sesame, asafoetida, chilli powder, salt and butter.",),
   ("Add water gradually to a stiff dough. It should not be sticky.",),
   ("Take small balls and flatten each between two greased plastic sheets into thin discs.",),
   ("Prick each disc several times with a fork.",
    "This is not optional. Unpricked thattai balloons and cooks unevenly."),
   ("Fry on medium until the bubbling subsides and they are pale gold and rigid, about 4 minutes.",),
   ("Drain and cool completely before storing.",)],
  "Keeps 3 weeks in an airtight tin at room temperature. If they soften, 5 minutes in a low oven brings them back.",
  ["hing"]),

R("seedai", "Seedai", "Tamil Nadu",
  "small rice flour spheres fried crisp for Krishna Jayanthi",
  30, 30, 25, A, [STOVE, KADHAI], [VEG, GF, NF], ["dairy"],
  [("rice-flour", "250g", None, True),
   ("urad-dal", "3 tbsp, roasted and ground", None, True),
   ("butter", "30g", None, True),
   ("coconut", "3 tbsp, grated", None, True),
   ("sesame", "1 tbsp", None, True),
   ("asafoetida", "1/2 tsp", None, True),
   ("water", "as needed", None, True),
   ("neutral-oil", "500ml for deep frying", None, True),
   ("salt", "to taste", None, True)],
  ["Seedai has a reputation for bursting in the oil. Two things cause it: air pockets in the balls and undissolved salt.",
   "Dissolve the salt in the water before it touches the flour, and roll each ball smooth with no cracks."],
  [("Sieve the flours together. Dissolve the salt and asafoetida in a little water and add that, not dry salt.",
    "Undissolved salt crystals are the classic cause of a seedai exploding."),
   ("Rub in the butter and coconut, then bring together into a stiff dough with water.",),
   ("Roll small marble-sized balls, keeping each one completely smooth with no cracks.",
    "A crack is where the steam gets in. Roll them properly."),
   ("Spread the balls on a cloth and air-dry 20 minutes.",),
   ("Fry a small batch on medium first as a test. If it holds, fry the rest until the bubbling stops.",
    "Test batch first, and stand back from the pan for the first minute."),
   ("Drain and cool completely.",)],
  "Keeps 2 weeks in an airtight tin at room temperature. The coconut is what limits it; beyond that it can turn.",
  ["hing"]),

R("ribbon-pakoda", "Ribbon Pakoda", "Tamil Nadu",
  "flat ribbons of gram and rice flour, fried until they snap",
  20, 20, 25, E, [STOVE, KADHAI], [VEG, VGN, GF, DF, NF], [],
  [("besan", "200g", None, True),
   ("rice-flour", "150g", None, True),
   ("chilli-powder", "1.5 tsp", None, True),
   ("asafoetida", "1/2 tsp", None, True),
   ("butter", "30g", "or oil, for a vegan version", True),
   ("water", "as needed", None, True),
   ("neutral-oil", "500ml for deep frying", None, True),
   ("salt", "to taste", None, True)],
  ["Also called ola pakoda, after the palm-leaf strips it resembles.",
   "Press the ribbons directly into the oil in a slow circle so they do not clump."],
  [("Mix the flours, chilli powder, asafoetida and salt. Rub in the butter.",),
   ("Add water gradually to a soft dough that will pass through a press without cracking.",),
   ("Fit a murukku press with the flat ribbon plate and press directly into medium-hot oil, moving in a circle.",
    "Straight into the oil. Pressed onto a sheet first, ribbons stick together."),
   ("Fry until the bubbling slows and the ribbons are golden, about 3 minutes, turning once.",),
   ("Drain, cool completely and break into shorter lengths.",)],
  "Keeps 3 weeks in an airtight tin at room temperature.",
  ["hing"]),

R("adhirasam", "Adhirasam", "Tamil Nadu",
  "jaggery and rice flour discs fried dark and dense, the Diwali sweet that takes practice",
  15, 40, 30, A, [STOVE, KADHAI], [VEG, VGN, GF, DF, NF], [],
  [("rice", "400g, soaked 3 hours, dried and ground", "the flour must retain a little moisture, which is why it is ground fresh", True),
   ("jaggery", "300g, dark", None, True),
   ("cardamom", "6 pods, seeds ground", None, True),
   ("dry-ginger-powder", "1/2 tsp", None, True),
   ("sesame", "1 tbsp", None, False),
   ("water", "100ml", None, True),
   ("neutral-oil", "500ml for deep frying", None, True)],
  ["The dough must rest. Overnight is normal and three days is better; the flour needs time to drink the jaggery syrup.",
   "The syrup stage decides the texture. Take it to soft-ball and no further."],
  [("Melt the jaggery in the water, strain out the grit, and boil to the soft-ball stage.",
    "A drop in cold water should form a soft ball you can roll. A thread stage gives hard adhirasam."),
   ("Take off the heat and stir in the rice flour, cardamom, dry ginger and sesame while hot.",),
   ("Cover and rest at least overnight, up to three days. The dough softens and darkens as it sits.",),
   ("Pat portions into 7cm discs between greased plastic sheets.",),
   ("Fry one at a time on medium, spooning oil over, until deep brown, about 3 minutes.",),
   ("Press each between two flat spoons as it leaves the oil to squeeze out the excess.",)],
  "Keeps 2 weeks in an airtight tin at room temperature and hardens slowly, which is expected.",
  []),

R("ambur-biryani", "Ambur Biryani", "Tamil Nadu",
  "seeraga samba rice and mutton with a soaked chilli paste, no whole garam masala at all",
  4, 30, 60, M, [STOVE, PC], [GF, NF], ["dairy"],
  [("mutton", "700g on the bone", None, True),
   ("basmati-rice", "400g", "seeraga samba is the authentic grain; basmati is the workable substitute", True),
   ("dried-red-chilli", "15, soaked and ground to a paste", "the defining element; Ambur uses chilli paste, not powder", True),
   ("onion", "3, sliced", None, True),
   ("tomato", "2, chopped", None, True),
   ("yogurt", "150g", None, True),
   ("ginger", "2 tbsp paste", None, True),
   ("garlic", "2 tbsp paste", None, True),
   ("mint", "a large handful", None, True),
   ("coriander-leaves", "a large handful", None, True),
   ("lemon", "1", None, True),
   ("neutral-oil", "6 tbsp", None, True),
   ("water", "600ml", None, True),
   ("salt", "to taste", None, True)],
  ["Ambur biryani has almost no whole spice. The flavour is chilli paste, ginger, garlic and mint, and the restraint is the point.",
   "It is cooked as a one-pot dish, not layered. The rice goes into the meat stock."],
  [("Marinate the mutton in the yogurt, ginger, garlic and half the chilli paste for 1 hour in the refrigerator.",),
   ("Fry the onion in the oil until golden. Add the rest of the chilli paste and fry 3 minutes.",),
   ("Add the marinated mutton and tomato and cook until the meat is browned and the oil separates.",),
   ("Add 600ml water and cook 40 minutes until the mutton is tender and you have a strong stock.",),
   ("Stir in the washed rice, mint, coriander and salt. Cover tightly and cook 15 minutes on the lowest heat.",
    "The liquid should be roughly one and a half times the rice by volume, no more."),
   ("Rest 10 minutes off the heat, squeeze over the lemon and fork through gently.",)],
  "Keeps 2 days refrigerated. Cool quickly and refrigerate within two hours, as with any cooked rice. Reheat with a sprinkle of water under a lid.",
  ["dum"]),

R("dindigul-biryani", "Dindigul Biryani", "Tamil Nadu",
  "small-grain rice, curd and a heavy hand with pepper, the biryani that tastes sour",
  4, 30, 55, M, [STOVE, PC], [GF, NF], ["dairy"],
  [("chicken", "800g on the bone", "mutton works equally", True),
   ("basmati-rice", "400g", "seeraga samba is traditional; the small grain is what holds the sourness", True),
   ("yogurt", "200g, sour", "sourness is the signature here, so let the curd stand out", True),
   ("black-pepper", "2 tsp, crushed", "Dindigul leans on pepper where other biryanis use chilli", True),
   ("onion", "3, sliced", None, True),
   ("tomato", "2, chopped", None, True),
   ("green-chilli", "5, slit", None, True),
   ("ginger", "2 tbsp paste", None, True),
   ("garlic", "2 tbsp paste", None, True),
   ("mint", "a large handful", None, True),
   ("cinnamon", "1 stick", None, True),
   ("cloves", "4", None, True),
   ("neutral-oil", "6 tbsp", None, True),
   ("water", "550ml", None, True),
   ("salt", "to taste", None, True)],
  ["Three things separate Dindigul from its neighbours: sour curd, crushed pepper and the small seeraga samba grain.",
   "Marinate in the refrigerator, not on the counter. An hour is plenty."],
  [("Marinate the chicken in the yogurt, ginger, garlic, pepper and salt for 1 hour in the refrigerator.",),
   ("Fry the cinnamon and cloves in the oil, add the onion and fry until golden.",),
   ("Add the green chillies, tomato and the marinated chicken. Cook until the oil separates, 12 minutes.",),
   ("Add the water and mint, bring to a boil and check the seasoning. It should taste slightly over-salted.",
    "The rice will absorb it. Season the liquid, not the finished dish."),
   ("Stir in the washed rice, cover tightly and cook 15 minutes on the lowest heat.",),
   ("Rest 10 minutes before opening and forking through.",)],
  "Keeps 2 days refrigerated. Cool quickly and refrigerate within two hours. Reheat under a lid with a sprinkle of water.",
  ["dum"]),

# ---------------------------------------------------------------- Kerala

R("karimeen-pollichathu", "Karimeen Pollichathu", "Kerala",
  "pearl spot masala-rubbed and steamed inside a banana leaf",
  2, 30, 30, M, [STOVE, TAWA], [GF, DF, NF], ["fish"],
  [("fish", "2 whole, about 300g each, scored", "karimeen (pearl spot) is the fish; pomfret or tilapia stand in", True),
   ("shallot", "10, sliced", None, True),
   ("ginger", "1 tbsp, chopped", None, True),
   ("garlic", "8 cloves, chopped", None, True),
   ("green-chilli", "4, slit", None, True),
   ("curry-leaves", "3 sprigs", None, True),
   ("chilli-powder", "2 tsp", None, True),
   ("turmeric", "1 tsp", None, True),
   ("black-pepper", "1 tsp", None, True),
   ("tamarind", "10g", None, True),
   ("coconut-oil", "5 tbsp", "coconut oil, not a substitute; it is half the flavour", True),
   ("lemon", "1", None, True),
   ("salt", "to taste", None, True)],
  ["Pollichathu means charred. The leaf is not a serving conceit; it scorches and perfumes the fish while trapping the steam.",
   "If you cannot get banana leaf, foil works for the steam but you lose the aroma entirely."],
  [("Score the fish to the bone on both sides. Rub with the turmeric, half the chilli powder, salt and lemon, then refrigerate 30 minutes.",),
   ("Shallow fry the fish 3 minutes a side in 3 tbsp of the coconut oil. Lift out.",),
   ("In the same pan, fry the shallots until soft, then the ginger, garlic, green chilli and curry leaves.",),
   ("Add the remaining chilli powder, pepper and tamarind with a splash of water and cook to a thick masala.",),
   ("Soften a banana leaf over a flame. Spread masala on it, lay the fish down, cover with more masala and wrap tightly.",),
   ("Cook the parcel on a tawa 6 minutes a side on low heat until the leaf blackens and the kitchen smells of it.",
    "Low heat. The leaf should scorch slowly, not catch fire.")],
  "Best eaten straight from the leaf. It keeps a day refrigerated; reheat in the parcel on a low tawa.",
  []),

R("kappa-meen-curry", "Kappa and Meen Curry", "Kerala",
  "mashed tapioca with a fierce red fish curry, the pairing Kerala argues about",
  4, 25, 45, M, [STOVE], [GF, DF, NF], ["fish"],
  [("yam", "800g tapioca, peeled and cubed", "cassava is what is meant; yam is the closest thing in this pantry", True),
   ("fish", "500g steaks", "sardine or kingfish traditionally", True),
   ("coconut", "100g, grated", None, True),
   ("shallot", "12", None, True),
   ("green-chilli", "4", None, True),
   ("turmeric", "1 tsp", None, True),
   ("chilli-powder", "2 tsp", None, True),
   ("kokum", "4 pieces", "kudampuli, the smoked fish tamarind, is authentic; kokum is the nearest available", True),
   ("fenugreek-seeds", "1/4 tsp", None, True),
   ("curry-leaves", "3 sprigs", None, True),
   ("coconut-oil", "4 tbsp", None, True),
   ("salt", "to taste", None, True)],
  ["Two separate pots. The tapioca is boiled and mashed with coconut; the fish curry is cooked in a clay pot and stays thin and sharp.",
   "The curry should be aggressively sour and salty. It is a sauce for a bland, starchy partner."],
  [("Boil the tapioca in salted water until a knife slides through, about 25 minutes. Drain well.",),
   ("Crush the coconut with half the shallots, the green chilli and turmeric, and mash it through the hot tapioca.",),
   ("For the curry, soak the kokum in 200ml warm water.",),
   ("Fry the remaining shallots, fenugreek and curry leaves in the coconut oil, add the chilli powder and fry 1 minute.",),
   ("Add the kokum with its water, bring to a boil, then slide in the fish and simmer 10 minutes without stirring.",
    "Do not stir. Shake the pan instead or the fish breaks up."),
   ("Rest 15 minutes before serving alongside the mashed tapioca.",)],
  "The curry keeps 2 days refrigerated and improves overnight. The tapioca is best fresh; it stiffens hard when cold and needs steaming to revive.",
  []),

R("unniyappam", "Unniyappam", "Kerala",
  "banana and jaggery fritters fried in a dimpled pan, the temple offering",
  20, 20, 25, E, [STOVE], [VEG, GF, NF], ["dairy"],
  [("rice", "250g, soaked 4 hours and ground", None, True),
   ("jaggery", "200g, melted and strained", None, True),
   ("raw-banana", "2 ripe bananas, mashed", "ripe, not raw, despite the ingredient name", True),
   ("coconut", "4 tbsp, cut into small pieces and fried in ghee", None, True),
   ("cardamom", "6 pods, seeds ground", None, True),
   ("sesame", "1 tsp", None, True),
   ("dry-ginger-powder", "1/4 tsp", None, True),
   ("ghee", "2 tbsp", None, True),
   ("neutral-oil", "400ml for frying", None, True),
   ("salt", "a pinch", None, True)],
  ["An unniyappam pan (paniyaram pan) makes this straightforward. Without one, small spoonfuls deep fried work but lose the shape.",
   "The batter rests. An hour minimum, and it should fall thickly from a spoon."],
  [("Grind the soaked rice to a smooth, thick batter.",),
   ("Beat in the melted jaggery, mashed banana, cardamom, dry ginger and salt. Rest 1 hour.",),
   ("Fry the coconut pieces and sesame in the ghee until golden and stir them through.",),
   ("Heat the oil in the dimpled pan. Fill each hollow three-quarters full.",),
   ("Cook 3 minutes until the underside is dark, then turn each one with a skewer and cook 3 minutes more.",
    "Turn once only, and only when the edges have set."),
   ("Drain and eat warm.",)],
  "Keeps 3 days in an airtight box at room temperature and stays soft. The banana means it will not keep much beyond that.",
  []),

# -------------------------------------------------------------- Karnataka

R("goli-baje", "Goli Baje", "Karnataka",
  "soft, tangy gram flour dumplings from the Mangalore coast",
  20, 15, 25, E, [STOVE, KADHAI], [VEG, NF], ["dairy"],
  [("maida", "200g", None, True),
   ("besan", "60g", None, True),
   ("yogurt", "200g, sour", "sour curd is what gives goli baje its tang and its lift", True),
   ("green-chilli", "4, chopped", None, True),
   ("ginger", "1 tbsp, chopped", None, True),
   ("curry-leaves", "2 sprigs, torn", None, True),
   ("coconut", "3 tbsp, cut into slivers", None, True),
   ("baking-soda", "1/2 tsp", None, True),
   ("neutral-oil", "500ml for deep frying", None, True),
   ("salt", "to taste", None, True)],
  ["Also sold as Mangalore bajji. The batter must be thick enough to hold a rough ball dropped from the fingers.",
   "The batter needs a rest of at least 2 hours. That fermentation is the difference between light and leaden."],
  [("Whisk the yogurt smooth and mix in both flours, salt and the soda into a thick batter.",),
   ("Rest, covered, 2 to 3 hours at room temperature until it looks aerated.",),
   ("Fold in the green chilli, ginger, curry leaves and coconut slivers.",),
   ("Drop rough balls into medium-hot oil using wet fingers.",
    "Medium heat. Too hot and they brown before the middle sets."),
   ("Fry 5 minutes, turning, until deep gold all over. Drain and serve hot with coconut chutney.",)],
  "Eat within the hour. They deflate and toughen as they cool and do not reheat convincingly.",
  []),

R("mangalore-buns", "Mangalore Buns", "Karnataka",
  "sweet, puffed banana puris that stay soft for days",
  12, 20, 25, E, [STOVE, KADHAI], [VEG, NF], ["gluten", "dairy"],
  [("maida", "350g", None, True),
   ("raw-banana", "3 very ripe bananas, mashed", "the riper and blacker the better", True),
   ("sugar", "60g", None, True),
   ("yogurt", "3 tbsp", None, True),
   ("cumin-seeds", "1 tsp", None, True),
   ("baking-soda", "1/2 tsp", None, True),
   ("neutral-oil", "500ml for deep frying", None, True),
   ("salt", "1/2 tsp", None, True)],
  ["Despite the name they are puris, not bread. The dough must rest 6 hours or overnight, which is where the flavour comes from.",
   "No water goes in at all. The banana and curd carry the dough."],
  [("Mash the bananas with the sugar until liquid, then mix in the curd, cumin, soda and salt.",),
   ("Work in the flour to a soft dough. Add no water.",
    "It will feel sticky at first. Keep working it and it comes together."),
   ("Cover and rest 6 hours or overnight at room temperature. It will darken and smell faintly fermented.",),
   ("Roll into thick 10cm discs, thicker than a normal puri.",),
   ("Fry one at a time in hot oil, pressing gently with the back of a slotted spoon until it puffs, then turn.",),
   ("Drain and serve warm with coconut chutney.",)],
  "Keeps 2 days in an airtight box at room temperature and stays notably soft, which is what they are known for.",
  []),
]
