"""Recipe batch, expanded by tools/add_recipes.py into data/recipes.json."""
from add_recipes import R

E, M, A = "easy", "moderate", "advanced"
STOVE, PC, STEAM, BLEND, OVEN, KADHAI, TAWA = (
    "stovetop", "pressure-cooker", "steamer", "blender", "oven", "kadhai", "tawa")
VEG, VGN, GF, DF, NF, NOG = (
    "vegetarian", "vegan", "gluten-free", "dairy-free", "nut-free", "no-onion-garlic")

BATCH = [

# ---------------------------------------------------------------- Awadhi
R("galouti-kebab", "Galouti Kebab", "Awadhi/Lucknowi",
  "Minced mutton kebabs so soft they collapse on the tongue, from the Nawab's kitchen",
  4, 30, 20, A, [STOVE, TAWA, BLEND], [GF], ["dairy", "nuts"],
  [("mutton","500g, finely minced twice",None,True),
   ("raw-papaya","2 tbsp paste","the tenderiser that gives galouti its name",True),
   ("ghee","4 tbsp",None,True),
   ("onion","2, sliced and fried till brown (birista)",None,True),
   ("cashew","2 tbsp, ground",None,True),
   ("garam-masala","1 tsp",None,True),
   ("mace","1/4 tsp",None,True),
   ("nutmeg","a scraping",None,False),
   ("cardamom","4, ground",None,True),
   ("ginger","1 tbsp paste",None,True),
   ("garlic","1 tbsp paste",None,True),
   ("saffron","a pinch in warm milk",None,False),
   ("besan","1 tbsp, roasted","only if the mix will not hold",False),
   ("salt","to taste",None,True)],
  ["Galouti was reputedly made for a Nawab who had lost his teeth, so texture is the whole point: the mince must be ground to a paste, not merely chopped.",
   "Raw papaya paste is the tenderiser. Do not overdo it or the meat turns mushy, and do not marinate longer than an hour."],
  [("Blend the mince to a smooth paste with the papaya, ginger and garlic. Rest 45 minutes, refrigerated.",),
   ("Fry the sliced onion in ghee until deep brown, drain, cool and crush to a powder. This birista carries most of the sweetness.",
    "Browned, not burnt — bitter birista ruins the kebab."),
   ("Work the birista, ground cashew, garam masala, mace, nutmeg, cardamom, saffron milk and salt into the mince. It should be soft but hold a shape; add the roasted besan only if it will not.",),
   ("Chill the mix 30 minutes, then shape into flat discs about 6cm across and 1cm thick.",),
   ("Fry on a tawa in ghee over low-medium heat, 3-4 minutes a side. Turn once and gently — they are fragile.",
    "Low heat: high heat sets a crust before the centre cooks."),
   ("Serve immediately with ulte tawe ka paratha or plain sheermal.",)],
  "Best straight from the pan. The raw mix keeps 24 hours refrigerated and shapes better cold; cooked kebabs reheat poorly and dry out.",
  ["bhuna"], "awadhi-g1.jpg"),

R("nihari", "Nihari", "Awadhi/Lucknowi",
  "Overnight shank stew, thickened with wheat flour and finished with ginger and lime",
  6, 20, 300, A, [STOVE], [DF, NF], [],
  [("mutton","1kg shank on the bone, with marrow",None,True),
   ("atta","3 tbsp","the traditional thickener",True),
   ("onion","3, sliced",None,True),
   ("ginger","3 tbsp, half paste half julienne",None,True),
   ("garlic","2 tbsp paste",None,True),
   ("fennel-powder","2 tsp",None,True),
   ("dry-ginger-powder","1 tsp",None,True),
   ("chilli-powder","2 tsp",None,True),
   ("turmeric","1 tsp",None,True),
   ("garam-masala","1 tsp",None,True),
   ("black-cardamom","2",None,False),
   ("cinnamon","2 pieces",None,False),
   ("bay-leaf","2",None,False),
   ("lemon","2",None,True),
   ("coriander-leaves","to finish",None,False),
   ("green-chilli","to finish",None,False),
   ("ghee","6 tbsp",None,True),
   ("salt","to taste",None,True)],
  ["Nihari comes from nahar, meaning morning: it was cooked overnight and eaten at dawn. The long, low cook is not optional — it is what turns shank into something spoonable.",
   "Shank with marrow bones is the cut. Boneless meat makes a curry, not nihari."],
  [("Brown the sliced onion in ghee, then add the ginger and garlic pastes and cook until the raw smell goes.",),
   ("Add the powdered spices with a splash of water so they do not scorch, then the mutton. Turn it in the masala over high heat until sealed.",),
   ("Add 2 litres of water and the whole spices. Bring to a boil, then drop to the barest simmer, cover, and cook 4-5 hours until the meat slides off the bone.",
    "A trembling surface, not a rolling boil. Boiling makes the meat stringy."),
   ("Whisk the atta into a cup of cold water until perfectly smooth and stir it into the pot. Simmer 30 minutes more, stirring often, until the gravy coats a spoon.",
    "Cold water and hard whisking, or you will get lumps you cannot remove."),
   ("Rest off the heat 20 minutes; the fat will rise. Do not skim it — that layer is the point.",),
   ("Serve with julienned ginger, green chilli, coriander and a hard squeeze of lemon at the table.",)],
  "Improves for two days refrigerated and is arguably better on day two. Reheat gently with hot water. Freezes 2 months.",
  ["bhuna"], "awadhi-g2.jpg"),

R("lucknowi-biryani", "Lucknowi Dum Biryani", "Awadhi/Lucknowi",
  "Pakki biryani: meat and rice cooked separately, then sealed and finished on dum",
  6, 40, 60, A, [STOVE, OVEN], [GF, NF], ["dairy"],
  [("mutton","800g on the bone",None,True),
   ("basmati-rice","3 cups, soaked 30 min",None,True),
   ("yogurt","1 cup, whisked",None,True),
   ("onion","3, sliced and fried to birista",None,True),
   ("ginger","2 tbsp paste",None,True),
   ("garlic","2 tbsp paste",None,True),
   ("saffron","a good pinch in 1/4 cup warm milk",None,True),
   ("cardamom","6",None,True),
   ("black-cardamom","2",None,False),
   ("cinnamon","2 pieces",None,True),
   ("cloves","6",None,True),
   ("bay-leaf","2",None,False),
   ("mace","1/2 tsp",None,False),
   ("kewra-water","1 tsp",None,False),
   ("mint","a handful",None,True),
   ("ghee","5 tbsp",None,True),
   ("atta","for sealing the lid",None,False),
   ("salt","to taste",None,True)],
  ["Awadhi biryani is subtle by design — where Hyderabadi is fiery, this is perfumed. Resist adding chilli powder or turmeric; the colour should be white and gold, not red.",
   "Rice is boiled to 70% before layering. Fully cooked rice turns to paste on dum."],
  [("Cook the mutton with yogurt, ginger, garlic, half the birista, the whole spices and salt until tender and almost dry, about 45 minutes. This is the korma base.",),
   ("Boil the soaked rice in heavily salted water with a bay leaf until it is 70% done — the grain should still have a firm core when pressed.",
    "Drain the moment it reaches that stage; it keeps cooking on dum."),
   ("Layer: meat at the bottom, rice over it, then the saffron milk, remaining birista, mint, kewra and ghee across the top.",),
   ("Seal the lid with a rope of atta dough, or cover tightly with foil and a lid.", None, "dum"),
   ("Cook on the lowest possible heat for 25 minutes — over a tawa if your burner runs hot — or in a 160C oven.",),
   ("Rest 10 minutes before breaking the seal, then lift from the bottom with a flat spoon so the grains stay whole.",)],
  "Keeps 2 days refrigerated. Reheat covered with a sprinkle of water so the rice steams rather than fries. Freezing makes the grains brittle.",
  ["dum"], "awadhi-hero.jpg"),

# ---------------------------------------------------------------- Bengali
R("shorshe-ilish", "Shorshe Ilish", "Bengali",
  "Hilsa poached in a raw mustard paste, the dish Bengal argues about most",
  4, 20, 15, M, [STOVE, BLEND], [GF, DF, NF], ["fish"],
  [("fish","6 pieces hilsa","any oily river fish; do not skin it",True),
   ("mustard-seeds","4 tbsp, half yellow half black",None,True),
   ("green-chilli","6, whole",None,True),
   ("turmeric","1 tsp",None,True),
   ("nigella","1/2 tsp",None,False),
   ("mustard-oil","6 tbsp","not negotiable here",True),
   ("salt","to taste",None,True)],
  ["Mustard turns bitter if the paste is ground hot or too long. Soak the seeds, add a green chilli and a pinch of salt, and grind in short bursts.",
   "Hilsa is full of fine bones and is eaten carefully rather than filleted. Do not substitute a boneless fillet and expect the same dish."],
  [("Soak the mustard seeds 20 minutes in warm water, then grind with 2 green chillies and a pinch of salt to a smooth paste. Strain if you want it silky.",
    "Short bursts. Overgrinding is what makes mustard bitter."),
   ("Rub the fish with turmeric and salt and rest 10 minutes.",),
   ("Heat the mustard oil until it just smokes, then take it off the heat for a moment — this removes the raw pungency.",),
   ("Return to low heat, add the nigella, then the mustard paste thinned with half a cup of water, the remaining chillies and salt. Simmer 3 minutes.",
    "Do not brown the paste; this is a raw mustard sauce, not a bhuna."),
   ("Slide in the fish in a single layer, spoon the sauce over, cover and cook 8 minutes. Do not stir — shake the pan.",),
   ("Finish with a tablespoon of raw mustard oil poured over, and rest 5 minutes before serving with plain rice.",)],
  "Eat the same day. Hilsa firms unpleasantly on reheating and mustard sauces turn bitter overnight. Do not freeze.",
  [], "bengali-g2.jpg"),

R("kosha-mangsho", "Kosha Mangsho", "Bengali",
  "Mutton slow-fried in its own masala until almost dry and very dark",
  4, 20, 90, M, [STOVE], [GF, DF, NF], [],
  [("mutton","750g on the bone",None,True),
   ("yogurt","1/2 cup",None,True),
   ("onion","4, sliced",None,True),
   ("ginger","2 tbsp paste",None,True),
   ("garlic","2 tbsp paste",None,True),
   ("turmeric","1 tsp",None,True),
   ("chilli-powder","2 tsp",None,True),
   ("coriander-powder","2 tsp",None,True),
   ("cumin-powder","1 tsp",None,True),
   ("garam-masala","1 tsp",None,True),
   ("bay-leaf","2",None,False),
   ("cinnamon","2 pieces",None,False),
   ("cardamom","4",None,False),
   ("sugar","1 tsp","for colour, a Bengali habit",False),
   ("mustard-oil","5 tbsp",None,True),
   ("potato","2, halved and fried","optional but expected in Bengal",False),
   ("salt","to taste",None,True)],
  ["Kosha means to fry slowly and persistently. The dish is defined by that process, not by a sauce — you are looking for near-dry meat coated in dark masala.",
   "Marinate the mutton in yogurt and turmeric for at least an hour; overnight is better."],
  [("Marinate the mutton with yogurt, turmeric and salt for an hour.",),
   ("Heat the mustard oil to smoking, cool slightly, then caramelise the sugar until it darkens — this is where the colour comes from.",
    "Seconds, not minutes. Burnt sugar is bitter."),
   ("Add the whole spices and sliced onion and fry until genuinely brown, 12-15 minutes.",),
   ("Add ginger, garlic and the powdered spices, then the marinated mutton. Now begin koshano: fry over medium-low heat, stirring often, for 30-40 minutes.",
    "Add a splash of hot water whenever it catches, and keep frying. This is the whole recipe.", "bhuna"),
   ("When the oil separates and the meat is deep brown, add just enough hot water to cover, cover the pan and simmer 30-40 minutes until tender.",),
   ("Add the fried potatoes for the last 10 minutes, finish with garam masala, and reduce until the gravy clings.",)],
  "Better the next day. Keeps 3 days refrigerated, freezes 2 months.",
  ["bhuna"], "bengali-hero.jpg"),

R("rasgulla", "Rasgulla", "Bengali",
  "Chhena dumplings boiled in light syrup until they double and turn spongy",
  4, 30, 25, A, [STOVE], [VEG, GF, NF], ["dairy"],
  [("milk","2 litres full fat","not UHT — it will not curdle cleanly",True),
   ("lemon","2, juiced","or 3 tbsp vinegar",True),
   ("sugar","2 cups",None,True),
   ("cardamom","3, crushed",None,False),
   ("rose-water","1 tsp",None,False),
   ("maida","1 tsp","insurance against cracking",False),
   ("water","5 cups",None,True)],
  ["Everything depends on the chhena: drained enough to hold, moist enough to knead smooth. Squeeze it dry and the rasgulla turns rubbery.",
   "The syrup must be thin. A thick syrup cannot penetrate the dumpling and it stays raw in the middle."],
  [("Bring the milk to a boil, take it off the heat, and add lemon juice a little at a time until the curds separate cleanly from greenish whey.",),
   ("Strain through muslin and rinse under cold water to wash out the acid. Hang 30 minutes — no longer.",
    "Rinsing matters; unrinsed chhena tastes of lemon."),
   ("Knead the chhena on a plate with the heel of your hand for 8-10 minutes, until it goes from grainy to smooth and slightly greasy. Work in the maida if using.",
    "This is the step people cut short, and it is why rasgullas crack."),
   ("Roll into 12 crack-free balls, smaller than you want them finished — they double.",),
   ("Bring the sugar and water to a rolling boil with the cardamom. Slide the balls in, cover, and boil hard for 15 minutes.",
    "Hard boil, lid on. A gentle simmer will not inflate them."),
   ("Cool in the syrup, add rose water, and chill at least 4 hours before serving.",)],
  "Keeps 4 days refrigerated in its syrup, and the texture is best from the second day. Do not freeze.",
  [], "bengali-g1.jpg"),

# ---------------------------------------------------------------- Goan
R("vindaloo", "Pork Vindaloo", "Goan",
  "Vinegar-and-garlic pork, descended from Portuguese carne de vinha d'alhos",
  4, 30, 75, M, [STOVE, BLEND], [GF, DF, NF], [],
  [("pork","800g shoulder, in large cubes with some fat",None,True),
   ("dried-red-chilli","12 Kashmiri, soaked",None,True),
   ("vinegar","1/2 cup","palm vinegar if you can find it",True),
   ("garlic","15 cloves",None,True),
   ("ginger","2 tbsp",None,True),
   ("cumin-seeds","1 tsp",None,True),
   ("black-pepper","1 tsp",None,True),
   ("cinnamon","2cm",None,True),
   ("cloves","6",None,True),
   ("cardamom","4",None,False),
   ("turmeric","1/2 tsp",None,True),
   ("jaggery","1 tsp","balances the vinegar",False),
   ("onion","2, sliced",None,True),
   ("neutral-oil","3 tbsp",None,True),
   ("salt","to taste",None,True)],
  ["Vindaloo is not simply 'very hot'. The name is vinha d'alhos — wine and garlic — and the defining flavours are sour and garlicky, with Kashmiri chillies for colour rather than fire.",
   "Grind the masala with vinegar, never water. The vinegar is both the flavour and the preservative that let this dish travel."],
  [("Grind the soaked chillies, garlic, ginger and whole spices with the vinegar to a smooth, thick paste. Use no water.",),
   ("Rub half the paste into the pork with salt and marinate at least 4 hours, ideally overnight refrigerated.",),
   ("Fry the onion in oil until soft and golden, then add the remaining masala paste and cook until the oil separates.", None, "bhuna"),
   ("Add the pork with its marinade and turn it over high heat until sealed and coated.",),
   ("Add a cup of hot water, cover, and simmer 60 minutes until the pork is tender and the fat has rendered into the gravy.",),
   ("Balance with jaggery and salt. Rest overnight if you can — vindaloo is markedly better on day two.",)],
  "Genuinely improves for 3-4 days refrigerated; the vinegar preserves it. Freezes 3 months.",
  ["bhuna"], "goan-hero.jpg"),

R("bebinca", "Bebinca", "Goan",
  "Goa's layered coconut and egg cake, one grilled layer at a time",
  8, 25, 90, A, [OVEN], [VEG, NF], ["dairy", "gluten"],
  [("coconut-milk","400ml thick",None,True),
   ("eggs","8 yolks",None,True),
   ("maida","1.5 cups",None,True),
   ("sugar","1.5 cups",None,True),
   ("ghee","200g, melted",None,True),
   ("nutmeg","1/2 tsp",None,True),
   ("cardamom","1/2 tsp",None,False),
   ("salt","a pinch",None,True)],
  ["Bebinca is a test of patience: each layer is baked separately, and a traditional one runs to sixteen. Seven still tastes right.",
   "Ghee is brushed between layers. That fat is what lets them separate cleanly when sliced."],
  [("Whisk the yolks with the sugar until pale, then beat in the coconut milk, flour, nutmeg, cardamom and salt to a smooth, pourable batter. Rest 30 minutes.",),
   ("Heat the oven to 180C with the grill element on. Brush a deep tin generously with ghee and warm it.",),
   ("Pour in a thin ladle of batter — about 5mm — and grill 8-10 minutes until the top is browned and set.",
    "Browned, not merely set. The colour contrast between layers is the whole look."),
   ("Brush the baked layer with ghee, pour the next ladle over, and grill again. Repeat for at least seven layers.",),
   ("Cool completely in the tin, then turn out. Slicing warm will tear the layers apart.",
    "At least 3 hours. Overnight is better."),
   ("Serve at room temperature in thin wedges.",)],
  "Keeps a week in an airtight tin at room temperature and improves as it settles. Do not refrigerate — the ghee sets hard and the texture goes waxy.",
  [], "goan-g2.jpg"),

# ---------------------------------------------------------------- Gujarati
R("undhiyu", "Undhiyu", "Gujarati",
  "Surat's winter casserole of root vegetables and methi dumplings, cooked upside down",
  6, 45, 60, A, [STOVE, KADHAI], [VEG, VGN, GF, DF], ["nuts"],
  [("yam","200g, cubed",None,True),
   ("sweet-potato","200g, cubed",None,True),
   ("raw-banana","2, thick slices",None,True),
   ("potato","3 small, halved",None,True),
   ("eggplant","6 small, slit",None,True),
   ("cluster-beans","150g",None,True),
   ("dried-peas","1 cup, fresh tuvar if available",None,True),
   ("besan","1 cup","for the muthiya dumplings",True),
   ("methi-leaves","2 cups, chopped",None,True),
   ("coconut","1 cup, grated",None,True),
   ("coriander-leaves","1 cup",None,True),
   ("green-chilli","6",None,True),
   ("ginger","2 tbsp",None,True),
   ("sesame","2 tbsp",None,True),
   ("peanut","3 tbsp, crushed",None,False),
   ("ajwain","1 tsp",None,False),
   ("asafoetida","a pinch",None,True),
   ("jaggery","1 tbsp",None,True),
   ("lemon","1",None,True),
   ("groundnut-oil","6 tbsp",None,True),
   ("salt","to taste",None,True)],
  ["Undhiyu takes its name from undhu, upside down: it was buried in an inverted earthen pot and cooked in a pit. The domestic version layers everything in a heavy pot and never stirs it.",
   "The green masala of coconut, coriander, chilli and ginger goes both inside the slit vegetables and between the layers. Make it first."],
  [("Blend the coconut, coriander, green chilli, ginger, sesame, peanut, jaggery, lemon and salt to a coarse green masala.",),
   ("Make muthiya: knead the besan with chopped methi, a spoon of the masala, ajwain and a little water into a stiff dough; shape small dumplings and shallow fry until golden. Set aside.",),
   ("Stuff the slit eggplants and any halved potatoes with the green masala.",),
   ("In a heavy pot, heat the oil with asafoetida, then layer the vegetables hardest-first: yam and sweet potato at the bottom, then banana and potato, then beans and peas, stuffed eggplant on top.",
    "Layer by cooking time and do not stir — that is the whole method."),
   ("Spoon over the remaining masala and a splash of water, cover tightly and cook on low heat 35-40 minutes.",),
   ("Add the muthiya for the last 10 minutes so they soften without dissolving. Fold once, very gently, at the end.",)],
  "Keeps 2 days refrigerated. Reheat gently and briefly; the vegetables are already soft and will collapse. Not suitable for freezing.",
  ["bhuna"], "gujarati-g2.jpg"),

# ---------------------------------------------------------------- Hyderabadi
R("hyderabadi-biryani", "Hyderabadi Dum Biryani", "Hyderabadi",
  "Kachchi biryani: raw marinated mutton layered under rice and sealed from the start",
  6, 40, 70, A, [STOVE, OVEN], [GF], ["dairy", "nuts"],
  [("mutton","1kg on the bone",None,True),
   ("basmati-rice","3 cups, soaked 30 min",None,True),
   ("yogurt","1.5 cups, thick",None,True),
   ("onion","4, sliced and fried to birista",None,True),
   ("ginger","2 tbsp paste",None,True),
   ("garlic","2 tbsp paste",None,True),
   ("chilli-powder","2 tsp",None,True),
   ("turmeric","1/2 tsp",None,True),
   ("garam-masala","2 tsp",None,True),
   ("mint","1 cup",None,True),
   ("coriander-leaves","1 cup",None,True),
   ("saffron","a pinch in warm milk",None,True),
   ("lemon","2",None,True),
   ("cardamom","6",None,True),
   ("cinnamon","2 pieces",None,True),
   ("cloves","6",None,True),
   ("bay-leaf","2",None,False),
   ("ghee","6 tbsp",None,True),
   ("atta","for sealing",None,False),
   ("salt","to taste",None,True)],
  ["Kachchi means raw: the mutton goes in uncooked and must finish in the same time as the rice. That only works with a long marination and a tender cut.",
   "Marinate at least 6 hours, ideally overnight. This is the single biggest determinant of success."],
  [("Marinate the mutton with yogurt, ginger, garlic, chilli, turmeric, garam masala, half the birista, half the herbs, lemon juice and salt. Refrigerate 6 hours or overnight.",),
   ("Bring the marinated meat to room temperature and spread it in a heavy pot with 3 tbsp ghee.",),
   ("Boil the rice in well-salted water with the whole spices until 70% done, then drain immediately.",
    "A firm core in the grain. It finishes on dum."),
   ("Layer the rice over the raw meat. Top with the remaining birista, herbs, saffron milk and ghee.",),
   ("Seal with a dough rope or tight foil. Cook on high for 5 minutes to build steam, then on the lowest heat for 45 minutes.", None, "dum"),
   ("Rest 15 minutes before opening. Serve with mirchi ka salan and dahi chutney.",)],
  "Keeps 2 days refrigerated. Reheat covered with a splash of water. The rice suffers in the freezer.",
  ["dum"], "hyderabadi-hero.jpg"),

R("haleem", "Haleem", "Hyderabadi",
  "Wheat, lentils and mutton pounded together for hours into a smooth, savoury porridge",
  8, 30, 240, A, [STOVE, PC], [NF], ["gluten", "dairy"],
  [("dalia","1.5 cups, soaked 4 hours",None,True),
   ("mutton","750g on the bone",None,True),
   ("chana-dal","1/2 cup",None,True),
   ("masoor-dal","1/4 cup",None,True),
   ("moong-dal","1/4 cup",None,True),
   ("urad-dal","2 tbsp",None,False),
   ("onion","4, sliced and fried to birista",None,True),
   ("ginger","3 tbsp",None,True),
   ("garlic","2 tbsp",None,True),
   ("chilli-powder","2 tsp",None,True),
   ("turmeric","1 tsp",None,True),
   ("garam-masala","2 tsp",None,True),
   ("mint","1 cup",None,True),
   ("lemon","3",None,True),
   ("ghee","150g","haleem is not a lean dish",True),
   ("salt","to taste",None,True)],
  ["Haleem is Ramadan food, cooked in enormous pots and beaten with a wooden paddle until no individual grain or fibre remains. At home, a hand blender does the same job.",
   "Do not blend it completely smooth — it should be homogenous but still have body."],
  [("Pressure cook the soaked dalia and the mixed dals with turmeric and plenty of water until collapsing, about 5 whistles.",),
   ("Separately, cook the mutton with ginger, garlic, chilli powder, half the birista and salt until it falls off the bone. Reserve the stock.",),
   ("Pick the meat off the bones and shred it finely; discard the bones but keep every drop of stock.",),
   ("Combine meat, grain and stock in a wide heavy pot. Now beat and mash over low heat for 45-60 minutes, adding ghee in stages.",
    "This is the recipe. Under-beaten haleem tastes like lentil soup with meat in it."),
   ("When it pulls away from the sides of the pot in a single mass, stir in garam masala and mint.",),
   ("Serve topped with birista, fried mint, ginger julienne and a lot of lemon.",)],
  "Keeps 3 days refrigerated and thickens to a solid block; loosen with hot water and a little ghee when reheating. Freezes 2 months.",
  ["bhuna"], "hyderabadi-g1.jpg"),

R("qubani-ka-meetha", "Qubani ka Meetha", "Hyderabadi",
  "Dried apricots stewed to a glossy compote, served with cream and blanched kernels",
  6, 15, 40, E, [STOVE], [VEG, GF, DF], [],
  [("dried-apricot","500g Hunza apricots, soaked overnight",None,True),
   ("sugar","1 cup, to taste",None,True),
   ("cardamom","3",None,False),
   ("lemon","1/2",None,False),
   ("cream","to serve",None,False),
   ("almonds","to serve","the apricot kernels traditionally",False),
   ("water","2 cups",None,True)],
  ["Use whole dried apricots with stones, not the bright orange sulphured halves. The stones are cracked and the kernels blanched and served on top.",
   "Soak overnight. There is no shortcut that produces the same texture."],
  [("Soak the apricots in water overnight until plump. Keep the soaking water.",),
   ("Pit them, reserving the stones. Crack the stones and blanch the kernels; the skins slip off.",),
   ("Simmer the fruit in its soaking water with the sugar and cardamom over low heat, 30-40 minutes, until it collapses into a thick glossy compote.",
    "Mash some against the side of the pan and leave the rest in pieces."),
   ("Sharpen with lemon if the apricots were very sweet.",),
   ("Cool. Serve at room temperature or chilled, topped with cream and the blanched kernels.",)],
  "Keeps a week refrigerated and the flavour deepens. Freezes 3 months.",
  [], "hyderabadi-g2.jpg"),

# ---------------------------------------------------------------- Kashmiri
R("rogan-josh", "Rogan Josh", "Kashmiri",
  "Kashmiri lamb in a red gravy coloured by ratan jot and Kashmiri chilli, without onion or garlic",
  4, 20, 90, M, [STOVE], [GF, NOG], ["dairy"],
  [("mutton","800g on the bone",None,True),
   ("yogurt","1 cup, whisked",None,True),
   ("kashmiri-chilli","3 tbsp","the colour comes from here, not from heat",True),
   ("fennel-powder","2 tbsp",None,True),
   ("dry-ginger-powder","1 tbsp",None,True),
   ("asafoetida","a good pinch",None,True),
   ("black-cardamom","2",None,True),
   ("cardamom","4",None,True),
   ("cinnamon","2 pieces",None,True),
   ("cloves","5",None,True),
   ("bay-leaf","2",None,False),
   ("ghee","5 tbsp",None,True),
   ("salt","to taste",None,True)],
  ["Kashmiri Pandit cooking uses no onion or garlic at all. Fennel and dry ginger do that work, which is why both are in tablespoons here rather than teaspoons.",
   "The red is from Kashmiri chilli and traditionally ratan jot (alkanet root), not from tomato — there is no tomato in this dish."],
  [("Heat the ghee and bloom the asafoetida and whole spices until fragrant.",),
   ("Add the mutton and sear over high heat until browned on all sides.",),
   ("Take the pan off the heat. Stir the Kashmiri chilli, fennel and dry ginger into the whisked yogurt, then add it to the meat, stirring constantly.",
    "Off the heat and constant motion — this is where yogurt splits."),
   ("Return to low heat and cook, stirring, until the gravy thickens and the fat begins to show, about 10 minutes.", None, "bhuna"),
   ("Add a cup of hot water and salt, cover, and simmer 60-70 minutes until the meat is tender and the gravy is deep red and glossy.",),
   ("Rest 15 minutes. Serve with plain rice.",)],
  "Keeps 3 days refrigerated and improves overnight. Freezes 2 months; the yogurt-based gravy can look grainy on thawing but comes back together when reheated slowly.",
  ["bhuna", "hing"], "kashmiri-hero.jpg"),

R("kashmiri-pulav", "Kashmiri Pulav", "Kashmiri",
  "Mildly sweet saffron rice with fruit and nuts, served alongside the wazwan",
  4, 15, 25, E, [STOVE], [VEG, GF, NOG], ["dairy", "nuts"],
  [("basmati-rice","2 cups, soaked 30 min",None,True),
   ("milk","1 cup",None,True),
   ("saffron","a good pinch",None,True),
   ("cardamom","4",None,True),
   ("cinnamon","1 piece",None,True),
   ("cloves","4",None,False),
   ("bay-leaf","1",None,False),
   ("fennel-powder","1 tsp",None,False),
   ("almonds","2 tbsp",None,True),
   ("cashew","2 tbsp",None,False),
   ("raisins","2 tbsp",None,True),
   ("pomegranate","1/2 cup seeds","to finish",False),
   ("sugar","1 tsp",None,False),
   ("ghee","3 tbsp",None,True),
   ("salt","to taste",None,True)],
  ["The sweetness should be barely there — this is a foil for rich meat dishes, not a dessert. One teaspoon of sugar for two cups of rice is enough.",
   "Warm the saffron in the milk for ten minutes before using; dropping threads into the pot does almost nothing."],
  [("Warm the milk and steep the saffron in it.",),
   ("Fry the nuts and raisins in ghee until the nuts colour and the raisins puff. Lift out and reserve.",),
   ("In the same ghee, bloom the whole spices, then add the drained rice and turn it gently for 2 minutes.",
    "Gently — soaked grains break easily."),
   ("Add the saffron milk, 2.5 cups water, sugar and salt. Bring to a boil, then cover and cook on the lowest heat 12 minutes.",),
   ("Rest, covered and off the heat, a further 10 minutes before lifting the lid.",),
   ("Fork through the fried nuts and raisins and scatter pomegranate over the top.",)],
  "Keeps 2 days refrigerated. Reheat covered with a splash of water. Add the pomegranate fresh rather than storing it in the rice.",
  [], "kashmiri-g1.jpg"),

# ---------------------------------------------------------------- Kerala
R("appam", "Appam", "Kerala",
  "Lacy fermented rice pancakes with a soft, thick centre",
  4, 20, 25, M, [STOVE, BLEND], [VEG, VGN, GF, DF, NF], [],
  [("rice","2 cups, soaked 4 hours",None,True),
   ("coconut","1/2 cup grated",None,True),
   ("coconut-milk","1/2 cup",None,True),
   ("rice","1/4 cup cooked","helps the batter ferment and spread",False),
   ("sugar","1 tsp","feeds the ferment",True),
   ("salt","to taste",None,True),
   ("coconut-oil","for the pan",None,True)],
  ["Appam batter ferments like dosa batter but is thinner and sweeter. It should pour, not spread.",
   "The pan matters: a deep, round-bottomed appachatti is what makes the edges lacy and the centre thick. A small wok is the closest substitute."],
  [("Grind the soaked rice with the grated coconut, cooked rice and enough water to make a smooth, pourable batter.",),
   ("Add sugar, cover, and leave to ferment 8-10 hours until risen and faintly sour.",),
   ("Stir in the coconut milk and salt. The batter should be thinner than dosa batter — like single cream.",
    "Too thick and you get a pancake; too thin and it will not hold a centre."),
   ("Heat the appachatti, wipe with coconut oil, pour a ladle into the middle, then immediately lift the pan and swirl it once so batter climbs the sides.",),
   ("Cover and cook 2-3 minutes on low. Do not flip.",
    "The lid is what steams the thick centre while the edges crisp."),
   ("Lift out when the edges lift away on their own. Serve with stew, kadala curry or sweetened coconut milk.",)],
  "Batter keeps 3 days refrigerated and grows more sour; older batter suits appam less well than dosa. Cooked appams do not keep.",
  [], "kerala-g2.jpg"),

R("avial", "Avial", "Kerala",
  "Mixed vegetables bound in coconut, cumin and yogurt, finished with raw coconut oil",
  6, 25, 25, E, [STOVE, BLEND], [VEG, GF, NF], ["dairy"],
  [("raw-banana","1, in batons",None,True),
   ("yam","150g, in batons",None,True),
   ("drumstick","2, in 5cm pieces",None,True),
   ("carrot","2, in batons",None,True),
   ("french-beans","100g",None,True),
   ("ash-gourd","150g, in batons",None,False),
   ("cucumber","1, in batons","the Kerala vellarikka",False),
   ("coconut","1.5 cups grated",None,True),
   ("cumin-seeds","1 tsp",None,True),
   ("green-chilli","4",None,True),
   ("turmeric","1/2 tsp",None,True),
   ("yogurt","1/2 cup, sour, whisked",None,True),
   ("curry-leaves","2 sprigs",None,True),
   ("coconut-oil","3 tbsp","2 for cooking, 1 raw at the end",True),
   ("salt","to taste",None,True)],
  ["Everything is cut to the same baton shape and size so it cooks evenly and looks right — this is not a dish where you cube things.",
   "The final spoon of raw coconut oil is not optional. It is the smell of avial."],
  [("Cook the vegetables hardest-first in a wide pan with turmeric, salt and just enough water — yam and banana first, softer vegetables after.",
    "Barely enough water. Avial is not a curry and should not be swimming."),
   ("Coarsely grind the coconut with cumin and green chilli. Do not make it a smooth paste.",
    "Coarse. The texture of avial comes from the ground coconut."),
   ("Fold the coconut mixture through the cooked vegetables and simmer 5 minutes.",),
   ("Take the pan off the heat, then stir in the whisked yogurt. Return briefly to very low heat but do not let it boil.",
    "Boiling after the yogurt goes in will split it."),
   ("Crush the curry leaves between your palms and stir them in with the raw coconut oil.",),
   ("Rest 10 minutes before serving. Avial is served warm, not hot.",)],
  "Keeps 2 days refrigerated. Reheat very gently — the yogurt splits over direct heat. Do not freeze.",
  ["curry-leaves"], "kerala-hero.jpg"),

# ---------------------------------------------------------------- Maharashtrian
R("misal-pav", "Misal Pav", "Maharashtrian",
  "Sprouted beans under a fiery kat, topped with farsan and eaten with pav",
  4, 25, 45, M, [STOVE, PC, BLEND], [VEG, VGN, DF], ["gluten", "nuts"],
  [("sprouted-moth","2 cups",None,True),
   ("onion","3, two for the masala",None,True),
   ("tomato","2",None,True),
   ("coconut","1/2 cup, dry roasted",None,True),
   ("garlic","8 cloves",None,True),
   ("ginger","1 tbsp",None,True),
   ("chilli-powder","2 tbsp","Kolhapuri if you have it",True),
   ("coriander-powder","1 tbsp",None,True),
   ("cumin-powder","1 tsp",None,True),
   ("turmeric","1/2 tsp",None,True),
   ("garam-masala","1 tsp","goda masala traditionally",True),
   ("mustard-seeds","1 tsp",None,True),
   ("curry-leaves","1 sprig",None,True),
   ("peanut","2 tbsp",None,False),
   ("sesame","1 tbsp",None,False),
   ("pav","8",None,True),
   ("lemon","2",None,True),
   ("coriander-leaves","to finish",None,False),
   ("groundnut-oil","5 tbsp",None,True),
   ("salt","to taste",None,True)],
  ["Misal is two things in one bowl: the usal, a mild sprouted-bean curry, and the kat, the fiery red oil-slicked gravy poured over it. Make them separately.",
   "The floating layer of red oil on top is the signature. Do not stir it in or skim it off."],
  [("Pressure cook the sprouts with turmeric and salt until just tender, 2 whistles. They should hold their shape.",),
   ("For the kat masala, dry roast the coconut, peanut and sesame until deep brown, then blend with two onions, tomato, garlic and ginger to a paste.",
    "Take the coconut properly dark — that is where the colour and depth come from."),
   ("Heat oil, splutter the mustard seeds and curry leaves, add the remaining chopped onion, then the ground paste. Fry until the oil separates.", None, "bhuna"),
   ("Add the chilli powder, coriander, cumin and garam masala and cook a further 2 minutes.",),
   ("Add 3 cups of hot water and simmer 15 minutes. The kat should be thin and carry a visible layer of red oil.",),
   ("To serve, spoon the usal into bowls, ladle the kat over, and top with farsan, raw onion, coriander and lemon. Pav alongside.",)],
  "Usal and kat both keep 3 days refrigerated and are better on day two. Assemble only at the moment of serving or the farsan goes soft.",
  ["bhuna", "tadka"], "maharashtrian-g1.jpg"),

R("modak", "Ukadiche Modak", "Maharashtrian",
  "Steamed rice-flour dumplings filled with coconut and jaggery, made for Ganpati",
  4, 40, 20, A, [STOVE, STEAM], [VEG, VGN, GF, DF, NF], [],
  [("rice-flour","1 cup, fine",None,True),
   ("coconut","1.5 cups, freshly grated",None,True),
   ("jaggery","1 cup, grated",None,True),
   ("cardamom","1/2 tsp",None,True),
   ("nutmeg","a scraping",None,False),
   ("poppy-seeds","1 tsp",None,False),
   ("ghee","2 tsp","use oil to keep it vegan",True),
   ("water","1 cup",None,True),
   ("salt","a pinch",None,True)],
  ["The dough must be kneaded hot. Let it cool and it cracks, and no amount of water will save it — keep a bowl of water beside you and work fast.",
   "Fresh coconut only. Desiccated makes a dry, grainy filling."],
  [("For the filling, cook the coconut and jaggery together over medium heat until the jaggery melts and the mixture comes together but is still moist, 8-10 minutes. Add cardamom, nutmeg and poppy seeds. Cool.",
    "Stop while it is still moist; it hardens as it cools."),
   ("Boil the water with a pinch of salt and a teaspoon of ghee. Take it off the heat, tip in the rice flour all at once and stir hard until no dry flour remains. Cover 5 minutes.",),
   ("Turn out and knead while hot, greasing your palm with ghee, until completely smooth.",
    "Hot dough. This is the step that decides whether modaks crack."),
   ("Take a lime-sized ball, flatten into a cup with your fingers, pleat the edge into 9-11 folds, fill, then gather the pleats to a point and seal.",),
   ("Steam 10-12 minutes until the shells turn glossy and translucent.",),
   ("Serve warm with a spoon of ghee over the top.",)],
  "Best within a few hours. Keeps a day refrigerated but the shell hardens; steam 3-4 minutes to soften before serving. Do not freeze.",
  [], "maharashtrian-g2.jpg"),

# ---------------------------------------------------------------- Northeast
R("naga-smoked-pork", "Naga Smoked Pork with Bamboo Shoot", "Northeast Indian",
  "Smoked pork simmered with fermented bamboo shoot and raja mircha",
  4, 15, 75, M, [STOVE], [GF, DF, NF], [],
  [("pork","700g smoked pork belly, in cubes",None,True),
   ("bamboo-shoot","1 cup fermented, rinsed",None,True),
   ("green-chilli","4","raja mircha traditionally — use far less",True),
   ("ginger","2 tbsp",None,True),
   ("garlic","8 cloves",None,True),
   ("onion","1, sliced",None,False),
   ("tomato","1",None,False),
   ("coriander-leaves","to finish",None,False),
   ("salt","to taste",None,True)],
  ["Naga cooking uses very little oil and few spices; the flavour is carried by smoke, fermentation and heat. Adding garam masala here would be a mistake.",
   "Fermented bamboo shoot is pungent. Rinse it, and add it in stages, tasting as you go."],
  [("Rinse the fermented bamboo shoot in two changes of water and drain.",),
   ("Put the smoked pork in a pot with the ginger, garlic, chillies and just enough water to cover. Bring to a boil.",
    "No oil. The pork renders plenty of its own."),
   ("Simmer covered 45-60 minutes until the pork is tender and the water has reduced by half.",),
   ("Add the bamboo shoot and the onion and tomato if using, and cook a further 15 minutes.",
    "Taste before adding all the bamboo — its sourness varies enormously between batches."),
   ("Season with salt only at the end; smoked pork is already salty.",),
   ("Serve with plain rice and a raw chilli on the side.",)],
  "Keeps 3 days refrigerated and improves. Freezes 2 months.",
  [], "northeast-g1.jpg"),

R("momos", "Momos", "Northeast Indian",
  "Steamed dumplings with a juicy filling, eaten with a fiery tomato-chilli chutney",
  4, 45, 20, M, [STOVE, STEAM, BLEND], [DF, NF], ["gluten"],
  [("maida","2 cups",None,True),
   ("chicken","400g, minced","or finely chopped cabbage for a vegetarian version",True),
   ("cabbage","1 cup, very finely chopped",None,True),
   ("onion","1, very finely chopped",None,True),
   ("spring-onion","3, chopped",None,False),
   ("garlic","1 tbsp",None,True),
   ("ginger","1 tbsp",None,True),
   ("black-pepper","1 tsp",None,True),
   ("dried-red-chilli","6","for the chutney",True),
   ("tomato","3","for the chutney",True),
   ("neutral-oil","2 tbsp",None,True),
   ("salt","to taste",None,True)],
  ["Everything in the filling must be chopped very fine and kept raw — it cooks in the steamer, and any large piece will tear the wrapper.",
   "Do not salt the filling until just before you fill: salt draws water out of the cabbage and makes the dough soggy."],
  [("Knead the flour with water and a pinch of salt into a firm, smooth dough. Rest 30 minutes covered.", None, "resting-dough"),
   ("Mix the filling ingredients with the oil and pepper. Salt it only when you are ready to fill.",),
   ("Roll the dough very thin and cut 8cm rounds, keeping the edges thinner than the centre.",
    "Thin edges, thicker middle — otherwise the pleated top is doughy."),
   ("Place a spoon of filling in each, then pleat and seal into a half-moon or a gathered purse.",),
   ("Steam in a greased steamer for 10-12 minutes. The wrappers turn translucent and stop looking floury.",
    "Do not crowd them; they swell and stick together."),
   ("For the chutney, boil the tomatoes and dried chillies, then blend with garlic and salt. Serve alongside.",)],
  "Best straight from the steamer. Uncooked momos freeze well on a tray for a month — steam from frozen, adding 4 minutes. Cooked ones go rubbery.",
  ["resting-dough"], "northeast-g2.jpg"),

# ---------------------------------------------------------------- Odia
R("chhena-poda", "Chhena Poda", "Odia",
  "Odisha's baked cheesecake: fresh chhena and sugar caramelised until the top is almost burnt",
  6, 25, 60, M, [OVEN], [VEG, GF], ["dairy", "nuts"],
  [("milk","2 litres full fat",None,True),
   ("lemon","2, juiced",None,True),
   ("sugar","3/4 cup",None,True),
   ("rava","2 tbsp",None,True),
   ("cardamom","1/2 tsp",None,True),
   ("cashew","2 tbsp",None,False),
   ("raisins","2 tbsp",None,False),
   ("ghee","2 tbsp",None,True),
   ("sugar","2 tbsp, for caramel","separate from the sugar above",False)],
  ["Poda means burnt. The dark, almost-scorched top is the dish, not a mistake — pull it out pale and it is just baked cheese.",
   "Chhena for this should be soft and moist. Unlike rasgulla, do not hang it dry."],
  [("Curdle the milk with lemon juice, strain through muslin and rinse briefly. Hang only 20 minutes — it should stay moist.",),
   ("Knead the chhena smooth, then work in the sugar, rava, cardamom, nuts and raisins. Rest 15 minutes so the rava swells.",),
   ("Caramelise the 2 tbsp sugar in a ghee-greased tin and let it set at the bottom.",
    "Traditionally the batter sits on a lining of sal leaves, which is where the smoky note comes from."),
   ("Pour in the batter and bake at 180C for 50-60 minutes, until the top is deep brown to nearly black and a skewer comes out clean.",
    "Go further than instinct says. Brown is not enough."),
   ("Cool completely in the tin — at least 2 hours — before turning out.",),
   ("Serve at room temperature in wedges.",)],
  "Keeps 3 days refrigerated and firms as it sits. Bring back to room temperature before serving; cold chhena poda tastes flat.",
  [], "odia-g1.jpg"),

# ---------------------------------------------------------------- Rajasthani
R("dal-baati-churma", "Dal Baati Churma", "Rajasthani",
  "Baked wheat balls drowned in ghee, with a five-lentil dal and sweet crushed churma",
  4, 40, 75, A, [STOVE, OVEN, PC], [VEG], ["gluten", "dairy", "nuts"],
  [("atta","3 cups, coarse",None,True),
   ("rava","2 tbsp","for crunch in the baati",False),
   ("ghee","200g","this is not a dish to economise on",True),
   ("ajwain","1 tsp",None,True),
   ("toor-dal","1/2 cup",None,True),
   ("chana-dal","1/4 cup",None,True),
   ("moong-dal","1/4 cup",None,True),
   ("urad-dal","1/4 cup",None,True),
   ("masoor-dal","1/4 cup",None,False),
   ("onion","1, chopped",None,False),
   ("tomato","2",None,True),
   ("ginger","1 tbsp",None,True),
   ("garlic","6 cloves",None,False),
   ("cumin-seeds","1 tsp",None,True),
   ("asafoetida","a pinch",None,True),
   ("turmeric","1 tsp",None,True),
   ("chilli-powder","1 tsp",None,True),
   ("coriander-powder","1 tsp",None,True),
   ("garam-masala","1/2 tsp",None,True),
   ("jaggery","1/2 cup","for the churma",True),
   ("cardamom","1/2 tsp",None,False),
   ("almonds","2 tbsp","for the churma",False),
   ("salt","to taste",None,True)],
  ["Baati dough is stiff and barely hydrated — nothing like chapati dough. If it feels soft, it is wrong.",
   "The baatis are dunked in melted ghee straight from the oven. Skipping that leaves them dry and hard."],
  [("Make a stiff dough from atta, rava, ajwain, salt and 4 tbsp ghee with as little water as possible. Rest 20 minutes.", None, "resting-dough"),
   ("Shape into balls, press a dimple into each, and bake at 200C for 35-40 minutes, turning once, until cracked and deep golden.",
    "The cracks are what let the ghee in later. Do not smooth them over."),
   ("Meanwhile pressure cook the mixed dals with turmeric and salt until soft, 4 whistles.",),
   ("Temper cumin and asafoetida in ghee, add ginger, garlic and onion, then tomato and the powdered spices. Cook until the fat separates, then fold into the dal and simmer 10 minutes.", None, "tadka"),
   ("For the churma, crush a few baatis coarsely and work in jaggery, cardamom, chopped almonds and hot ghee.",),
   ("To serve, dunk each hot baati in melted ghee, break it open into the dal, and eat with churma on the side.",)],
  "Baatis keep 2 days in an airtight tin and reheat well in a hot oven. The dal keeps 3 days refrigerated and thickens. Churma keeps a week.",
  ["tadka", "resting-dough"], "rajasthani-hero.jpg"),

R("kachori", "Pyaaz Kachori", "Rajasthani",
  "Flaky fried pastry with a spiced onion filling, from the sweet shops of Jodhpur",
  6, 40, 30, A, [STOVE, KADHAI], [VEG, VGN, DF, NF], ["gluten"],
  [("maida","2 cups",None,True),
   ("ghee","6 tbsp","for the moyan; use oil to keep it vegan",True),
   ("onion","4, finely chopped",None,True),
   ("besan","2 tbsp",None,True),
   ("fennel-seeds","2 tsp",None,True),
   ("coriander-powder","2 tsp",None,True),
   ("cumin-seeds","1 tsp",None,True),
   ("nigella","1/2 tsp",None,False),
   ("chilli-powder","1 tsp",None,True),
   ("turmeric","1/2 tsp",None,True),
   ("garam-masala","1/2 tsp",None,True),
   ("amchur","1 tsp",None,True),
   ("asafoetida","a pinch",None,True),
   ("neutral-oil","for deep frying",None,True),
   ("salt","to taste",None,True)],
  ["Flakiness comes from moyan — fat rubbed into the flour before any water. When you squeeze a fistful and it holds its shape, you have enough.",
   "Fry low and slow. Hot oil puffs the outside and leaves the inside raw, and the kachori collapses as it cools."],
  [("Rub the ghee into the flour with salt until it holds together when squeezed, then add water a little at a time to make a firm dough. Rest 30 minutes.", None, "resting-dough"),
   ("Fry the cumin, fennel, nigella and asafoetida, add the onion and cook until soft and just golden, not brown.",),
   ("Add the besan and the powdered spices and cook 4-5 minutes until dry and crumbly. Add amchur, cool completely.",
    "The filling must be dry, or the kachori will burst in the oil."),
   ("Roll small dough balls into cups, fill, gather and seal, then flatten very gently to about 1cm.",),
   ("Fry in oil kept at a low 130-140C for 10-12 minutes, turning occasionally, until pale gold and covered in blisters.",
    "If they brown in under five minutes the oil is far too hot."),
   ("Drain on a rack. Serve warm with tamarind and coriander chutneys.",)],
  "Keeps 2 days in an airtight tin at room temperature. Refresh in a hot oven for 5 minutes; do not microwave or they go soft.",
  ["resting-dough"], "rajasthani-g2.jpg"),

# ---------------------------------------------------------------- South Indian
R("idli", "Idli", "South Indian",
  "Steamed cakes of fermented rice and urad dal, the lightest thing in Indian breakfast",
  4, 20, 20, M, [STOVE, STEAM, BLEND], [VEG, VGN, GF, DF, NF], [],
  [("rice","3 cups par-boiled idli rice",None,True),
   ("urad-dal","3/4 cup",None,True),
   ("fenugreek-seeds","1 tsp",None,True),
   ("poha","1/4 cup","makes softer idlis",False),
   ("salt","to taste",None,True)],
  ["The urad dal is ground first and separately, with cold water, until it is light and holds a peak. That aeration is what makes idlis fluffy — the fermentation only builds on it.",
   "Idli batter is thicker than dosa batter. If it pours easily it is too thin."],
  [("Soak the rice in one bowl and the urad dal with fenugreek in another, for 5 hours. Soak the poha for 20 minutes before grinding.",),
   ("Grind the urad dal first with cold water until white, fluffy and doubled in volume. Test it: a spoon of batter should float in water.",
    "This is the single most important step. Do not rush or overheat it."),
   ("Grind the rice to a slightly grainy paste, then fold the two together by hand with salt.",
    "By hand — the warmth helps fermentation start."),
   ("Cover loosely and ferment 8-12 hours until risen and bubbly.",),
   ("Grease the idli plates, fill three-quarters full, and steam 10-12 minutes. A skewer should come out clean.",
    "Do not oversteam; idlis turn dense and wet."),
   ("Rest 3 minutes before unmoulding, then serve with sambar and coconut chutney.",)],
  "Batter keeps 4 days refrigerated, growing more sour. Cooked idlis keep a day and steam back to life in 3 minutes; they are also the basis of idli upma.",
  [], "tamil-nadu-g1.jpg"),

R("sambar", "Sambar", "South Indian",
  "Toor dal and vegetables in a tamarind broth, built on freshly ground sambar powder",
  6, 20, 40, E, [STOVE, PC], [VEG, VGN, GF, DF, NF], [],
  [("toor-dal","1 cup",None,True),
   ("tamarind","a lime-sized ball, soaked",None,True),
   ("drumstick","2, in pieces",None,False),
   ("pumpkin","150g",None,False),
   ("okra","100g",None,False),
   ("shallot","10","sambar onions",True),
   ("tomato","2",None,True),
   ("sambar-powder","3 tbsp",None,True),
   ("turmeric","1/2 tsp",None,True),
   ("asafoetida","a good pinch",None,True),
   ("mustard-seeds","1 tsp",None,True),
   ("fenugreek-seeds","1/4 tsp",None,False),
   ("dried-red-chilli","2",None,True),
   ("curry-leaves","2 sprigs",None,True),
   ("coriander-leaves","to finish",None,False),
   ("jaggery","1 tsp",None,False),
   ("coconut-oil","2 tbsp","or sesame oil",True),
   ("salt","to taste",None,True)],
  ["Cook the tamarind broth and the vegetables together before the dal goes in. Vegetables added to dal never take on the sourness properly.",
   "Sambar powder loses its aroma quickly. If yours has been open six months, it is doing very little."],
  [("Pressure cook the toor dal with turmeric until completely soft, then whisk it smooth.",),
   ("Simmer the tamarind extract with the shallots, tomato and harder vegetables, the sambar powder and salt for 12-15 minutes.",
    "Cook the raw edge off the tamarind before the dal goes in."),
   ("Add quicker vegetables like okra for the last 5 minutes.",),
   ("Stir in the whisked dal and enough hot water to reach a pourable consistency. Simmer 8 minutes; do not boil hard.",),
   ("Temper mustard seeds, fenugreek, dried chilli, curry leaves and asafoetida in oil and pour it in.", None, "tadka"),
   ("Add jaggery if the tamarind is sharp, finish with coriander, and rest 10 minutes before serving.",)],
  "Keeps 3 days refrigerated and thickens; loosen with hot water. Freezes 2 months, though okra softens.",
  ["tadka", "hing"], "tamil-nadu-g2.jpg"),
]
